### ISSUE TITLE
Switching between apps works differently when clicking common header vs tiled navigation

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#102]
![switching-apps-bug](https://cloud.githubusercontent.com/assets/9273546/13540791/05f5a746-e22f-11e5-8503-4e7762a958be.gif)

To recreate:

Navigate to a sub company.
Open schedules, displays, etc.. in a new tab by clicking the link in the common header
It takes you to the parent company
Now open schedules, displays, etc.. in a new tab by clicking the link in the tiled navigation dropdown. 
It takes you to the app and you remain in the right company.

**Comment by ByronDarlison** [comment]
@ezequielc did we fix this once already? I seem to recall this... Thanks

**Comment by ezequielc** [comment]
@ByronDarlison We had a similar issue when navigating to Display details. The fix might be similar. Cheers

**Comment by ByronDarlison** [comment]
@ezequielc okay. Let's queue this up for the current sprint if we can. Thanks

**Comment by ezequielc** [comment]
@ByronDarlison Sounds good. Thanks!
