### ISSUE TITLE
Template Editor: Attributes List doesn’t appear on mobile landscape mode

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rise-vision-apps#1025]
### What happens
Users can't see or scroll the list of attributes when using mobile in landscape mode:

<img width="642" alt="Screen Shot 2019-06-10 at 6 01 02 PM" src="https://user-images.githubusercontent.com/7738553/59226616-cd344700-8ba9-11e9-8d49-7ea6f2faf08c.png">

### What should happen

User should be able to see the list and scroll to edit Template attributes.

**Comment by sheadarlison** [comment]
@ezequielc @alanclayton looking at GA it doesn't look like almost no one uses landscape on mobile. I think we could close this and see if anyone reports it as an issue. Thoughts?

FYI @stulees

**Comment by alanclayton** [comment]
@ezequielc  @sheadarlison 👍

**Comment by ezequielc** [comment]
@sheadarlison Makes sense. I am closing it. Thanks
