### ISSUE TITLE
Template Editor: Financial attribute list shows empty list message while loading data

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rise-vision-apps#1026]
### What happens
Behind the loading spinner, a message says that are no symbols in the list:

<img width="1128" alt="Screen Shot 2019-06-10 at 6 05 03 PM" src="https://user-images.githubusercontent.com/7738553/59226908-6e230200-8baa-11e9-8d4a-0694a16d4a57.png">

### What should happen
It should show a blank empty state, instead of a misleading message.

**Comment by stulees** [comment]
This has been fixed from changes in #1031
