### ISSUE TITLE
Feature Update: Remove filters

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1037]
@ezequielc How much effort would it be to remove these filters: https://www.screencast.com/t/55ddJHC9u

I'm using github issues to track this request as I thought it'd be easiest. 

Thanks 

FYI @alanclayton

**Comment by ezequielc** [comment]
@sheadarlison It is a simple change, one point. Thanks

**Comment by sheadarlison** [comment]
@ezequielc could you add it to your backlog without putting dates at risk?

**Comment by sheadarlison** [comment]
Card created, closing this.
