### ISSUE TITLE
Financial Data License Required popup does not show for non-editable Templates

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-vision-apps#1046]
**What currently happens**
The Financial Data License Required popup does not show when a non-editable Template is added to from the library.

**What should happen**
The popup should show for all Templates using financial data.

**Steps to Reproduce**
Add a Template that just has a non-editable financial component e.g. World Markets or Heatmap

**Comment by santiagonoguez** [comment]
So we'll need to add those to the blueprint along with a flag that mark them as editable or not.

**Comment by ezequielc** [comment]
@santiagonoguez Yes, agreed. Thanks!

**Comment by alex-deaconu** [comment]
@pcsandford @ezequielc this issue has now been resolved. As @santiagonoguez suggested, we have added the readonly components to the blueprint.json file, and updated all the Templates with Readonly Financial Components (based on the list provided by Peter) by rebuilding Beta/Stable. I've verified them all and the notification now shows as expected.

Thanks!
