### ISSUE TITLE
When trying to change the name of a selected item by highlighting/selecting the entire name, the pop-up window closes.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#1047]
### What is the expected behavior?
The properties window of the item you have selected does not disappear unless you press Save or Cancel.

### What is the actual behavior?
Whenever you try to change the name of a selected item by highlighting/selecting the entire name with my mouse, the pop-up window closes. The only way at this point to rename items is by clicking with the mouse at the end of a name and then deleting the name letter by letter by using the Backspace key.

### What steps can be taken to replicate the problem?
Open a Presentation item in a Schedule, and try to change the name of a Presentation item.

**Comment by ezequielc** [comment]
@robb-price I could not replicate the issue.
But is it the same as https://github.com/Rise-Vision/rise-vision-apps/issues/902 ? Thanks

**Comment by robb-price** [comment]
Closing until we can reliably recreate the issue, and confirming that it is not #902
