### ISSUE TITLE
rise-data-financial license dialog and auto-schedule dialog shown on top of each other

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/rise-vision-apps#1049]
If I'm a new user and I select a template with rise-data-financial as my first presentation, the license dialog appears; but then auto-save kicks in and as I'm a new user the auto-schedule dialog also appears. So both dialogs are appearing at the same time which doesn't provide a smooth user experience.

**Comment by sheadarlison** [comment]
@ezequielc @santiagonoguez what do you think about showing the auto schedule dialog when a user makes their first change or publishes the template?

**Comment by santiagonoguez** [comment]
@sheadarlison I like that idea. I've just commented with @ezequielc that I'll create a document with the alternatives we have, I'll put this one there so we can properly discuss. I hope it's ready for tomorrow morning or maybe even today.

**Comment by santiagonoguez** [comment]
Fixed here: https://github.com/Rise-Vision/rise-vision-apps/pull/1091
