### ISSUE TITLE
Rise Vision web apps asks for industry twice when signing up

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1054]
### What is the expected behavior?

When I sign up for the Rise Vision web app, I should only be asked for my industry once.

### What is the actual behavior?

When I sign up for the Rise Vision web app, I'm asked for my industry twice.

### What steps can be taken to replicate the problem?

https://www.loom.com/share/edaf3df30cc341ad9497ecdf026f6e58

**Comment by olegrise** [comment]
Issue if fixed. Thanks.
