### ISSUE TITLE
New user signup on website gives me error

### ISSUE THREAD

**Issue by nipuniitg** [Rise-Vision/rise-vision-apps#106]
Hi Risevision-dev,

I am hosting a customization of the Rise-vision-apps code in here on an amazon ec2 instance. The application works fine with a registered user on risevision.com . But if I try to do "Signup with Google" from the customized application using a new google account, it gives me the following error of "User is not found". Any help is deeply appreciated. Thanks

<img width="583" alt="screen shot 2016-03-13 at 7 20 00 pm" src="https://cloud.githubusercontent.com/assets/2149443/13729063/89b623de-e951-11e5-8da5-77bf4c1cc0cc.png">
<img width="452" alt="screen shot 2016-03-13 at 7 20 11 pm" src="https://cloud.githubusercontent.com/assets/2149443/13729064/8b760130-e951-11e5-9629-e9dd7de5fb4d.png">

**Comment by ByronDarlison** [comment]
Hi nipunitg, this works as designed and new users must be registered on rise vision apps. Thanks
