### ISSUE TITLE
Little squares appear in presentation when removing all images

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/rise-vision-apps#1060]
I've seen this in Pi, Ubuntu, and Windows players. It does not seem to happen in editor preview.

To reproduce, create a presentation for template 'QA for image component' here:
https://apps.risevision.com/editor/list?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

Open the presentation in the player

Then remove the images in all components, and publish. For some of the images, little squares are shown ( see capture below ). If the player is restarted, the problem disappears.

![squares_arrows](https://user-images.githubusercontent.com/33162690/59877452-8265bc80-936b-11e9-9636-a4e5ce8e6e01.png)

**Comment by santiagonoguez** [comment]
@fjvallarino FYI

**Comment by stulees** [comment]
Fixed with change to _rise-image_ in PR https://github.com/Rise-Vision/rise-image/pull/20
