### ISSUE TITLE
Images with special characters in names or paths not showing in editor preview or player

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/rise-vision-apps#1063]
To reproduce use this company:
https://apps.risevision.com/editor/list?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

I created the following images and folders in storage:
- apache (" !"#$%&'*+,-.:;<=>?@[\]^_`{|}~)|.jpg
- special (" !"#$%&'*+,-.:;<=>?@[\]^_`{|}~)

If in rise-image settings I pick that first image or images in that second directory, they don't show in the preview editor, or in the display after publishing.

**Comment by stulees** [comment]
This is now fixed by deploying #1143 and rise-image changes in https://github.com/Rise-Vision/rise-image/pull/34
