### ISSUE TITLE
If an image is deleted from storage, editor preview still shows it

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/rise-vision-apps#1066]
If an image is deleted from storage, and the presentation is reloaded, the image list correctly marks it as non existent, but editor preview still shows it ( from cache - the second image below should not appear ).

![still-appearing](https://user-images.githubusercontent.com/33162690/59938331-4e95a000-941a-11e9-902f-05650828a4f0.png)

rise-image in editor preview could use the same existence flag that the image list uses to avoid displaying it, so it will reflect the behavior in the display ( where this works ok, the image is not shown ).

**Comment by sheadarlison** [comment]
@santiagonoguez @stulees I'm re-opening this, I think we need to have preview always show the latest state when a user opens the template. I don't think our solution is good enough. (trello convo for reference: https://trello.com/c/tHPRbEuE/7053-issue-1066-if-an-image-is-deleted-from-storage-editor-preview-still-shows-it-2) 

FYI @alanclayton

**Comment by santiagonoguez** [comment]
@sheadarlison it's ok, thanks ! As I commented before, some refactorings that were already planned for video epic will help us implement the changes needed here more easily. Those changes are part of the first card I have in backlog for video epic, so we could attend the remaining corrections just after that.

@stulees

**Comment by stulees** [comment]
@sheadarlison @alanclayton On the back of what @santiagonoguez mentions above, I think this issue needs to be addressed after July 25th zero defects date so we can apply a long-term solution/fix. As SAntiago mentioned, the fix will be absorbed in upcoming cards in the Epic. Let us know if you agree to move the date of this defect. Thanks
