### ISSUE TITLE
Editor preview does not work in Samsung Browser.

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/rise-vision-apps#1075]
It does work in Chrome browser for Samsung ( Galaxy S8 )

Samsung browser capture below:

![samsung](https://user-images.githubusercontent.com/33162690/60038549-49cf2700-967a-11e9-8fe0-0d59d29b1708.png)

**Comment by andrecardoso** [comment]
I can't reproduce this. It is working fine on both Chrome and Samsung browser.
