### ISSUE TITLE
rise-image storage allows adding the same image multiple times from storage

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/rise-vision-apps#1076]
If I click 'select from storage' and I select the same image multiple times, it is added to the image list multiple times. It should only allow an image to be loaded once into the selection list.

![repeated](https://user-images.githubusercontent.com/33162690/60039471-666c5e80-967c-11e9-9a84-0ad2a93b22e4.png)

**Comment by sheadarlison** [comment]
@santiagonoguez I'm not sure if this is a defect, a user might want to have the same image appear multiple times in a set of images. Like they want something like: 

Image A
Image B 
Image A 
Image C
Image A
Image D
etc...

**Comment by santiagonoguez** [comment]
@sheadarlison good point, then it maybe is not a defect, as you say. I don't think is worth invert effort in trying to avoid this situation when they repeat the same unique image if they wish. If you agree I'll close this. Thanks !

**Comment by sheadarlison** [comment]
@santiagonoguez sounds good, lets close. Thanks
