### ISSUE TITLE
New Subscription not unlocking widgets, or seen as active

### ISSUE THREAD

**Issue by tylermwight** [Rise-Vision/rise-vision-apps#1078]
### What is the expected behavior?
When using the new subscriptions "Digital Display Plan", widgets should unlock and it should show what plan you are using in the top right

### What is the actual behavior?
Widgets show as locked, and the top right corner says "get more out of rise vision" as if there is no paid subscription.

### What steps can be taken to replicate the problem?
Create a new company and add a "digital display plan" subscription, the website does not behave as if it has a subscription.  These can be seen on these company IDs:

1. A test company I created: 48a80d01-d8d9-4dd6-849f-41965dab31f6
2. Client's company: 9598fdca-0d71-42f1-a750-03d1c026a679

**Comment by tejohnso** [comment]
@tylermwight can you confirm this is still an issue?  I was able to add a presentation with the Mostly Sunny! widget. Might have been a temporary problem while we were rolled back on our deployment.

**Comment by tejohnso** [comment]
@tylermwight we spoke. No longer an issue. Closing.  

@andrecardoso FYI
