### ISSUE TITLE
Apps Pricing Component font does not match Pricing Page

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/rise-vision-apps#1081]
<img width="1005" alt="Screen Shot 2019-06-27 at 11 04 57 AM" src="https://user-images.githubusercontent.com/6218188/60277656-f9e79e80-98cb-11e9-9137-25a904b087c9.png">

From what I can tell the `ProximaNova` font does not exist in Apps.

**Comment by jasoncaldwell** [comment]
@alex-deaconu Let's use Helvetica instead of Proxima Nova in-app. Is that possible? cc @tejohnso

**Comment by tejohnso** [comment]
@alex-deaconu see https://github.com/Rise-Vision/pricing-grid-component/pull/5

**Comment by tejohnso** [comment]
@alex-deaconu As discussed, let's validate the fix after your master merge later today.  cc @jasoncaldwell

**Comment by tejohnso** [comment]
![helv](https://user-images.githubusercontent.com/1511535/60307411-83ba5a80-9912-11e9-9034-afa676c9d50f.png)

Corrected and now confirmed as Helvetica.
