### ISSUE TITLE
Text Component UI shows default text instead of placeholder when empty

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1084]
### What is the expected behavior?
As a User, when I remove text from a text component, exit the component settings, and then re-open it I should see the placeholder text *Enter your text*. 

### What is the actual behavior?
When a text component has been emptied by a user and they re-open it it shows the default text. 

### What steps can be taken to replicate the problem?
View this presentation: https://apps.risevision.com/templates/edit/8e5e054c-f75b-41de-90df-84ba4c1205dd/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

FYI @andrecardoso @olegrise

**Comment by sheadarlison** [comment]
https://www.screencast.com/t/SpLvLNnkvTQ

**Comment by andrecardoso** [comment]
Fixed in https://github.com/Rise-Vision/rise-vision-apps/pull/1095
