### ISSUE TITLE
You can add an HTML Template to an Embedded Presentation item

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1085]
@ezequielc what do you think of this? https://www.screencast.com/t/wNeBbqN9

**Comment by ezequielc** [comment]
@sheadarlison Agreed, Embedded Presentation functionality can't handle HTML Templates so hiding from the list makes sense to me.
@santiagonoguez @fjvallarino fyi. Thanks

**Comment by alex-deaconu** [comment]
@sheadarlison this issue should now be resolved. To confirm, we are filtering out HTML Templates from the Presentations list when selecting an Embedded Presentation. Thanks.
