### ISSUE TITLE
Unable to move files to sub-folders in Rise Storage

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-vision-apps#1086]
**Expected Behavior:**
Users should be able to move images from any folder to any sub-folder in Rise Storage.

**Actual Behavior:**
Users cannot move files from the root storage directory or from folders to sub-folders that are inside folders. They don't show up as an option.

**Steps to reproduce:**
1. Create a sub-folder within a folder in Rise Storage
2. In Rise Storage try to move an image from the root storage directory to the sub-folder. You won't see it as an option

**Comment by sheadarlison** [comment]
@kaden-rise question for you here https://www.screencast.com/t/gT3AVVpE
