### ISSUE TITLE
Parenthesis in Display or Schedule search causes it to fail.

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/rise-vision-apps#1088]
### What is the expected behavior?

Schedules or displays with a () in their name should load. 

### What is the actual behavior?

When searching for either, an error about schedules or displays failing to load appears. It suggests to reload the page, but as soon as you remove the parenthesis it loads correctly. 

### What steps can be taken to replicate the problem?

Search for something like Test(Display) or Test(Schedule) on even just a single ( or ). This doesn't appear to be an issue with presentations.

**Comment by alex-deaconu** [comment]
@colby-maughan this issue should now be fixed. To confirm, it's been fixed for some other lists as well as Displays/Schedules. Thanks.
