### ISSUE TITLE
Plan bar should not say Rise Vision Volume Plan

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1090]
https://www.screencast.com/t/L6Qn5kcUv

Plan bar should only say: 

You have X days on your trial.

**Comment by tejohnso** [comment]
Fixed

![fixed](https://user-images.githubusercontent.com/1511535/61083549-128ea300-a3fa-11e9-8b59-1fd02f2fc625.png)

![fixed-expired](https://user-images.githubusercontent.com/1511535/61083608-3520bc00-a3fa-11e9-874d-15964197597e.png)
