### ISSUE TITLE
Template Editor Storage is missing an empty state

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1098]
**LOW PRIORITY ISSUE**

When you navigate to storage in the template editor and don't have any files you don't see an empty state: https://www.screencast.com/t/zxdbKLpyk

@jasoncaldwell what should this empty state look like?

**Comment by jasoncaldwell** [comment]
@sheadarlison Empty state (for video) should be this:

https://share.goabstract.com/d4e9c62c-13c4-42e1-9634-1347f965d7e5?collectionLayerId=a808f33e-e801-4cd2-b1b1-4158ac682854&mode=design

For the images component, you'd just swap out the word "Videos" for "Images".

**Comment by sheadarlison** [comment]
Thanks @jasoncaldwell 

In your mockups for video, I just realized I think we need an Upload and Add Selected button. You only have one or the other.

**Comment by sheadarlison** [comment]
FYI @santiagonoguez @stulees there will be a minor UI change to video so that the storage section follows the same functionality as image.

**Comment by santiagonoguez** [comment]
@sheadarlison @jasoncaldwell @jasoncaldwell  weird, I see this working for empty directories, and we have code to show this state. Maybe this is an issue on storage root, and as the templates company has lots of files in root already there they are not showing :O let's see

**Comment by fjvallarino** [comment]
@sheadarlison this has been fixed and deployed

**Comment by fjvallarino** [comment]
@sheadarlison I'm closing the issue. Please re open it if needed!
