### ISSUE TITLE
Users cannot edit their subscriptions.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#1105]
**How to recreate**
1. Go to [this company](https://apps.risevision.com/billing?cid=e113f8d6-de1c-4c26-b160-4ef1c4589957)
2. Click edit next to Additional Displays
3. Click edit subscription
4. Change qty from 1 to 2
5. Click Update Subscription

**What happens**
Error message _not allowed in _values_ pops up.

**What should happen?**
Subscription should be updated with current value.

**Additional information**
[Video](https://www.screencast.com/t/j1fdruidt5)

**Comment by tejohnso** [comment]
This was due to legacy plans being archived which required a change to the chargebee portal custom code. 

@btfrise we spoke and tested with your test company - all appears to be well. Closing.
