### ISSUE TITLE
Player does not start when only an HTML Template is added in new company

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-vision-apps#1108]
**What should happen**

A user should be able to add an HTML Template as a single item in a schedule and have it load on a display.

**What currently happens**

Player shows the loading spinner and does not load the Template

**Steps to recreate**

- Set up a new company
- Add a new display
- Add an HTML Template from the library and publish it so it automatically added to the 24/7 schedule
- Player will still show no schedule added until you restart player and it will then only show the spinner.

I tested with HTML Weather and HTML Image and got the spinner. Viewer based Back to School countdown loaded as expected.

I also tried not adding a display until I was prompted to after add the Template but had the same result.

**Comment by tejohnso** [comment]
Fixed with https://github.com/Rise-Vision/rise-vision-apps/pull/1112
