### ISSUE TITLE
Hover on table item indicates clickable row, but is not 

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-vision-apps#111]
Hover on table item indicates clickable row via pointer, but is not until text is selected underneath

![bug2](https://cloud.githubusercontent.com/assets/11826611/13890330/3cf1465e-ed21-11e5-8426-f90effe74317.gif)

**Comment by ezequielc** [comment]
Validated in the cars https://trello.com/c/BQEFEiLQ/1256-issue-111-hover-on-table-item-indicates-clickable-row-but-is-not-1
