### ISSUE TITLE
Display in New Company shows "Missing License..." error

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/rise-vision-apps#1110]
Was testing a new Company scenario. Added a brand new Company with a brand new User:
https://apps.risevision.com/?cid=4e43fb48-4cac-4aaf-935d-a75f5e181558

Company has a 14 day Trial remaining.

Added an HTML Template which was automatically added to a Schedule; added a Display.

Plugged in that Display ID in my local Chrome player. Result was the "Missing License..." error:
<img width="895" alt="Screen Shot 2019-07-17 at 9 50 07 AM" src="https://user-images.githubusercontent.com/6218188/61382777-662a4200-a87b-11e9-8c35-db703aa30e62.png">

I would expect the Display to be allowed to play content as it shows as Licensed in the UI.

**Comment by alexey-rise** [comment]
Fixed in https://github.com/Rise-Vision/core/pull/508
