### ISSUE TITLE
Users with legacy plan subscriptions are able to purchase display licenses using the new licensing system

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-vision-apps#1117]
**Expected Behavior**
Users with legacy plan subscriptions should not be able to purchase additional licenses through the new licensing system. They should be added to their existing plan subscription instead.

**Actual Behavior**
Users with legacy plan subscriptions are able to use the "Get more" link to purchase additional licenses through the new licensing system. This results in a completely new subscription and an extra invoice for the full amount of display licenses.
![image](https://user-images.githubusercontent.com/33877348/61483830-d65bc500-a95a-11e9-89a3-a37e43dc5de2.png)

**Steps to reproduce**
1. In a company with a legacy Plan subscription make sure all of your existing Display licenses are applied to Displays.
2. Create a new Free Display
3. On the Display Settings page for that Free Display a "Get More" link should appear at the top next to "0 Available Licenses"
4. Click the "Get More" link and you'll be able to purchase licenses through the new licensing system

**Comment by alanclayton** [comment]
@tejohnso this behavior isn't right. Pretty sure we decided that if the company is subscribed to a plan they are presented with the portal where they can manage their subscription. @jasoncaldwell let me know if I have this wrong.

**Comment by tejohnso** [comment]
Yes, if they are subscribed they should go to Account & Billing to modify their account. This is part of the reason we removed the plan bar for subscribed customers. This "get more" should open Account & Billing. @jasoncaldwell let me know if you agree.

**Comment by tejohnso** [comment]
@kaden-rise /  @robb-price Can you confirm and close?

**Comment by tejohnso** [comment]
@kaden-rise Looks like you were able to confirm. Closing.
