### ISSUE TITLE
Placeholder with CSS animations inside a Div breaks HTML view

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#112]
I added the below code and some CSS animations to the HTML view of a presentation: 

```
<div style="width:815px;height:900px;left:560px;top:55px;z-index:3;position:absolute;box-shadow: 5px 10px 15px 5px rgba(0,0,0,0.4);overflow:hidden;>
<div id="Image-Slideshow" class="image" placeholder="true" style="width: 815px; height: 900px; z-index: 3; visibility: visible;"></div>
</div>
```

And now I can't access the HTML view any more. 

Presentation:
https://apps.risevision.com/editor/workspace/63f52f47-7990-444b-8e6f-ba27281ba275/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

Preview:
http://preview.risevision.com/?type=presentation&id=63f52f47-7990-444b-8e6f-ba27281ba275&showui=false

![html-view-bug](https://cloud.githubusercontent.com/assets/9273546/13900490/60edd6ba-ede6-11e5-9f1f-4290025749f8.gif)

**Comment by ezequielc** [comment]
@sheadarlison A fix has been released. Could you validate it is working? Thanks!

**Comment by ezequielc** [comment]
Validated in the card https://trello.com/c/pIHTJqBo/1258-issue-112-placeholder-with-css-animations-inside-a-div-breaks-html-view-2
