### ISSUE TITLE
Pricing component does not match style guide

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-vision-apps#1123]
Font sizes, padding, etc.
https://drive.google.com/open?id=1bFaIrhh3fDA_4uRnfESxLJBD0pijjr3vvLRb3mEpZI8

**Comment by ezequielc** [comment]
@tejohnso Is this closed? I don't see it in the defects spreadsheet. Thanks!

**Comment by tejohnso** [comment]
Yes
