### ISSUE TITLE
Issue relating to URL validation for the Google Slides Template Editor Component #1

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1140]
**What should happen:**
- When I enter a valid URL into the URL field of the Google Slides Template Editor Component, but the URL isn't a Google Slides URL, the messaging should say "Please provide a valid Google Slides URL."

**What happens:**
- When I enter a valid URL into the URL field of the Google Slides Template Editor Component, but the URL isn't a Google Slides URL, the messaging says "Invalid URL".

**Steps to replicate:**
https://www.loom.com/share/03a25ce146b844e88aa765ca395c01c5

**Comment by andrecardoso** [comment]
@jasoncaldwell fix deployed to production.
