### ISSUE TITLE
Issue relating to URL validation for the Google Slides Template Editor Component #2

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1141]
**What should happen:**
When I enter in gibberish into the URL field of the Google Slides Template Editor Component, the app should say "Please provide a valid URL."

**What happens:**
When I enter in gibberish into the URL field of the Google Slides Template Editor Component, the app tries to insert/format that gibberish into a URL.

**Steps to replicate:**
https://www.loom.com/share/6f46bb7cd9af41d4b86908e53b7abcd9

**Comment by andrecardoso** [comment]
@jasoncaldwell this is a side effect of accepting the presentation id as input. We can't differentiate an ID from any other word, so we build a Google Slides URL with whatever word the user types in.

**Comment by andrecardoso** [comment]
@sheadarlison can you confirm this is not a defect?

**Comment by sheadarlison** [comment]
@andrecardoso could it just show the gibberish and not a URL until it can confirm it is valid and then change it to the URL?

**Comment by alanclayton** [comment]
@jasoncaldwell @sheadarlison given this is cosmetic, and we are behind schedule, my preference is not to pursue and close this. Let me know if that is okay with you. @andrecardoso FYI.

**Comment by andrecardoso** [comment]
@sheadarlison we could do that, but I agree with @alanclayton regarding not pursuing it now. I'll close it and we can reopen if necessary. Thanks.
