### ISSUE TITLE
Images added to the Full Screen Image Template do not loop

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#1156]
### What is the expected behavior?
All images that you add to the Presentation should loop through. For greater clarification: when it reaches the last image, it should cycle back to the first.

### What is the actual behavior?
Once it reaches the last image, it sits on that one and does not move forward.

### What steps can be taken to replicate the problem?
Add several images to a copy of the Full Screen Image Presentation template.

**Comment by pcsandford** [comment]
@ezequielc @robb-price this sounds like it would be an issue with the Template - I can take it and investigate if you agree, thanks!
