### ISSUE TITLE
[Image Component] Primary Secondary Buttons

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1159]
**Defect:** When editing a template with an Image Component, both buttons here need to be secondary buttons (green outline with white background):

![image1](https://user-images.githubusercontent.com/1440943/62785740-df861080-ba86-11e9-9d60-4f516912b683.jpg)

**Comment by willread** [comment]
@jasoncaldwell This issue has been addressed by [this pull request](https://github.com/Rise-Vision/rise-vision-apps/pull/1172) and should be good to go!

**Comment by jasoncaldwell** [comment]
@willread 👍
