### ISSUE TITLE
[Image Component] [Rise Storage] Text labels for Rise Storage folders

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1162]
**Defect:** text label size for folders in Rise Storage needs to be 12px and have a color value of #999:

![image28](https://user-images.githubusercontent.com/1440943/62786710-c67e5f00-ba88-11e9-9689-ac533372cf24.jpg)

**Comment by willread** [comment]
@jasoncaldwell Fixed with [this PR](https://github.com/Rise-Vision/rise-vision-apps/pull/1191). Pleased validate and let me know when I can close this.

**Comment by jasoncaldwell** [comment]
@willread Looks good!
