### ISSUE TITLE
[Image Component] Font size and color of text in the empty state #2

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1164]
**Defect:** When there are no images in the Image Component, the font size for this text here should be 12px and have a color value of #020620:

![image13](https://user-images.githubusercontent.com/1440943/62787080-88ce0600-ba89-11e9-8348-25121a710046.jpg)

**Comment by santiagonoguez** [comment]
@jasoncaldwell I've just fixed this, please validate:

https://apps.risevision.com/templates/edit/0ada0513-d383-4578-b30c-fc9505b8e636/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

( the screeny width is still a question I put in the Style guide )

**Comment by jasoncaldwell** [comment]
@santiagonoguez 👍 Looks good.
