### ISSUE TITLE
[Image Component] [Rise Storage] Font size and color of text in the empty state #1

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1165]
**Defect:** When there are no images in Rise Storage, the font size for this text here should be 14px and have a color value of #020620:

![image24](https://user-images.githubusercontent.com/1440943/62787268-f7ab5f00-ba89-11e9-8166-57a200270e5c.jpg)

**Comment by santiagonoguez** [comment]
@jasoncaldwell I've just fixed this, please validate:

https://apps.risevision.com/templates/edit/0ada0513-d383-4578-b30c-fc9505b8e636/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

there's an 'empty' folder where you can test

**Comment by jasoncaldwell** [comment]
@santiagonoguez 👍 Looks good, although the text here needs to be bold:

![Rise_Vision___Apps](https://user-images.githubusercontent.com/1440943/63032025-a7ae0d00-be7a-11e9-8194-f5ef0ea8723f.png)

Thanks!

**Comment by santiagonoguez** [comment]
@jasoncaldwell it's now bold, thanks !
