### ISSUE TITLE
[Image Component] [Rise Storage] Font size and color of text in the empty state #2

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1166]
**Defect:** When there are no images in Rise Storage, the font size for this text here should be 12px and have a color value of #020620:

![image27](https://user-images.githubusercontent.com/1440943/62787366-2cb7b180-ba8a-11e9-9bc7-eb447429d50c.jpg)

**Comment by santiagonoguez** [comment]
@jasoncaldwell I've just fixed this, please validate:

https://apps.risevision.com/templates/edit/0ada0513-d383-4578-b30c-fc9505b8e636/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

there's an 'empty' folder where you can test

**Comment by jasoncaldwell** [comment]
@santiagonoguez 👍 Looks good!
