### ISSUE TITLE
[Image Component] [Rise Storage] Buttons when there are no images in Rise Storage

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1167]
**Defect:** When there isn’t any content in Rise Storage, the “Add Selected” button shouldn’t be visible:

![image26](https://user-images.githubusercontent.com/1440943/62787523-80c29600-ba8a-11e9-8961-a97b0abe57e9.jpg)

**Comment by santiagonoguez** [comment]
@jasoncaldwell this has been fixed [here](https://github.com/Rise-Vision/rise-vision-apps/pull/1195).

You can validate it working in any presentation, such as these:

https://apps.risevision.com/templates/edit/b5df98d6-b534-4d62-99f1-b899dde2949d/?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

Please confirm we can close this. thanks !

**Comment by jasoncaldwell** [comment]
@santiagonoguez Looks good!
