### ISSUE TITLE
Play until Done In-App Requirement Missed

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1174]
**How it Currently Works** 
When a user schedules a template that is Play until Done they need to check the PUD box. 

**How it Should Work** 
When a user schedules an HTML Template that is NOT Play until Done, we do not show the PUD checkbox in schedules. 

When a user schedules an HTML Template that is Play until Done, the PUD checkbox is checked by default but a user can uncheck it and override PUD with a duration.

FYI @andrecardoso @olegrise defect opened for this missed requirement https://trello.com/c/TMN4Wsta/154-3-discuss-apps-changes-to-support-template-pud

Thanks

**Comment by olegrise** [comment]
Issue is fixed. 
@sheadarlison FYI.
