### ISSUE TITLE
Schedule and Add a Display Modals aren't showing up in the Template Editor and Editor

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1176]
[See thread here.](https://rise-vision-inc.slack.com/archives/CCDCUDRJQ/p1565645828357400)

**Comment by alex-deaconu** [comment]
@sheadarlison this issue should now be resolved. Validated both by manual testing and via the Apps e2e tests. Closing. Thanks!

**Comment by sheadarlison** [comment]
@alex-deaconu 👍
