### ISSUE TITLE
Schedule is claiming it cannot be saved, but saves anyways

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/rise-vision-apps#1179]
### What is the expected behavior?

If a schedule cannot save, it will show an error stating that is the case. If it can save, it will not show the error. 

### What is the actual behavior?

Currently, it can save, and is showing the error regardless of the save being successful or not. This only happens on a couple accounts that we know of.

### What steps can be taken to replicate the problem?

I have unfortunately not been able to replicate the issue on any schedules of my own, but it has happened to two accounts that we know of now. One has been resolved, but I will link the other on the Trello card for this issue.

**Comment by alex-deaconu** [comment]
@colby-maughan to confirm, this issue should now be resolved. I've saved the schedule you linked and it worked as expected. Thanks.
