### ISSUE TITLE
[RSS Component] Help Text

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1203]
Defect: The help text here:

![Rise_Vision___Apps](https://user-images.githubusercontent.com/1440943/63383396-4dbdb380-c362-11e9-8ee8-bb0791a80ebd.png)

Needs to be massaged a bit. Maybe it should say "Provide a valid RSS URL."

**Comment by fjvallarino** [comment]
@jasoncaldwell this issue was closed automatically by GitHub since I used the word _fixes_ next to the issue number. I'm not sure I really like this GitHub feature...

In any case, please re open if needed! The text was updated as suggested. Thanks!
