### ISSUE TITLE
Image in storage is deleted and replaced by an image of the same name it does not update to the new image.

### ISSUE THREAD

**Issue by RowanDarlison** [Rise-Vision/rise-vision-apps#1209]
### What is the expected behavior?
The image will update with the new image of the same name.
### What is the actual behavior?
The image is the original deleted image.
### What steps can be taken to replicate the problem?

Add an image to a presentation, delete it from storage, add a new image of the same name.

**Comment by santiagonoguez** [comment]
@RowanDarlison does this happen on regular presentations, HTML presentations, or both ? can you clarify if the old image still appears in thumbnails, storage, preview or display ? Thanks !

**Comment by RowanDarlison** [comment]
@santiagonoguez It is on both types of presentations and the old image still appears in the presentation however everywhere else it is the updated image.

**Comment by santiagonoguez** [comment]
This was corrected las week for HTML template editor, but the problem still happens in presentation editor.

**Comment by ezequielc** [comment]
@santiagonoguez I investigated this today for Presentations Editor and the issue seems to be on Image Widget side. Editor doesn't hold any information about the file, it only initiates the widget, which would be responsible for checking that.
Given we are transitioning to Image Component, I am not sure if it is worth investing time on Image Widget at this point. Thoughts?
@sheadarlison fyi

**Comment by santiagonoguez** [comment]
@ezequielc Also, this is an uncommon case, so uncommon that it took this long to be reported. So I'm also not sure if it's worth pursuing. @sheadarlison thoughts ?

**Comment by sheadarlison** [comment]
@santiagonoguez @ezequielc does it impact displays or only the editor?

**Comment by santiagonoguez** [comment]
@sheadarlison it does not impact displays, just presentation editor

**Comment by sheadarlison** [comment]
@santiagonoguez @ezequielc yeah lets close this. Not a priority. Thanks

**Comment by santiagonoguez** [comment]
@stulees FYI ^
