### ISSUE TITLE
Video Issue - Modal isn't centered on mobile

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1216]
[Modal isn’t centered on mobile. ](https://photos.google.com/share/AF1QipNqPdWk253Rj1p4lz_JB1jHIrH-kh1sfzMlzgW3OaVg1Hn3vidmo1jsGp9N58JbDQ/photo/AF1QipOkPvSPWL7NLBlJRBq_mTUwn8PzCFv4qBzGhJj_?key=RzVhOVpDZjFYMUlqNWtXRGlJS1dQQzliUUVmOVpR)

**Comment by willread** [comment]
@sheadarlison I pushed a fix for this, please validate.

**Comment by sheadarlison** [comment]
Looks good!
