### ISSUE TITLE
Inconsistent Sign Up Data

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1235]
**Problem:** 
Marketing can’t accurately track new sign ups or user invites in HubSpot. 

BigQuery and HubSpot data are inconsistent and we don’t know which is accurate. 

**Outcome:** 
As Marketing, I can accurately track in HubSpot the number of people that:
 
- Have signed up for a new account. 
- Have accepted an invitation to join an existing account. 

As Marketing, I have queries that tell me the number of people that: 

- Have signed up for a new account. 
- Have accepted an invitation to join an existing account. 

And the data between BigQuery and HubSpot is exactly the same 99% of the time.

FYI @jasoncaldwell

**Comment by alanclayton** [comment]
@tejohnso I wonder if part of the problem described here is a result of [531](https://github.com/Rise-Vision/core/issues/531).  Thoughts?

**Comment by tejohnso** [comment]
@alanclayton @sheadarlison It does sound like [531](https://github.com/Rise-Vision/core/issues/531) is related because we're seeing failures in the Hubspot sync from BQ. I'm not sure about the details on tracking signups or invitations, but I can say for sure that Hubspot isn't getting everything exactly as expected from BQ right now.

**Comment by alanclayton** [comment]
@sheadarlison @jasoncaldwell given this I would suggest using data from big query for now until that defect is corrected. Let me know if you agree. And if you do, are you good closing this one and tracking 531 for the discrepancy you are seeing?

**Comment by sheadarlison** [comment]
@alanclayton That's fine with me. I've updated 531 to include this problem and outcome required.

Thanks
