### ISSUE TITLE
[Branding Component] Modal Buttons in wrong order

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1248]
**Defect:** The button order here:

![Rise_Vision___Apps](https://user-images.githubusercontent.com/1440943/64202816-a491b580-ce57-11e9-9979-0b793caee285.png)

needs to be reversed. Eg., "No, Keep It" needs to go on the right and "Yes, Remove It" needs to go on the left.

**Comment by ezequielc** [comment]
@jasoncaldwell I used the above order to be consistent with Delete Presentation modal.
If we change it for Logo Remove modal, I think we should also change it for Delete Presentation. 
Or we should keep both as it. Thoughts? Thanks!

<img width="633" alt="Screen Shot 2019-09-03 at 4 46 31 PM" src="https://user-images.githubusercontent.com/7738553/64203692-6c47a280-ce6a-11e9-92f5-f68c100dc6a0.png">

**Comment by jasoncaldwell** [comment]
@ezequielc So, I think the "Are you sure ..." modal button order needs to be changed as well. The buttons should be (left to right): 

[Red Button] "Yes, Delete"
[Green Button] "No, Don't Delete"

**Comment by ezequielc** [comment]
@jasoncaldwell Sounds good. Thanks!

**Comment by alex-deaconu** [comment]
This issue should now be resolved. The buttons have been swapped for the two modals. Thanks.
