### ISSUE TITLE
User settings modal save button appears to ignore click

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-vision-apps#1257]
When the user settings modal is not valid, and the save button is clicked, the ui gives no indication that something is wrong. It appears to ignore the click. 

To reproduce, try to edit *<removed - [check card](https://trello.com/c/m4W46RAx/5332-issue-1257-user-settings-modal-save-button-appears-to-ignore-click-1)>* from *<removed - [check card](https://trello.com/c/m4W46RAx/5332-issue-1257-user-settings-modal-save-button-appears-to-ignore-click-1)>*. Open the user settings modal for that user, change the email address to `.ca` instead of `.com` and click save. Instead of saving, the click appears to be ignored. Possibly due to form not being valid because the last name field is empty.

**Comment by ezequielc** [comment]
@tejohnso A fix was released, let me know if you still see the problem. Thanks
