### ISSUE TITLE
Glitchy Famous Artists Template

### ISSUE THREAD

**Issue by jrkuchta** [Rise-Vision/rise-vision-apps#1284]
### What is the expected behavior?
- Template loads and displays the images and text as designed.

### What is the actual behavior?
- The template loads as a blank white page with only the text Famous Artists appearing

### What steps can be taken to replicate the problem?
- Schedule and run the template on a display

**Comment by alanclayton** [comment]
@jrkuchta what template? What type of display (player)? 

@mmeiers @pcsandford

**Comment by pcsandford** [comment]
@alanclayton it is the Famous Artists Template (editor based) and we have it running on Chrome and Windows players without issue at the moment. I saw that at times it would fail to load in preview but couldn't narrow it down so @andrecardoso is checking if there is anything that needs to be addressed on our end. Thanks!

**Comment by pcsandford** [comment]
@jrkuchta as Andre was not able to find anything in his investigation we are not going to look into this further unless we hear other reports or can replicate it on our players. 

Instead, we are working on converting all of the auto updating Templates to HTML with branding and have set a target date of 10/18/2019 for this to be completed. We have set the defect close date to the same day as at that point if anyone has any issues we will direct them to use the new Templates. 

I will let you know when this is released so you can let the user know. 

Thanks!

**Comment by ezequielc** [comment]
@pcsandford Should we close this? Thanks

**Comment by pcsandford** [comment]
@ezequielc sorry, yes, we have released the HTML version so this can close. @jrkuchta can you follow up with the user who originally reported this to show them our new auto updating Templates with branding etc. Thanks!
