### ISSUE TITLE
Text Widget opens very slowly in some cases

### ISSUE THREAD

**Issue by tylermwight** [Rise-Vision/rise-vision-apps#1309]
### What is the expected behavior?
When opening the text widget it takes less than a few seconds to open

### What is the actual behavior?
For some users it is taking over 1 minute after clicking on the text widget for it to open and be able to be edited. We have full video of this while the dev console is open which is included in the card. It takes a very long time to open and does so every time.

### What steps can be taken to replicate the problem?
Unsure, it could be CDN related as this is reported in New Zealand

**Comment by stulees** [comment]
Closing based on positive client feedback from our improvement that reduced the size of _settings.js_ file.  @kaden-rise
