### ISSUE TITLE
Contacts are being erroneously created in HubSpot

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1314]
[Problem is documented here.](https://docs.google.com/document/d/1h0UQtZljBXsVlRVZXisPBTH84h_c1jyMUw0uudyGT4U/edit#bookmark=id.b86q1jbozuus)

**Comment by tejohnso** [comment]
@sheadarlison my responses are in the doc. Going forward we'll have a much clearer picture of how records ended up in the system. Some of the records in the past are hard to explain.
