### ISSUE TITLE
store.risevision.com is accessible if you're not logged in

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1315]
### What is the expected behavior?
Store redirects to our new pricing

### What is the actual behavior?
If you're not logged in, you can view Store and see our old plans, as well as some old per-feature pricing.  You can get as far as adding an item to cart before being asked to log in.  

If you log in from an account without a subscription, you get the company info modal over Store, but are then immediately redirected to the Subscribe to Rise Vision modal with the correct pricing.

### What steps can be taken to replicate the problem?
Open store.risevision.com in a new Incognito window.

**Comment by alex-deaconu** [comment]
The redirect was not being applied correctly when the User was not logged in. Updated and now they will be redirected to the sign up page for Apps. Thanks.
