### ISSUE TITLE
Reactivating a Subscription in Chargebee will enforce Simple Licensing to all Displays in Company.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#1316]
### What is the expected behavior?
When a subscription for a Company that was created before the effective date is cancelled, it can be reactivated in Chargebee, and pick up exactly where it left off, no changes to any Displays.

### What is the actual behavior?
After the Subscription is reactivated in Chargebee, it applies Simple Licensing to all Displays in the Company.

### What steps can be taken to replicate the problem?
1. Using a Company that has Licensed Displays in a plan, as well as other free Displays, cancel a subscription that was created before the effective date.

2. Reactivate the subscription in Chargebee.

3. Notice that the Licensed Displays work as expected, but the Free Displays now show the Missing License error.
--

**Comment by alexey-rise** [comment]
Fixed in https://github.com/Rise-Vision/core/pull/573
