### ISSUE TITLE
Schedules Do not Save Changes in Staging Environment

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/rise-vision-apps#1320]
Expected Behavior
If I remove or add templates to a schedule I expect it to update my player set up in the same staging environment with saved changes.

Actual Behavior
When I remove or add templates to a schedule the display continues to show the originally saved template list.

Steps to replicate
Add a beta display, then add a schedule and assign it to that display in a staging environment.
Add templates and save. Then add more templates and save. The templates that were added after the initial save will not be pushed to the display.

**Comment by andrecardoso** [comment]
hey @mmeiers could you please clarify how did you get player configured to staging?

**Comment by santiagonoguez** [comment]
@andrecardoso they are using this branch - https://github.com/Rise-Vision/rise-player-electron/compare/staging/player-beta-point-to-template-staging?expand=1

**Comment by andrecardoso** [comment]
@santiagonoguez Thanks. @mmeiers closing this as discussed. We are going to fix it as part of our current epic.

**Comment by mmeiers** [comment]
@andrecardoso Sounds good I assume Santiagos clarification was what you needed but msg me if you have any questions.
