### ISSUE TITLE
Can't add HTML templates in apps-beta

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1331]
### What is the expected behavior?
Can add a presentation from a template by clicking 'Add Presentation' under Presentations and picking any Template.

### What is the actual behavior?
In apps-beta, HTML templates like Image Full Screen return an error.
![image](https://user-images.githubusercontent.com/40774237/67704938-ceb5ae80-f994-11e9-8a05-03e611496092.png)

### What steps can be taken to replicate the problem?
- Log in to apps-beta.risevision.com
- Click "presentations"
- Click "add presentation"
- Pick the Image Full Screen template

**Comment by santiagonoguez** [comment]
I need to sync all templates to staging just as I did with beta before to solve this.

**Comment by santiagonoguez** [comment]
@PatrickA-RiseVision this is fixed now, apps beta now has access to all HTML templates. Thanks !
