### ISSUE TITLE
Exposed Google OAuth Key

### ISSUE THREAD

**Issue by kastentx** [Rise-Vision/rise-vision-apps#1336]
Potential security breach. See /web/scripts/components/userstate/services/svc-external-logging.js

**Comment by tejohnso** [comment]
Thanks.
This is restricted in scope, but needs to be addressed in any case.

**Comment by tejohnso** [comment]
Closing per [discussion](https://docs.google.com/document/d/16LMfeVD6lSrFhpShuc4vqzvRZyNEf5NwSdpDfxru7Ag/edit)
