### ISSUE TITLE
Templates with PUD selected in Schedule do not finish animations

### ISSUE THREAD

**Issue by jrkuchta** [Rise-Vision/rise-vision-apps#1358]
### What is the expected behavior?

When a template is scheduled and PUD is selected in the Playlist Item settings, the template will run through the entire animation.

### What is the actual behavior?### 

The Social Media and Scrolling Ticker templates are only running for about 5 seconds and moving on to the next item on the playlist.  They are not finishing the animation or showing the full scrolling text input by the user.

What steps can be taken to replicate the problem?
-- Add the Social Media or Scrolling Ticker template as a playlist item on the schedule.

CID: https://apps.risevision.com/schedules/details/9686339f-5afc-4335-bca3-ced6d37ba145?cid=65df3085-4294-4907-bfde-831ebdcd4338

Presentations: MDSA Athletics Social Media & Athletics Schedule (Scrolling)

**Comment by tejohnso** [comment]
Closing per [discussion](https://rise-vision-inc.slack.com/archives/CD10S3YTT/p1573652743058300)
