### ISSUE TITLE
Odd behavior in-app if you're a system administrator with no permissions

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1364]
### What is the expected behavior?
System Administrator can make changes to all parts of their Rise Vision account.
If a System Administrator cannot perform a task, an error is shown to explain it and direct them to a solution.

### What is the actual behavior?
A System Administrator has read-only access to all parts of the app.  In most cases there is either no error, or the error is unclear.  

### What steps can be taken to replicate the problem?
- Create a test account.
- Create a presentation, schedule, and Display
- Remove all permissions except for System Administrator from yourself
- Try to make changes to Presentations, Schedules, and Displays.  The behavior is inconsistent and the cause is not clear.

Here's a quick video overview:
https://drive.google.com/a/risevision.com/file/d/1v1RMmZ29Suaobx4G7Vng23iWgldOsVPe/view?usp=drivesdk

**Comment by ezequielc** [comment]
@PatrickA-RiseVision As discussed in the [card](https://trello.com/c/ZIkR6G2T/5587-issue-1364-odd-behavior-in-app-if-youre-a-system-administrator-with-no-permissions-3), we disabled Display Licensing toggle and removed template autosave when user doesn't have the required role. Thanks
