### ISSUE TITLE
Inconsistent password requirements

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-vision-apps#1372]
If you visit https://apps.risevision.com/unauthorized and attempt to login with email/password, the password field shows password requirements which I don't think should apply in this scenario since I'm already a user that has already defined my password. 

![image](https://user-images.githubusercontent.com/6854911/69266293-8141f100-0b90-11ea-8e0e-f2de2672c6ee.png)

**Comment by ezequielc** [comment]
@alanclayton The new password requirement is 12 characters. Previously we had a requirement of 4 characters, so when entering an existing password the user is expected to provide at least 4 characters as per message above.
Are you suggesting to remove the validation entirely and not show any validation when entering an existing password? 
Thanks!

**Comment by alanclayton** [comment]
@ezequielc Yes, I don't understand the purpose of the saying the password needs to be 4 or more characters in this scenario. I think the only message that should be shown is if the password provided is incorrect. Thanks

**Comment by ezequielc** [comment]
@alanclayton Sounds good. I will remove this validation. Thanks

**Comment by ezequielc** [comment]
@alanclayton Minimum length validation has been removed.
Just a heads up, I still left the empty field message 'Oops, don't leave this blank'.
Let me know if that is ok. Thanks!
