### ISSUE TITLE
Template Library Template CTA Does Not Work As Expected

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1373]
https://www.screencast.com/t/XH65u2qJE

**Comment by alex-deaconu** [comment]
@sheadarlison great catch!

It should now be resolved. To confirm, this is related to the Chargebee latency issues we've been observing when starting trials. We have implemented a workaround in Apps for that, however the fix was missed for this particular use case.

Closing. Thanks!
