### ISSUE TITLE
Billing email addresses are not always being added to Chargebee accounts when the account is created through trial

### ISSUE THREAD

**Issue by jrkuchta** [Rise-Vision/rise-vision-apps#1376]
### What is the expected behavior?

When a new user creates an account with Rise Vision, a trial is created in Chargebee and all necessary information is added, including the email address for billing notifications.

### What is the actual behavior?

Some accounts are being created in Chargebee without an email address, which means they are not receiving invoices or billing notifications. 

### What steps can be taken to replicate the problem?

Unsure.  Vario Systems, MC2, and LaFrance are all recent additions to Chargebee and do not have email addresses.

**Comment by ezequielc** [comment]
@jrkuchta This issue has been fixed. New customers now have associated billing contact and we also ran a job to update some subscribers that were missing the billing contact. Thanks!

**Comment by ezequielc** [comment]
Given we still have actions related to missed billing contacts, I am reopening this defect until all actions are finalized. Thanks!

**Comment by ezequielc** [comment]
As discussed, we are generating log entries when we detect companies missing billing contact and CS defined a weekly process to manually correct them. Closing the defect. Thanks!
