### ISSUE TITLE
Add Display button not selectable when tabbing with keyboard

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-vision-apps#1377]
*What should happen*

A user with a keyboard should be able to navigate the website by selecting buttons etc. without a mouse.

*What currently happens*

All elements and links are selectable on the displays page, except for the Add Display button.

*Steps to recreate*

Open the display page and mash the tab button a bunch of times.

**Comment by alex-deaconu** [comment]
@pcsandford good find, issue should now be resolved. Thanks!
