### ISSUE TITLE
Add a Display Modal for Raspberry Pi Should Say Raspbian Buster...

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1385]
... not Raspbian 8.0 (ARMv7)

https://www.screencast.com/t/q0CkB2c1j5

**Comment by alanclayton** [comment]
@sheadarlison I think we should eliminate this maintenance and not state the specific OS. Instead, add the text, "What operating system versions are supported" that links to the respective article.

**Comment by sheadarlison** [comment]
Good point. Lets just leave it as "Download for Raspberry Pi"

**Comment by alex-deaconu** [comment]
@sheadarlison this has been updated to say
> Download for Raspberry Pi
as suggested. Closing. Thanks!
