### ISSUE TITLE
Empty placeholder with background color does not respect scheduling.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#139]
**How to replicate**
1. Create a new presentation
2. Create a placeholder
3. Do not assign any content to that placeholder, assign a black background to it, schedule it to display only during a certain time (Ex. 01:00PM - 01:45PM).
4. Assign this presentation to a schedule, and that schedule to a display.

**What happens**
After 01:45PM, the placeholder is still visible.

**What should happen**
The empty placeholder should respect scheduling.

**Notes**
Demo presentation [here](http://preview.risevision.com/?type=presentation&id=92b1f1f2-f833-467c-9b48-afdf84a27c48)

This was test in both Editor and Classic editor, with the same result.

**Comment by ByronDarlison** [comment]
@alex-deaconu @ezequielc is this an apps defect or a viewer defect? Thanks

**Comment by alex-deaconu** [comment]
@ByronDarlison this behaviour is controlled by the viewer, hence a viewer defect. Thanks.

**Comment by ByronDarlison** [comment]
@alex-deaconu I thought so. @btfrise can you move this to the viewer repo. Thanks

**Comment by btfrise** [comment]
Moved to correct repo, sorry about that!

https://github.com/Rise-Vision/viewer/issues/92

**Comment by alex-deaconu** [comment]
@ByronDarlison @btfrise thanks!
