### ISSUE TITLE
Embedded Presentation & HTML Templates

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1390]
https://www.screencast.com/t/nugBwxle

Check if the ID is valid, if it is an HTML Template ID show the message: 

Templates cannot be embedded. Please enter a Presentation ID.

**Comment by ezequielc** [comment]
As discussed in https://trello.com/c/NpIvNeM7/5635-issue-1390-embedded-presentation-html-templates-viewer-change-8, we are good with Apps changes. Closing the defect. Thanks
