### ISSUE TITLE
[Count Up/Down Component] White space issue

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1403]
Issue details:
In the Template Editor, when editing a Template with a Count Up/Down Component, there needs to be 5 more pixels separating the time input and the "A specific time ..." radio option.

![Rise_Vision___Apps](https://user-images.githubusercontent.com/1440943/70569551-28022780-1b68-11ea-9b33-3b54a0eb212d.png)

**Comment by stulees** [comment]
This has been fixed with #1407
