### ISSUE TITLE
Browser Upgrade shouldn't be visible to users on Electron player

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1408]
https://www.screencast.com/t/B7s67mkzP

**Comment by alex-deaconu** [comment]
@sheadarlison this field is deprecated. To confirm, that dropdown will only show if a User has previously set this to "User Managed" and it will disappear if they change it back to "Auto Update". Basically, this should never show except for really old Displays that had that setting configured. My advice is to just remove this field from the page. I believe it was specific to v1/v2 players. Thoughts? Thanks.

**Comment by sheadarlison** [comment]
@alex-deaconu Agreed with removing it completely. Thanks

**Comment by alex-deaconu** [comment]
@sheadarlison the field is now removed. I've also double checked that this field is not used in Player code anymore. Thanks.

**Comment by sheadarlison** [comment]
Thanks @alex-deaconu
