### ISSUE TITLE
If a user only has the "Content Publisher" role, they cannot publish to Displays in the Presentation Editor

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#1412]
### What is the expected behavior?
User's with the Content Publisher Role should be able to Publish Presentations to Displays.

### What is the actual behavior?
In order to publish a Template Presentation to Display, you need both Publisher and Editor roles.

### What steps can be taken to replicate the problem?
1.Create a user with a Content Publisher Role only.
2. Add a new Presentation, and attempt to click the Publish to Display Button. Notice it says you do not have the rights.
![Error](https://user-images.githubusercontent.com/6862256/71103936-fd782600-2188-11ea-9c70-3ff39f139c81.jpg)

**Comment by ezequielc** [comment]
@robb-price I don't think we have an issue here. The message says they don't have permission to 'Edit'.  'Publish To Display' button is enabled and should work as expected. Let me know if it clarifies. Thanks

**Comment by robb-price** [comment]
@ezequielc When you create the Presentation for the first time, The Publish to Display is not enabled.

**Comment by ezequielc** [comment]
@robb-price When they open a new Presentation for the first time, they can't create/save that Presentation as they don't have Content Editor role. So, as the Presentation was not created, they can't Publish it as well.

I agree it is not very intuitive, but the entire App is not very intuitive when some roles are missing. Let me know if you have suggestions or if we can close the issue. Thanks

**Comment by robb-price** [comment]
@ezequielc Since this has only happened once, I agree we can close this for now. If we get more users reporting similar confusion, I think we need to revisit it, and come up with a correction.
