### ISSUE TITLE
Remove Settings and Network From RVA 

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1419]
Remove the settings and network link from the RVA header.

**Comment by alex-deaconu** [comment]
@sheadarlison to confirm, the Settings and Network links have now been removed from the RVA. 

Just as a quick note, if anyone does want to modify either pages (internally or an end user) we can provide a URL for them to access that page. Only the links were removed the pages themselves were not.

Thanks!

**Comment by sheadarlison** [comment]
Thanks @alex-deaconu
