### ISSUE TITLE
Error when trying to submit tax exemption during checkout process

### ISSUE THREAD

**Issue by jrkuchta** [Rise-Vision/rise-vision-apps#1465]
### What is the expected behavior?

When attempting to subscribe and using the checkout process, I should be able to add tax exempt information, select the "Submit Tax Exemption" button and continue the checkout process.

### What is the actual behavior?

During the checkout process, in the Add Tax Exemption window, when I select the "Submit Tax Exemption" button, an error occurs and I am blocked from continuing. The error is: "An error occurred while submitting your tax exemption. Please try again."

![image](https://user-images.githubusercontent.com/23563598/72165618-6bc99600-338d-11ea-8323-bd8cda870716.png)

### What steps can be taken to replicate the problem?

Attempt to add a subscription in app, and add a tax exemption.

**Comment by tejohnso** [comment]
@jrkuchta This is corrected now.

**Comment by tejohnso** [comment]
Corrected via https://github.com/Rise-Vision/store-server/pull/1088
