### ISSUE TITLE
After going through the checkout process the billing page shows no subscriptions until you refresh

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1472]
**How it should work**
Upon completing the checkout process the billing page should show your updated information.

**Comment by alex-deaconu** [comment]
@sheadarlison we have deployed a potential fix for this issue.

To confirm, when on the Billing page, and the User purchases a Subscription, after they complete the Purchase and close the modal (the modal closes with a 10 second delay), the Billing Page will update the Subscriptions list.

From our testing this will show the new Subscription in the list.

However, there could be instances where the Purchase itself, Chargebee webhook calls and other delays cause the Subscription to not be present within the 10 seconds we allocate for this. That generally should not happen, especially in Production, but in that case a Page refresh would be required. Let us know if you think this would be an issue (or this is what you actually experienced when logging this).

Also, as a bonus, we're hiding the View Old Invoices link if the company was created after September 2018, something described in the Purchasing Improvements Epic.

Thanks!
