### ISSUE TITLE
Assigning specific Displays in Placeholder distribution is removed when you switch between HTML and Design view

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#1483]
### What is the expected behavior?
Any changes you make to Placeholder Distribution in Design View should be saved when you press Save in HTML view.

### What is the actual behavior?
Changes you make to Placeholder Distribution in Design View are disregarded when you press Save in HTML view.

### What steps can be taken to replicate the problem?
1. In Design view, Set the distribution of a Placeholder to a specific Display.
2. Switch over to the HTML view, click SAVE, and switch back to the Design view. 
3. Notice the single Display is gone from the Distribution, and it now shows 'No Display Assigned'.

Darius brought this up in this Community conversation: https://help.risevision.com/hc/en-us/community/posts/360056411732-I-think-there-is-a-bug-to-report-1

**Comment by alex-deaconu** [comment]
@robb-price this issue has been resolved. Thanks!
