### ISSUE TITLE
Completing onboarding step 1 adds a template to the schedule with duration of 10s

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1494]
### What is the expected behavior?
The default behavior for templates that support PUD is to enable PUD.

### What is the actual behavior?
When completing onboarding step 1, the template you choose is added to the schedule with a duration of 10s regardless of PUD support.

### What steps can be taken to replicate the problem?
- Create a new Rise Vision account
- Complete Step 1: Pick a Template
- Check your All Displays 24/7 Schedule

Here's a video: https://drive.google.com/a/risevision.com/file/d/1jkx8oXisQxNYd5SJ8SDESgeuuOv-kHvd/view?usp=drivesdk

**Comment by PatrickA-RiseVision** [comment]
See also https://github.com/Rise-Vision/rise-launcher-electron/issues/837

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision to confirm, a fix for this issue has been deployed.

We are now checking if the Template is PlayUntilDone and setting the flag accordingly on automatic Schedule creation.

Closing. Thanks!
