### ISSUE TITLE
Add button in Edit Subscription window does not work

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#1509]
### What is the expected behavior?
You should be able to press the add and subtract button when changing the amount of licenses you want to purchase.

### What is the actual behavior?
The Add Button is not working.

### What steps can be taken to replicate the problem?
Log int https://apps.risevision.com go to the Account and Billing page, click Edit on your subscription, and then try to press the Add button. Notice that it has no effect.

This video shows the bug in action: https://drive.google.com/a/risevision.com/file/d/1rZR2WJ-sQrAAhA2HtMEnkoFUhMkl5m-o/view?usp=drivesdk

Chargebee has been notified, and are investigating.

**Comment by ezequielc** [comment]
@sheadarlison I believe you requested Chargebee to change this selector recently. Would you be able to reach them to take a look at this? Let me know in case you want me to pursue it. Thanks

**Comment by sheadarlison** [comment]
@ezequielc Robb and myself have reached out, we're waiting to hear back from Chargebee with the resolution.

**Comment by ezequielc** [comment]
@sheadarlison Awesome. Thanks!

**Comment by brianloosbrock** [comment]
@sheadarlison @robb-price Did you guys receive an update from Chargebee today? Thanks

**Comment by sheadarlison** [comment]
@brianloosbrock haven't heard back since Thursday, I followed up this morning and cc'd Amrutha
