### ISSUE TITLE
When adding multiple items to a Schedule Playlist, Image Fullscreen template defaults to 10s

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1512]
### What is the expected behavior?
When added to a schedule playlist, the Image Fullscreen template defaults to PUD.

### What is the actual behavior?
If you select more than one item including the Image Fullscreen template, it defaults to 10s and PUD must be selected manually.

### What steps can be taken to replicate the problem?
- Create a presentation from the Image Fullscreen template
- Create a presentation from any other template
- In a schedule, add both items at the same time
- Click on the Image Fullscreen template playlist item.  Note that the duration is 10s instead of PUD.

**Comment by ezequielc** [comment]
@PatrickA-RiseVision I could not replicate this. In both cases Image Full Screen was set as PUD for me. I tested with a new Template and a new Schedule. Maybe there is a combination of events for this to happen? Please let me know if you can still replicate it and if possible, a video so I can follow the steps. Thanks!

**Comment by ezequielc** [comment]
Closing the issue as it can no longer be replicated.
@PatrickA-RiseVision fyi. Thanks!
