### ISSUE TITLE
Mail sent on behalf of risevision.com by email.chargebee.com softfails spf check

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1515]
### What is the expected behavior?
Chargebee is allowed to send mail on behalf of Rise Vision

### What is the actual behavior?
Chargebee is not explicitly allowed to send mail on behalf of Rise Vision.  An SPF check would return SoftFail with the ~all group, possibly making messages appear as spam.

### What steps can be taken to replicate the problem?
Lookup the SPF record for risevision.com using a tool such as mxtoolbox.com.  it currently returns this: `v=spf1 include:_spf.google.com include:_spf.firebasemail.com include:2700250.spf03.hubspotemail.net ~all`

Chargebee has shared this article recommending we explicitly include it: https://support.chargebee.com/support/solutions/articles/23167

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision the SPF record has been updated for risevision.com, and I validated with the 3rd party site provided in the documentation that the Chargebee URL is there. Let us know if we encounter further issues. Thanks.
