### ISSUE TITLE
Embedded Presentations are sometimes showing blank white screens and not following durations

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#1520]
### What is the expected behavior?
Embedded Presentations should play for the duration that you set them for, and show in the Placeholder you assign them to.

### What is the actual behavior?
White screens are appearing at random times when the embedded Presentation should be showing, and the duration does not appear to be followed for other content items, or the embedded Presentation when it shares content with other items in the Placeholder.

### What steps can be taken to replicate the problem?
Create a Presentation using the Blank template, add an embedded Presentation and another item. Preview, or watch on a Display.

For example, this is what we see occurring: https://drive.google.com/a/risevision.com/file/d/194p7QffSNHZY5AJYMdQ6i3u1pos04ZES/view?usp=drivesdk

**Comment by ezequielc** [comment]
@fjvallarino Are we goo to close this? Thanks!

**Comment by fjvallarino** [comment]
@ezequielc yes! Thanks!

**Comment by btfrise** [comment]
We have two users that reported this issue earlier this week that are once again reporting it. @robb-price has been able to recreate locally.
