### ISSUE TITLE
Released licenses are assigned immediately to Sub-Company displays if they were previously licensed

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1546]
### What is the expected behavior?
If I remove a License from a Display, I am able to then assign that license to a different Display.

### What is the actual behavior?
If I remove a License from a Display, and another Display was previously licensed and is currently not Licensed, it immediately inherits the License without prompting.

### What steps can be taken to replicate the problem?
- Create a company to behave as the parent company, we'll call it "PARENT".
- Create a company under the parent to behave as a sub-company, we'll call it "SUB"
- Add a subscription for any number of licenses in PARENT.
- Add another subscription for any number of licenses in SUB.
- Create Displays so that all the Licenses in PARENT and SUB are in use.
- Cancel the subscription in SUB.
- At this point you should have a number of licenses in PARENT which are all in use, and a number of Free Displays in SUB.
- Remove a license from a Display in PARENT.
- Refresh your browser.
- The license will have been assigned immediately to a Display in SUB.

Here's a video where I replicate the behavior: https://drive.google.com/a/risevision.com/file/d/11MOUu2bWODeEaa08l9zLAXuhxuUAl0W2/view?usp=drivesdk

**Comment by PatrickA-RiseVision** [comment]
@ezequielc I'm not sure I agree that this isn't a defect, but I'd like to see the behavior mapped out first.  Is the target date for that tomorrow?

**Comment by ezequielc** [comment]
@PatrickA-RiseVision Yes, we are going to share a doc by tomorrow. Thanks

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision as mentioned we've highlighted the behaviour in a doc:
https://docs.google.com/document/d/1L6vsNbFwq-pLMNJIJUMiA44bNM2xD_8G9_1UNWm0Q1Q/edit#

Please review and let us know your thoughts. @sheadarlison @ezequielc FYI.

Thanks!

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision wondering if you could confirm if we can close this defect once reviewed. Thanks!

**Comment by alex-deaconu** [comment]
Closing. Thanks!
