### ISSUE TITLE
App asks for role after it has already been provided

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-vision-apps#1583]
Sign into the rise vision parent company. You'll be [asked for your role](https://www.screencast.com/t/PvVAJk0j1u). Give an answer and save. Then navigate to another company and you'll be asked again. 

I should only be asked once.

**Comment by alex-deaconu** [comment]
@alanclayton a fix has been deployed for this. To confirm, there's still a delay while updating the User settings, so during that time the issue could still occur. However, the general case is fixed.

We are going to queue a card for improving the behaviour to show a spinner while the User settings are updated.

Closing. Thanks.
