### ISSUE TITLE
Companies are signing up without an industry

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#1592]
Run this query: 

`#legacysql
SELECT companyId, industry
FROM [client-side-events:Apps_Events.CustomerJourneyAnalysisView] rg
WHERE
    signup_date     >= '2020-03-01 00:00:00'
    and signup_date     < '2020-03-19 00:00:00'
    and parentid = 'RISEVISIONPARENTID'
    and industry = ""
`

And then look at the companies that show up

**Comment by alex-deaconu** [comment]
@sheadarlison as we discussed, this was introduced by users not selecting an Industry on Sub Company creation. As suggested, we have now set the Industry field as required. Also, the Company size field was swapped with Industry. We also improved the overall functionality of the modal with validation errors appearing on Save. And added Address validation for Add Company which was missing; it will only validate a non-blank address, and for US and Canada only. Closing. Thanks!
