### ISSUE TITLE
Content updates are delayed due to high messaging service traffic

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1611]
### What is the expected behavior?
As the user, when I update my content on Rise Vision, I get immediate feedback that the update was successful on my player.

### What is the actual behavior?
During periods of high traffic on our messaging service, it takes several hours for content to update in some cases.  It's not clear to me why the content does not match what I have built or how long it will take for my content to appear on my Displays.

### What steps can be taken to replicate the problem?
Make a change to a schedule or presentation that is running on a Display during a period of high traffic, i.e. when an alert is captured warning:
"High display-messaging-service incoming bytes
Received bytes for GCS Bucket is above the threshold of 200000 with a value of 1143479.117."

**Comment by tejohnso** [comment]
Fix was released on Friday https://github.com/Rise-Vision/core/pull/693
