### ISSUE TITLE
Additional Display License unavailable in app.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#1613]
**Problem**
User purchased an additional Display License, and it's not being reflected on their risevision.com account. 

**How to recreate**
N/A it appears to only be affecting this user to far.

**Details**
[Rise Vision account](https://apps.risevision.com/displays/list?cid=7edd34a1-4164-4c4b-a72c-e1ffa48dfbcc) shows 4 Display Licenses

[Chargebee account ](https://risevision.chargebee.com/customers/740798/details#events)shows 5 Display Licenses

**Comment by alex-deaconu** [comment]
We double checked and the Chargebee webhook for the Subscription change had not gone through. 

Fixed the issue for the user by rerunning the Webhook.

Confirmed with Chargebee and they had a server issue that they resolved; validated that all the webhook calls that had been in the Pending state went through.

Closing. Thanks!
