### ISSUE TITLE
If your Storage folder has an apostrophe, the content in it will not show

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#1621]
### What is the expected behavior?
Regardless of the name of the folder, the content in that folder should show in the Presentation.

### What is the actual behavior?
If the name of the folder has an apostrophe, the content will never download and show on the Display.

### What steps can be taken to replicate the problem?
Create a folder in Storage with an apostrophe, add content to it, and set a Presentation to view content from that folder. Notice that the content will not download to the Display.

**Comment by ezequielc** [comment]
@robb-price Just to clarify, is this for regular Presentation/Widgets?
And, does the problem happen only on displays or Preview as well? If displays only, what Player version? Thanks!

**Comment by robb-price** [comment]
@ezequielc It happens for both the Presentation Editor, and the Template Presentation Editor. It looks like it only occurs on the Displays, the Presentation Editor and Template Presentation Editor show the content just fine. The Player version I am using is RisePlayerElectron 2020.03.05.21.02 Licensed. Thanks!

**Comment by ezequielc** [comment]
@robb-price Thanks. 
@tejohnso @stulees Who should take a look at this? It doesn't look like an Apps issue per Robb's comment. Thanks!

**Comment by stulees** [comment]
@ezequielc @tejohnso It sounds like either a Storage or Player issue, which neither on our Doing list right now. Maybe we discuss in SoS tomorrow.

**Comment by PatrickA-RiseVision** [comment]
Just wanted to note in case it wasn't already discovered (didn't see it above), this isn't limited to folders.  Files with apostrophes in the title also cannot be downloaded.

**Comment by tejohnso** [comment]
@robb-price This should be fixed now with the latest version which went out to 100% yesterday.
