### ISSUE TITLE
Pausing a subscription in chargebee causes the subscription to suspend.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#1635]
**How to recreate**
In chargebee, pause any active subscription.

**What happens**
The subscription becomes suspended in Rise Vision and Display Licenses are removed from the account.

**What should happen**
Display Licenses should remain active during pause. The subscription should not be suspended.

**Example**
Subscription ID [HngTosfRC7hXdwsDQ](https://risevision.chargebee.com/subscriptions/685922/details)
Company ID [e113f8d6-de1c-4c26-b160-4ef1c4589957](https://apps.risevision.com/?cid=e113f8d6-de1c-4c26-b160-4ef1c4589957)

I paused the subscription in this Company. It removed Display Licenses and suspended the subscription in Rise Vision. I resumed the subscription. The subscription is still suspended. There are no overdue invoices.

**Comment by tejohnso** [comment]
Root cause analysis [doc](https://docs.google.com/document/d/1HBIQ6-6gTBquCINEHu_SMfxdBwwGUwoI3bngSls1Jx0/edit?usp=sharing)
