### ISSUE TITLE
Pricing change notification still showing for existing users

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-vision-apps#1666]
Old price change notification still shows to users that have not acknowledged it.  This should not be shown any longer to anyone. 

![image](https://user-images.githubusercontent.com/6854911/80998947-6d6e0c80-8e09-11ea-92e6-b73f13d84ca5.png)

**Comment by alex-deaconu** [comment]
@alanclayton good catch! The notification has been removed from Apps. Thanks!
