### ISSUE TITLE
Missing Display License appears when saving a new Schedule with only Licensed Displays

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1703]
### What is the expected behavior?
If all displays on a Schedule are licensed, no message is shown when it is saved.

### What is the actual behavior?
Missing Display License appears when saving a new Schedule even if all Displays are licensed.

### What steps can be taken to replicate the problem?
1. Create a schedule.
2. Name it.
3. Add 1 Display that is licensed.
4. Save.

https://drive.google.com/file/d/1ypXe39Nfq3qXDJaLAicxoOzbWSIvH52o/view?usp=drivesdk

### Some additional notes
- If I save without any displays, no error appears.  If I then add the licensed display, no error appears.
- If I select all displays, I get the error every time.

**Comment by ezequielc** [comment]
@PatrickA-RiseVision A fix has been released. The issue actually only occurred when adding a new Schedule on a Subcompany. Let me know in case you still see it. Thanks!
