### ISSUE TITLE
"Click here to License this Display" does not license the Display

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1709]
### What is the expected behavior?
As a user, if my Displays are not licensed, the Display Screenshot and other features are obscured.  There is a "Click here to License this Display" link in the Display Screenshot area to direct me.

If I have an available license, clicking "Click here to License this Display" will solve my problem by Licensing my Display.

If I don't have an available license, clicking "Click here to License this Display" will solve my problem by having me purchase a License, and Licensing my Display.

### What is the actual behavior?
"Click here to License this Display" redirects to Account & Billing.

### What steps can be taken to replicate the problem?
- From a test user account, create a Free Display.
- Make sure you have licenses available in your account.
- Click "Click here to License this Display" in the Display Screenshot field.

**Comment by ezequielc** [comment]
@PatrickA-RiseVision @alanclayton This is working as per JTBD. When company is subscribed to a plan, we redirect them to the billing page so they can manage their subscription.
We are not handling the case of company having available licenses as it has many conditions that could complicate the process, for example if user is not Display Administrator, etc.
I am wondering if we should remove the "Click here to License" message and just show "License Required" instead. Thoughts?

**Comment by PatrickA-RiseVision** [comment]
@ezequielc I agree, the problem currently is that it's confusing for the user.  If the link doesn't solve my problem, it shouldn't say it solves my problem.

**Comment by PatrickA-RiseVision** [comment]
@ezequielc or move the message to where the toggle is.  "License to enable additional features" with something drawing to the toggle.  The toggle already solves this problem by opening the modal when you're out.

**Comment by ezequielc** [comment]
@PatrickA-RiseVision Thanks, I will change the screenshot message to "License Required" without any links.
Also, if I can make it look good, I will try to add the "License to enable additional features" message near the toggle.
@alanclayton fyi

**Comment by ezequielc** [comment]
@PatrickA-RiseVision fyi, I released the "License Required" message update. Thanks!
