### ISSUE TITLE
Google Slides template acts unpredictably if "Show each slide for..." is unset.

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1715]
### What is the expected behavior?
A default duration replaces the actual duration for "Show each slide for:" if it is unset.  If I save the template without a duration, the default duration is kept and the behavior remains consistent.

### What is the actual behavior?
A default duration appears in the field if the value is made blank, but it isn't followed by the templat and instead the slides are changed every 0s.  If you save and/or publish and come back to it, the duration becomes 10 but the changes continue to happen every 0s.

### What steps can be taken to replicate the problem?
Warning, do NOT try to replicate this if you have a history of epilepsy.

1. Create a presentation from the Google Slides template.
2. Make sure your slideshow has more than 1 slide.
3. In "Show each slide for", backspace out the value.

https://drive.google.com/file/d/1SZQG98llo1UYE-97_moMirJ3hc8Dggq6/view?usp=drivesdk

**Comment by ezequielc** [comment]
@olegrise Is this something you should grab? Do you think it requires a fix at the component level? If it is on Apps side, I can take it if you want. Thanks!

**Comment by olegrise** [comment]
@ezequielc I can take it. Sounds like a bug in the Google Slides API, but I need to confirm.

**Comment by alanclayton** [comment]
@olegrise what is the status of this defect?

**Comment by olegrise** [comment]
@alanclayton this issue is fixed. I forgot to close it. PR: https://github.com/Rise-Vision/rise-vision-apps/pull/1720
