### ISSUE TITLE
Text wrap in Apps launcher

### ISSUE THREAD

**Issue by ghislaineguerin** [Rise-Vision/rise-vision-apps#172]
Text should be truncated to one line only

![screen shot 2016-05-26 at 6 29 28 pm](https://cloud.githubusercontent.com/assets/845767/15592217/f6cbbc1a-236f-11e6-802b-f301a3ab050a.png)

**Comment by ghislaineguerin** [comment]
@RV-Adrian please take a look

**Comment by ByronDarlison** [comment]
@ghislaineguerin @RV-Adrian @ezequielc @alex-deaconu what's the status of this defect? Thanks

**Comment by ByronDarlison** [comment]
@ghislaineguerin @RV-Adrian @ezequielc @alex-deaconu can this be closed now? Thanks

**Comment by ezequielc** [comment]
@ByronDarlison Yes, this issue is fixed. I am closing it. Thanks!
