### ISSUE TITLE
Displays added using Claim ID do not get assigned a Display License even if you have one available.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#1735]
### What is the expected behavior?
If you have Licenses available and you add a new Display, it should use one of those available licenses.

### What is the actual behavior?
If you add the Display using a Claim ID, it does not use a Display License, and gets added as a Free Display.

### What steps can be taken to replicate the problem?
Ensure that you have a license available in your subscription, and then add a Display using a Claim ID. Notice that the Display is added as a Free Display.

**Comment by alex-deaconu** [comment]
@robb-price to confirm, a fix has been deployed for this. If a License is available in the Company, the newly created Display will now obtain it. Thanks.
