### ISSUE TITLE
Messaging promoting Shared Schedules continues to obscure the screen even if the user manages to navigate away

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1874]
### What is the expected behavior?

Messaging appears to promote new features in the app when the user logs in.  The screen is obscured, so the only option is to interact with the message until they do.  Once they interact with the message, they are able to use the app as normal.

### What is the actual behavior?

Messaging appears to promote new features in the app when the user logs in, and the screen is obscured, but if the user manages to navigate away (i.e. by clicking the back button on their browser) the screen continues to be obscured and it is impossible to interact with anything.

### What steps can be taken to replicate the problem?

1. Log in at risevision.com with an account that hasn't already seen the messages about Shared Schedules.
2. Get the message promoting the new feature.
3. Click the back button.

https://drive.google.com/file/d/1Q9sATXl-M4UpxJ9JzH8zU9NcokTzbDfy/view?usp=drivesdk

**Comment by ezequielc** [comment]
@PatrickA-RiseVision We talked at SoS and decided it is not worth to solve this issue now as we are going to replace the notification mechanism (use a 3rd party service) in a couple of weeks from now. Thanks!
