### ISSUE TITLE
Editor goes in a ‘Saving’ loop when you make changes to a Presentation, don’t Save and select to Delete the Presentation

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-vision-apps#189]
**How to recreate**
1. Create a new Presentation in the new Editor
2. Make a change to the Presentation such as adding an Image Widget
3. Press Save.  
4. Go back to the Presentation, make a change.  Don't press Save.
5. Select to Delete the Presentation

**What happens**
After you confirm that you want the Presentation deleted, you see the prompt “Do you want to save changes before leaving?”. 

If you press ‘Don’t Save’ your presentation is deleted.  

If you select ‘Save’ or 'Cancel', the screen is stuck on the ‘Saving’.  

If you go back to ‘Presentations’ on the same Window, you are prompted to save changes again.  

**What should happen**
Being able to delete a Presentation without having to save it.

**Comment by ByronDarlison** [comment]
@hcs0 I'm not able to replicate this. Can you capture a video of this in action and post here. Thanks!

**Comment by hcs0** [comment]
@ByronDarlison Sorry, left out a step there.  The newly created Presentation should be saved first, it's only when you return, edit, then delete the Presentation without saving. Recording at http://recordit.co/vpbjV9zSAO

**Comment by hcs0** [comment]
Also what happens when you select 'Cancel' and then 'Don't Save' to delete the Presentation: http://g.recordit.co/jfbpiItcT6.gif
