### ISSUE TITLE
[Editor] Schedules Attribute Hyperlink Styling

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1894]
**Problem:** The "Edit" hyperlink when clicking the schedule menu in the Schedules Attribute needs to conform to the style guide.

![Edit_Presentation___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/88304347-25f37000-ccd6-11ea-9f9a-8f6e13a4bea6.png)

**Solution:** Hyperlink color needs to be "#107DDA". Color needs to remain "#107DDA" on hover. Hyperlink needs to have the "text-decoration: underline;" property.

**Comment by alex-deaconu** [comment]
@jasoncaldwell updated the hyperlinks in the selector as per the suggested styles. To confirm, the updated color, hover and underline were applied. Thanks.
