### ISSUE TITLE
Typo in Presentation message text

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-vision-apps#192]
When you log on as a new user with no presentations and navigate to the presentations view, the message states that 'You haven't created any Presentation yet', instead of 'Presentations'.
<img width="1149" alt="screen shot 2016-06-12 at 1 06 20 pm" src="https://cloud.githubusercontent.com/assets/8008948/15992661/439ebede-309f-11e6-8bc6-523d931d71e2.png">

**Comment by ezequielc** [comment]
@pcsandford Thanks for reporting. Typo was fixed. Cheers
