### ISSUE TITLE
[Display Settings] Clicking "back" after navigating to a display

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1921]
Problem: I noticed that when I navigate to the display settings of a display from the display list, and then click the "back" button, I'm taken to a page other than the display list. Please see this video:

https://www.loom.com/share/929122e9dd8e449e97b47074fc5fe7eb

**Comment by alex-deaconu** [comment]
@jasoncaldwell good catch! A fix has been deployed for this. Closing. Thanks!
