### ISSUE TITLE
[Schedule Details] Styling defects

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1924]
### 1. Shading under "Create Playlist Item"

**Problem:** there should be no shading/drop-shadow under the "Create Playlist Item" during a click, or otherwise.

![Edit_Schedule___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/88968799-e13f7a00-d27d-11ea-9bf7-c37e4d4f36aa.png)

---

### 2. Timestamp styling

**Problem:** the timestamp at the bottom needs to have a value of `#999999` or `#020620`.

![Edit_Schedule___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/88969011-2f547d80-d27e-11ea-9109-433f254df821.png)

**Comment by ezequielc** [comment]
@jasoncaldwell Fixes for both issues were released. Thanks!
