### ISSUE TITLE
[Preview/Schedule Details] Previewing Portrait Templates

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1925]
**Problem:** When I preview certain portrait templates, part of the template is cut off/not centered in the preview area. Please see this video:

https://www.loom.com/share/30168650014549378b189ddef74c106b

Schedule URL used in the video:

https://preview.risevision.com/?type=sharedschedule&id=b41f563b-f153-4a91-9af5-66175aa0d3d7

**Comment by ezequielc** [comment]
@jasoncaldwell As per discussion in [this card](https://trello.com/c/32UskyTQ/6476-issue-1925-preview-schedule-details-previewing-portrait-templates-initial-investigation-summary-1), we are going to pursue this pas part of Android Player epic. Closing ti for now. Thanks.
