### ISSUE TITLE
Files that are deleted from Folders continue to show in Presentations.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#1928]
### What is the expected behavior?
When you remove an image from a folder, and an image Widget is watching that folder, that image should be removed from the rotation of images.

### What is the actual behavior?
Images that are removed from the folder, and are now in trash, are continuing to show in the Presentation.

### What steps can be taken to replicate the problem?
View a Folder of images using the Image Widget, remove some of the images, notice that they still remain in the Presentation.

FYI - If you permanently delete the images from the Trash Folder and restart the Display, this corrects the issue.

**Comment by robb-price** [comment]
@tejohnso Confirmed this is corrected on all OS's using the steps taken above.

**Comment by tejohnso** [comment]
Thanks @robb-price
