### ISSUE TITLE
Very large video files fail when being uploaded, and give no evidence of having failed, nor show the Retry option.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#1931]
### What is the expected behavior?
Regardless of the size of the video file, it should be able to be uploaded successfully to be added to a Presentation.

### What is the actual behavior?
The size has varied, but a user has reported that their larger video files, between 3 and 8 GB's, fail when trying to upload, and there is no retry option. It just fails.

### What steps can be taken to replicate the problem?
Using an 8.1 GB video file, I was able to recreate, and get the appropriate info over to Tyler.

**Comment by tejohnso** [comment]
@robb-price Closing as we confirmed yesterday the retry is now working.
