### ISSUE TITLE
Display page does not look right

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-vision-apps#1970]
## See image

```
Chromium | 84.0.4147.125 (Official Build) Arch Linux (64-bit)
```

![display](https://user-images.githubusercontent.com/1511535/90401054-6b078980-e06b-11ea-9551-f68808842962.png)

**Comment by tejohnso** [comment]
@ezequielc @alanclayton Per SoS, here's what I'm seeing. Doesn't look right to me. I can't see my display details, and the call to action is **Save** but I don't know what I would be saving.

**Comment by ezequielc** [comment]
@tejohnso @alanclayton Apart from the License Toggle, the screenshot matches the [new UI](https://app.abstract.com/share/bdc62d33-6be2-4350-a110-acaafc385f2f?collectionId=97b1dcbe-30e3-45ea-bf5c-6c33868dbee8&collectionLayerId=bbc5b8dc-136c-481f-b878-055e754dd891&present=true&preview=false&sha=89007062a16ff60014342a57aa9cd82e9c3f1889) that is being implemented as part of our current epic.

The "... no updates to show right now..." message is part of the schedule being previewed. If the schedule does not have content scheduled for that time, that is the message we show.

We will work on fixing the toggle, but I don't think there is nothing else here. Unless we want to revisit the UI with Jason. Thanks!

**Comment by alanclayton** [comment]
@ezequielc makes sense.

**Comment by ezequielc** [comment]
@tejohnso  Toggle has been corrected. Let us know in case you still see it broken. Thanks!
