### ISSUE TITLE
No licensed displays error message shows even when there are only URLs in schedule.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#1979]
### How to recreate
- Create a new schedule
- Add a free display
- Add a scheduled URL

### What happens
The schedule shows the error message You selected 1 unlicensed display that won’t show your content. License it?

### What should happen
There should be no error message.

[Example Schedule](https://apps.risevision.com/schedules/details/30b4ae33-4f17-418a-b94a-fd96d8e4ae75?cid=e113f8d6-de1c-4c26-b160-4ef1c4589957)

**Comment by ezequielc** [comment]
@btfrise A fix has been released. Thanks!
