### ISSUE TITLE
[Display Settings] UI Feedback

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1994]
### Capitalization of text on modal

![Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/1440943/90901923-b38bb380-e399-11ea-8d05-887731be5abe.png)

---

### Input for monitoring email

![Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/1440943/90902562-a622f900-e39a-11ea-8e35-52ea1ba455bb.png)

---

### Hyperlink color for "Chrome Enterprise" on the "Share" menu

![Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/1440943/90902953-411bd300-e39b-11ea-9d44-c6c3b81d4ddf.png)

All hyperlinks need to be `#107DDA;` and have `text-decoration: underline;` as a property. The style of hyperlinks shouldn't change on hover.

---

### Copy changes for Display Details area

![Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/1440943/90903203-9a840200-e39b-11ea-9a5a-e6dbbc6e2955.png)

**Comment by ezequielc** [comment]
@jasoncaldwell I have fixed styles for screenshoot #2, but I could not replicate the placeholder text being cut off. I am on Mac OS Chrome 84. Let me know if you can still replicate and your Chrome version. Thanks

**Comment by ezequielc** [comment]
@alanclayton Long Schedule name has been fixed. 

@jasoncaldwell If you see the placeholder cut off issue again, please let me know. As everything else has been addressed I will close the defect for now. Thanks!
