### ISSUE TITLE
[Checkout] Tax Exemption Submission Bug?

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2034]
**Problem:** When I submit tax exemption information, log out, and then log in to a new account. The tax exemption inputs ("Tax Exemption Number" and "Tax Exemption Document") are populated.

See this video:

https://www.loom.com/share/4304b1a72adf4d25b7b0c949ff9085cc

**Comment by alex-deaconu** [comment]
@jasoncaldwell a fix for this has been deployed and validated. To confirm, we are now resetting the form every time the Tax Exemption option is opened. Closing. Thanks.
