### ISSUE TITLE
Apps seems to be creating forms in HubSpot 

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#2035]
See photo: https://www.screencast.com/t/cZelBN7Az

Forms seem to be getting created by Apps on the log in/reset/sign up pages when some users enter their information.

I don't think these forms should be getting sporadically created.

**Comment by alex-deaconu** [comment]
Fixed by disabling the setting to create forms in Hubspot. Validated that they are no longer being created in Apps, and that nothing is broken in other places. Closing.

@sheadarlison fyi. Thanks.
