### ISSUE TITLE
Contacts are being erroneously created in HubSpot 

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#2036]
Contacts are being created in HubSpot by the apps sign up page that don't exist in datastore and aren't associated with a company. 

Contacts shouldn't be created in HubSpot by apps unless they have finished signing up and can be associated with a company. 

Example: https://app.hubspot.com/contacts/2700250/contact/71207951/

**Comment by alex-deaconu** [comment]
This was caused by Hubspot identify being called once the User was shown the registration form. This means the User would be created despite them not being registered. Fixed by moving the identify to after the User registers. Thanks.
