### ISSUE TITLE
Http / Https notification shows on preview regardless of url in presentation content.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#2046]
**What happens**
Create a presentation with the web page widget. Add the url https://risevision.com.
Preview the presentation, the notification still appears.

**What should happen**
If the presentation contains only https urls, no notification or call to action should show.

**Additional details**
Users are confused, they are getting this notification even though they may not have a problem. This is creating extra touches for support.

**Comment by ezequielc** [comment]
@btfrise @alanclayton As discussed in SoS, we decided to no longer show this message. 
We will remove it and confirm there are no references to Nov-1 date in Apps. Thanks!

@alex-deaconu fyi

**Comment by alex-deaconu** [comment]
@btfrise to confirm, this notice has now been disabled from appearing on Preview links in Apps. We are also removing the Nov 1 reference from the Schedule Item modal shortly. Closing. Thanks.
