### ISSUE TITLE
Not able to Save presentation after deleting multiple Widgets in a Placeholder

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-vision-apps#205]
**How to recreate**
1. Open a Presentation that was previously created 
2. Make sure that there are multiple Widgets located within a Placeholder
3. Delete at least one Widget 

**What happens**
When I delete at least one Widget, the 'Save' button is still a light green color, indicating that I cannot save it.

See http://g.recordit.co/rxTgW6Wzdy.gif

**What should happen**
When I delete, I should be able to save the Presentation

**Comment by hcs0** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/conversation/5266442029

**Comment by ByronDarlison** [comment]
@ezequielc can you take a look at this asap? Thanks

**Comment by hcs0** [comment]
@ezequielc They mentioned that the workaround was to delete widget from placeholder, go to the presentation properties - hit apply then save, then go back to placeholder.  You can use https://apps.risevision.com/editor/workspace/8af88c33-d9c9-4b4c-8665-3fd730d434c7/?cid=960b72df-9af7-476b-8a47-b67ded4c779d as the presentation example (from the screen recording)

**Comment by ezequielc** [comment]
@hcs0 Issue should be fixed by now. Could you confirm? Thanks

**Comment by hcs0** [comment]
@ezequielc Confirmed - thanks!
