### ISSUE TITLE
Clicking and dragging playlist items in a schedule on mobile doesn't work

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#2053]
iPhone / iOS 14 / Safari 

1. Open a schedule on mobile
2. Add multiple playlist items 
3. Attempt to click and drag

Video: https://drive.google.com/file/d/1PBxaBdtvqeofPKmScCKviHIr5RL3CvtO/view?usp=sharing

The icons for copy and trash are also misaligned. @jasoncaldwell how should these icons be aligned on mobile?

**Comment by jasoncaldwell** [comment]
@sheadarlison Icons should right-aligned and spread horizontally. Also, click + drag is working for me on safari/iOS, although it is a bit buggy.

See below:

![IMG_6589](https://user-images.githubusercontent.com/1440943/94021514-164de180-fd82-11ea-856d-aef4cc26aeb7.png)

**Comment by ezequielc** [comment]
@sheadarlison @jasoncaldwell Drag&drop and alignment on mobile have been fixed and released to production. Thanks!
