### ISSUE TITLE
Playlist Items with long names and timelines escape their bounds and are illegible

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2060]
### What is the expected behavior?
Items within the Schedule playlist are legible.

### What is the actual behavior?
When the name of the playlist item and/or its schedule gets too long, the text escapes the bounds of the playlist and become hard to read.

### What steps can be taken to replicate the problem?

1. Create a presentation with a really long name.
2. Add it to a schedule.
3. View the item in the schedule's playlist.

Screenshot below.

![image](https://user-images.githubusercontent.com/40774237/94163311-11f6f680-fe5e-11ea-8a0e-ca4765b3c8e6.png)

**Comment by ezequielc** [comment]
@PatrickA-RiseVision This has been fixed. Thanks!
