### ISSUE TITLE
URL Schedule Playlist items which link to files cause automatic downloads without permission when previewed

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2068]
### What is the expected behavior?
Playlist items can be added to a schedule by URL, allowing you to play a web page that is hosted externally on a rise vision display.

### What is the actual behavior?
Playlist items can be added to a schedule by URL, but there is no restriction to the URL used.  Adding a URL that is not a web page triggers an automatic download without prompt when the page is previewed.

### What steps can be taken to replicate the problem?
- Upload a file like a Powerpoint presentation to Rise Storage.
- Obtain the link to the file in Rise Storage.
- Add it to your schedule playlist by URL.
- Copy the shared schedule link for the presentation.
- Paste it into a web browser.

**Comment by ezequielc** [comment]
Details in this card: https://trello.com/c/suMKVHW7/6679-issue-2068-url-schedule-playlist-items-which-link-to-files-cause-automatic-downloads-without-permission-when-previewed-2
