### ISSUE TITLE
You can't change a background color on a Placeholder if you don't change something else in the Presentation

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#207]
<b>How it works now:</b>
1. Add a Placeholder to a Presentation, change the background color, save and publish.
2. Now change the background color again, but don't change anything else. Notice that you cannot save the change since you have not modified anything else in the Presentation.

For further clarification: https://goo.gl/qmjDG7

<b>How it should work:</b>
Since a background color change is a modification to the Presentation, the Save button should become available after you do that.

**Comment by alex-deaconu** [comment]
@robb-price a fix for this has been deployed to Production. Can you please verify when you have a chance? Thanks!

**Comment by robb-price** [comment]
@alex-deaconu  Verified and Closed.

Thanks!
