### ISSUE TITLE
Cannot create any new presentations

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#2135]
### How to recreate
Add any new Presentation from a Template
**OR**
Add a Blank Template, add content, click save

### What happens
Error message Failed to add Presentation. The Presentation could not be added. Please try again.

### What should happen
We should be able to add Presentations.

**Comment by tejohnso** [comment]
Closed - see [post mortem](https://docs.google.com/document/d/1uNBk1fhDhy-4Uq3dQc2Q-FNd3W67uTohoZI20PZF1og/edit)
