### ISSUE TITLE
If there are multiple placeholders, with multiple widgets set to the same duration, they do not rotate together.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#2139]
### How to recreate
Create a presentation with 3 placeholders.
Put 3 pieces of content in each placeholder.
Set the duration of each piece of content to 15 seconds.
Preview.

### What happens
The content will not rotate synchronously. 

### Additional information
Reported by user with [this presentation](https://apps.risevision.com/editor/workspace/4048b78c-0fc7-46b7-a5f5-326a02c0b3ed?cid=a0368bd3-7115-4970-8004-314904fdf8a4). He says they have been using this same format for around 2 years and the content has rotated as expected until 19-October-2020.

**Comment by sheadarlison** [comment]
@btfrise I don't think this is a defect. We have never supported synchronized playback. In creative when we had projects that required content to be synchronized we would always break content into separate presentations or use embedded presentations.

**Comment by alex-deaconu** [comment]
@btfrise I took a quick look at this issue. We haven't made any changes in Viewer for the past few months, so it would not be related to that. However, looking at the 3 placeholders in the issue, they have Spreadsheet widgets. We have recently made some changes re: load timers for those which could potentially impact the synchronization behaviour that they were previously seeing. Thanks!

**Comment by alanclayton** [comment]
Agreed.

**Comment by btfrise** [comment]
@alex-deaconu thanks. Should I open the defect in the widgets repo then?

**Comment by alex-deaconu** [comment]
@btfrise I'll defer to @alanclayton and @stulees for that question. Thanks!

**Comment by btfrise** [comment]
Moved. https://github.com/Rise-Vision/widget-google-spreadsheet/issues/330 Closing.
