### ISSUE TITLE
[Templates/Editor] Can't add the thanksgiving template

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2141]
**Issue:** When I click on the thanksgiving template "Add" button, it says "Failed to add presentation."

![Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/1440943/96673777-42cf2c00-1335-11eb-9080-8a99f4080069.png)

![Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/1440943/96673740-2e8b2f00-1335-11eb-8475-f0873b2a8050.png)

**Comment by ezequielc** [comment]
@mmeiers fyi, as other templates look fine, I think it is something wrong with the spreadsheet entry. Could you take an initial look? Thanks!

**Comment by ezequielc** [comment]
@mmeiers I assume you fixed this. I confirmed it is working. Closing it. Thanks!
