### ISSUE TITLE
Shared Presentations is not available unless you add a template Presentation

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#2142]
### What is the expected behavior?
The Shared Presentations button should always be available for your sub companies.

### What is the actual behavior?
The Shared Presentations button is not available until you have at least 1 template presentation in your company.

### What steps can be taken to replicate the problem?
Create a new sub company, go to the Presentations tab, notice that the Shared Presentations option is not available.

**Comment by ezequielc** [comment]
@jasoncaldwell Sorry to bother you again, but I will need UX input here too.
Robb is referring to the fact that we hide Shared Presentations button (and search bar) when the Presentations list is empty:
<img width="1236" alt="Screen Shot 2020-10-21 at 3 01 04 PM" src="https://user-images.githubusercontent.com/7738553/96767719-443f3980-13b3-11eb-8f5c-e0b9f9427c22.png">
vs:
<img width="1240" alt="Screen Shot 2020-10-21 at 3 00 56 PM" src="https://user-images.githubusercontent.com/7738553/96767716-430e0c80-13b3-11eb-83b6-ef9130d143ad.png">

I am wondering if we should continue to show them, along with the empty list message. Let me know your thought. Thanks!

**Comment by jasoncaldwell** [comment]
@ezequielc I'm fine with putting the "Shared Presentations" button to the left of the "Add From Template" button here:

https://user-images.githubusercontent.com/7738553/96767716-430e0c80-13b3-11eb-83b6-ef9130d143ad.png

**Comment by ezequielc** [comment]
@jasoncaldwell Sounds good, I will do that. Thanks
