### ISSUE TITLE
Displays page shows update available but no actions or context are provided.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#2147]
### How to recreate
Have a Display that is running an older version of Rise Player. [Example ](https://apps.risevision.com/displays/details/RTP4P2NYSG3G?cid=9710196b-1af1-4a0d-88ef-25f5a69d5636)

### What happens
Display page shows old version of Rise Player, and Update Available.

### What should happen
If we show an error message, or a status message like update available, we should provide context on how a user can fix the problem.

Ideally, the end user can't see update available.

**Comment by btfrise** [comment]
@ByronDarlison @alanclayton @tejohnso FYI

**Comment by ezequielc** [comment]
As per [slack discussion](https://rise-vision-inc.slack.com/archives/CCELMSZFZ/p1603467909105000), I am going to remove the 'Update available' message from Apps. Thanks
