### ISSUE TITLE
When displays are exported to CSV, all displays are exported instead of selected displays.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#2148]
### How to recreate
In a company with multiple displays, select less than the total number of displays in the company. Export to CSDV

### What happens
The total number of displays in the company are exported, not just those selected.

### What should happen
Only the selected displays should be exported to CSV.

**Comment by tejohnso** [comment]
@ezequielc during planning discussion we concluded the whole network would be exported with the api call. Is that your recollection as well?

**Comment by ezequielc** [comment]
@tejohnso Yes, that was the conclusion: https://docs.google.com/document/d/19C_sNmoEwyhBnA7Rv8BkSaS5-4_daXTdVNbmjGd35DE/edit?ts=5f4fd29e#bookmark=id.r1wbi5juixvm Thanks!

**Comment by ezequielc** [comment]
@ByronDarlison @jasoncaldwell  I am wondering if we should have a separate button/link above the displays list for the Export. I agree with @btfrise that it is confusing for users to select some displays but export all. Let me know if you have any suggestions. Thanks!

**Comment by ByronDarlison** [comment]
@ezequielc I missed something along the way. Where did we decide that export only exported All displays? Can you point out where in this doc that conclusion was reached? https://docs.google.com/document/d/19C_sNmoEwyhBnA7Rv8BkSaS5-4_daXTdVNbmjGd35DE/edit?ts=5f4fd29e#bookmark=id.r1wbi5juixvm Thanks!

**Comment by ezequielc** [comment]
@ByronDarlison From what I remember, the discussion happened in a call with Tyler, Alexey, Alan, you and me, on the same call that discussed on sending the CVS file as a zip attachment instead of download link. 
We only listed the conclusion in the doc, in the [bookmarked link](https://docs.google.com/document/d/19C_sNmoEwyhBnA7Rv8BkSaS5-4_daXTdVNbmjGd35DE/edit?ts=5f4fd29e#bookmark=id.r1wbi5juixvm). Thanks

**Comment by ByronDarlison** [comment]
@ezequielc I missed that completely. Sorry about that. And can you clarify why we had to go that route? @alanclayton @alexey-rise @tejohnso if anything to add please jump in. Thanks

**Comment by ezequielc** [comment]
@ByronDarlison To be honest, I don't remember :) I believe it had to do with the fact that it wasn't clear if subcompanies displays would be included and that 'select all' would only select the displays visible in the UI, not all company's displays. Thanks

**Comment by tejohnso** [comment]
@ByronDarlison I don't think we had to. I think we were talking about keeping it simple, and it was simpler to give them everything rather than have them pick/choose which ones they want, and then set up the api call to accept potentially hundreds of individual displays while skipping others. See discussion for Process point #1

**Comment by ByronDarlison** [comment]
> @ByronDarlison To be honest, I don't remember :) I believe it had to do with the fact that it wasn't clear if subcompanies displays would be included and that 'select all' would only select the displays visible in the UI, not all company's displays. Thanks

Yup, I remember the above, but I don't remember that translating to we only export all displays. Can we fix this so we export what is selected? Is that doable? Thanks

**Comment by ezequielc** [comment]
@tejohnso I could easily provide the list of selected displays to Core endpoint. Not sure about the complexity from your side, but I assume it is doable.

@ByronDarlison If we only export selected displays, we would no longer export the entire network. Should we consider adding another action in the UI for that? I assume it is a common scenario. Thanks!

**Comment by ezequielc** [comment]
@ByronDarlison @btfrise @alanclayton @tejohnso @jasoncaldwell  We talked. The compromise for now is to rename 'Export' to 'Export All'. If we hear more from users, we can revisit. Thanks!

**Comment by alex-deaconu** [comment]
@btfrise the wording update has been released. Closing. Thanks!
