### ISSUE TITLE
[Network UI Epic] Consolidated Feedback/Visual Defects

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2164]
### "Select None" hyperlink when doing bulk actions

**Issue:** Should there be a "Select none." to the right of the selection count when doing bulk selections as the maximum number of selections has been reached, [as per the design](https://share.goabstract.com/49c3e18f-2403-4b67-a360-3e61bd14a188?collectionLayerId=f0b5c6e7-bdb8-4ad9-8903-56b73f875ed7&mode=design):

![Displays___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/97588419-d7d7c200-19d2-11eb-8774-5974b0ae4de6.png)

---

### Padding around bulk actions menu.

**Issue:** Please reduce top/bottom padding for the bulk actions menu:

![Displays___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/97588783-3bfa8600-19d3-11eb-885b-d21f12a9ff61.png)

I'd recommend a `padding` value of `5px 20px` for that element.

---

### Search "no results" copy.

**Issue:** Please add a period (".") to the end of this sentence:

![Schedules___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/97589759-4d905d80-19d4-11eb-97ff-05deb02c11f3.png)

---

### Possible bug for display license assignment.

**Issue:** UI won't let me assign a license to a display. Please see this video:

https://www.loom.com/share/bcffa23e6f1c4ed4a539fe43c91311f5

---

### Possible bug for display license count.

**Issue:** UI has "-1" as the number of licensed displays. Please see this video:

https://www.loom.com/share/d279bbc80b4d4e1f937b898e21492467

**Comment by alex-deaconu** [comment]
@jasoncaldwell to confirm, we have corrected the UI defects you have identified, however still looking into the Licensing issues from your last two points. Will keep this defect open until we have some conclusions and potential fixes. Thanks!

**Comment by ezequielc** [comment]
@jasoncaldwell We fixed the licensing issues. Basically, we were failing to notify the UI when a failure happened server side and the count would be incorrect. Thanks!
