### ISSUE TITLE
[Legacy Editor] Color Picker Doesn't Hide

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2176]
**Issue:** I noticed that when I'm editing the settings on a legacy template, I'm not able to hide the color picker. Please see this video:

https://www.loom.com/share/bf701aea0bc14beeb38a1bcd1a2d8b92

**Comment by alex-deaconu** [comment]
@jasoncaldwell a fix for this issue has been deployed. Thanks!
