### ISSUE TITLE
Last Connection not showing in display list

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-vision-apps#2189]
Details in this doc, https://docs.google.com/document/d/1Dn2QrMwBJSWpF41UyW1C8Av5ShMECukvqElbkccWIKM/edit

**Comment by alex-deaconu** [comment]
@tejohnso @alexey-rise we initially thought this was related to the fact that we were retrieving `lastActivityDate` from the messaging service, however it seems that the Display list response for this Display is missing that field. Wondering if you could take a look. @ezequielc fyi. Thanks!

**Comment by tejohnso** [comment]
This is corrected with the above merge. I monitored the affected display until it encountered a natural disconnect / reconnect cycle to confirm that it is now showing the correct last connection time in the [display listing](https://apps.risevision.com/displays/list?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55).  

Closing as validated.
