### ISSUE TITLE
Bulk delete Presentation fails when it is used in an Embedded Presentation

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rise-vision-apps#2207]
### What happens
Bulk delete Presentation fails when it is used in an Embedded Presentation and the presented error message is not clear, asking the user to retry.

### What should happen instead
When a bulk delete Presentation fails, we clarify the reason and list one of the embedding Presentations so that the user can clearly identify and fix the problem

**Comment by alex-deaconu** [comment]
@ezequielc the fix for this has been released. To confirm we are not showing the first error message we get back from the Core in the error bar. We have also improved the error message to make it more generic. Thanks.
