### ISSUE TITLE
Cookies are disabled warning and not able to log in on iOS 14.1 and later.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#2227]
**What happens**
When trying to log in to apps.risevision.com with a google account on an ipad or iphone with iOS 14.1 or later, we see a Cookies are disabled warning, and are redirected to the login screen after logging in.

**How to recreate**
On any iOS 14.1 or later device go to apps.risevision.com and attempt to log in using google.

**Notes**
In Safari settings I've found that _Prevent Cross-Site Tracking_ is enabled by default on 14.1 and later. If I disable this, I can successfully log in but the cookies error message is still shown.

The cookies error message appears regardless if black all cookies or prevent cross-site tracking is disabled.

**Comment by ezequielc** [comment]
@btfrise This is now resolved as per https://github.com/Rise-Vision/rise-vision-apps/pull/2269. Thanks!
