### ISSUE TITLE
UI bug when deleting presentations with Shared Schedules modal open

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2229]
### What is the expected behavior?
Our layout stays consistent when performing actions on the website, i.e. menus stay where they are until you are done interactng with them.

### What is the actual behavior?
In the Schedule Settings, if you delete all the presentations in your playlist while you have the Shared Schedules modal open, it is moved to the top-left of the screen.

### What steps can be taken to replicate the problem?
-Go to Schedules.
-Pick a schedule.
-Click on "Share" to open the modal.
-Delete all presentations from the playlist by clicking the trash can.

Here's a quick video demo: https://drive.google.com/file/d/1mRh8ylzuoX0haVOpcLzSRo5CdnFlqx2c/view?usp=drivesdk

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision this issues should now be resolved. Thanks!
