### ISSUE TITLE
Override Brand Colors setting is ignored in Preview and Shared Schedules when any presentation uses brand colors

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2230]
### What is the expected behavior?
Override Brand Colors allows you to set a color other than your Brand Color for a single presentation.  The behavior should be the same in preview, shared schedules, and on a display.

### What is the actual behavior?
In preview and shared schedules, a presentation that has override brand colors selected will show brand colors instead if another presentation in the same schedule uses brand colors.

It behaves as expected on a display.

### What steps can be taken to replicate the problem?
1. Set brand colors on a presentation.
2. Create a presentation that uses "Override Brand Colors" and use different colors.
3. Add both presentations to the same schedule.
4. Preview the schedule, or use Shared Schedules to view the schedule in your browser.

Here's a quick video demonstrating: https://drive.google.com/file/d/1JqgCDUYym33tcFO0GB1NMMuvlvsaItdq/view?usp=drivesdk

**Comment by ezequielc** [comment]
@stulees @olegrise fyi. Thanks

**Comment by olegrise** [comment]
Fixed
