### ISSUE TITLE
[Legacy Editor] Can't cancel video upload

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2238]
Issue: I can't cancel the upload for a video. Please see this video:

https://www.loom.com/share/4b00da1869f7453c938df9e9741c025d

**Comment by ezequielc** [comment]
@tejohnso I am wondering if this is related to Video encoding. Thanks

**Comment by tejohnso** [comment]
@jasoncaldwell I've confirmed this is corrected in production. Canceling now works as expected for a video file. Let me know if you need us to take another look. In the meantime I'll close it.
