### ISSUE TITLE
Clicking the Help button does nothing

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2241]
### What is the expected behavior?
Clicking Help opens the Elev.io widget allowing users to search HC and contact support.

### What is the actual behavior?
Nothing happens.

This looks to be probably caused by a problem with the elev.io API: https://status.elev.io/

The problem isn't captured, so the user isn't directed anywhere.  The button just doesn't work.

### What steps can be taken to replicate the problem?

1. Log in to risevision.com
2. Click help
3. Get no help :(

**Comment by PatrickA-RiseVision** [comment]
This was related to an AWS outage that persisted through the day yesterday, which is a dependency of the elev.io api.  The issue is now resolved.

**Comment by PatrickA-RiseVision** [comment]
Reopen as per discussion at SoS about next steps.

**Comment by santiagonoguez** [comment]
@PatrickA-RiseVision a failback has been implemented and released. Whenever elev.io script is not available, help.risevision.com will open in a new tab.
