### ISSUE TITLE
Able to do some modifications and save changes to deprecated content in the new Editor

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-vision-apps#225]
**How to recreate**
Create a presentation with deprecated content item. See this <a href=“https://apps.risevision.com/editor/workspace/9be94b31-9e99-4fcb-8245-091ce7121589/?cid=960b72df-9af7-476b-8a47-b67ded4c779d”>example</a>

Go to the new Editor and select Cancel when you see the Deprecated Item pop up.

Continue editing the Presentation (i.e. add an Image Widget)

Select Save and Publish

**What happens**
A user is able to do some (but not all i.e. change image links) modifications to deprecated content such as changing the Placeholder arrangement.

They are able to go back into RVA, add deprecated content (such as Presentation Item) and go to the new Editor and they can continue using the new Editor with the deprecated content.

**Notes**
Go to 1:57 of this session https://www.fullstory.com/ui/U3O/session/5478226483740672:5478226483740672!5671617594130432 you can see this on a live (i.e. not test) use case where they selected Cancel on the pop up and continued editing the Presentation.

I also thought that there are additional barriers (ie extra pop ups) to a user being able to save / make changes to deprecated content on the new Editor.

**Comment by alex-deaconu** [comment]
@hcs0 wondering why you think this is an issue. Unless there's a bug where if you save deprecated content in the New Editor it somehow breaks the Presentation (which it shouldn't), this is normal behaviour. @ezequielc thoughts? Thanks.

**Comment by ezequielc** [comment]
@hcs0 I agree with @alex-deaconu . I believe it works like that by design, the pop up is a warning that the Presentation is not fully supported but users are still able to change other components. Thanks!

**Comment by hcs0** [comment]
Ok thanks, I didn't realize you can still change other components. I'll close this now. @alex-deaconu @ezequielc

**Comment by ezequielc** [comment]
👍 Thanks @hcs0

**Comment by alex-deaconu** [comment]
@hcs0 thanks!
