### ISSUE TITLE
Display deletion modal closes without action after entering failsafe and pressing enter.

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-vision-apps#2252]
Expected: Entering the failsafe in a delete confirmation modal and pressing enter should result in a deleted display.

Actual: Entering the failsafe in a delete modal and pressing enter closes the modal without deleting the display.

See [video](https://drive.google.com/file/d/1tGut0-f9D-TaDX-GYp_oY5vug_WGVBtj/view?usp=sharing).

**Comment by alanclayton** [comment]
@tejohnso the video link isn't workin for me.

**Comment by tejohnso** [comment]
> @tejohnso the video link isn't working for me.

Can you download and play it locally? Works for me on a ScreenConnect dev machine (Windows 10).

Alternatively, you can try to replicate yourself:

 1. Go to the displays list.
 2. Click the checkbox next to one display.
 3. Cick the actions dropdown and select DELETE.
 4. In the modal popup, press 1 then press ENTER.

The modal will disappear without doing anything.

**Comment by santiagonoguez** [comment]
This has been fixed, thanks !
