### ISSUE TITLE
Search not finding relevant templates

### ISSUE THREAD

**Issue by osmankarame** [Rise-Vision/rise-vision-apps#2265]
**Reproduction Steps**
1. On the presentation page, I click on **Add From template**
and by example I look for Human rights, I write human ri or right, it doesn't found the template called Human Rights

**Expected Results**
I expect to see the templates before having to complete the word. or adding a "s".
https://www.screencast.com/t/omBbtOgk

**Actual Results**
Not finding any templates.
https://www.screencast.com/t/ElH2M2Mez61j

**Comment by ezequielc** [comment]
@alanclayton @alexey-rise @tejohnso This came up in the past, our search mechanism does not match partial words, only the full word. I believe it is a limitation of Google Search API and considering we want to move away from it, I think we should either close or block this defect until we migrate. Thanks

**Comment by alanclayton** [comment]
Thanks @ezequielc I recall the same. @tejohnso can you confirm?

**Comment by alexey-rise** [comment]
@ezequielc @alanclayton Google Search API does not support partial matches but that is not a limitation of Google Search API, rather it is a "feature" of a full-text search. If we migrate to other full-text search mechanism we will have the same problem.

If we want to support partial matches in a full-text search system we need to tokenize all text for all possible (or all desirable) substrings and add them to the index (e.g. "hello world" -> "he,hel,hell,hello,wo,wor,worl,world").

**Comment by tejohnso** [comment]
I think Elasticsearch would allow partial matches via [wildcard query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html)

**Comment by alex-deaconu** [comment]
We could move the search to the client side since we retrieve the whole list anyways (no paging). It would be instantaneous and we would support partial word search. Thanks.

**Comment by alanclayton** [comment]
@tejohnso @ezequielc @alexey-rise @alex-deaconu what is the conclusion? is this something we can/should pursue right now?

**Comment by ezequielc** [comment]
We talked, we are going to proceed with Alex's suggestion. Thanks

**Comment by alex-deaconu** [comment]
As discussed we have implemented client side search in Apps, which should resolve the partial word search issues. Closing. Thanks.
