### ISSUE TITLE
Schedule name doesn't update in Displays list

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2270]
### What is the expected behavior?
References to schedule names is consistent across the Displays list, Display Settings and Schedules.

### What is the actual behavior?
If a schedule is renamed after it's assigned to a display, the name in the Displays list does not get updated.

### What steps can be taken to replicate the problem?
1. Create a schedule with an arbitrary name.
2. In display settings, assign the schedule to a display.
3. Return to the schedule and rename it.
4. Click on Displays and note that the schedule's name did not update.

Here's a quick video demonstration: https://drive.google.com/file/d/1uIAslRZSI_rPL_DLRR5HPNq-AqUzi8Ew/view?usp=drivesdk

**Comment by ezequielc** [comment]
@alexey-rise @tejohnso fyi, I assume this is related to reindexing Schedule name on server side. Thanks

**Comment by alanclayton** [comment]
@alexey-rise @tejohnso @ezequielc what is the status of this defect?

**Comment by tejohnso** [comment]
This was closed on February 11th with this [card](https://trello.com/c/cPFiPbYe/6311-presentations-list-shows-1-schedule-when-a-presentation-has-not-been-scheduled)
