### ISSUE TITLE
Mobile menu bar is appearing on desktop

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#2271]
It's just peaking in from the left-hand side:

https://www.screencast.com/t/VMLOF3jpy0

Chrome / Windows 10 / ~1700px viewport width

**Comment by sheadarlison** [comment]
This is making it so that I can't add placeholders in the editor

**Comment by alex-deaconu** [comment]
@sheadarlison I’m having a tough time replicating this issue.

I fixed it for the resolution in question (and smaller up to 992px), but I would like to know if it’s still appearing in resolutions smaller than that, if it ever was in the first place. 

Wondering if you could validate at https://apps-stage-18.risevision.com/ when you have a moment and let me know.

Thanks!

**Comment by sheadarlison** [comment]
@alex-deaconu it's not happening for me anymore at stage-18. 

Thanks!

**Comment by alex-deaconu** [comment]
@sheadarlison thanks for confirming!

**Comment by alex-deaconu** [comment]
@sheadarlison the fix for this has been deployed, closing. Thanks!
