### ISSUE TITLE
[Schedules] Duplicating settings without saving

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2273]
**Issue:** When I edit the timeline settings for one schedule, it's mirroring those setting changes in other schedules without saving.

Please see this video:

https://www.loom.com/share/2bc0d6c710ec444aa2951d7c9461e370

**Comment by ezequielc** [comment]
@jasoncaldwell I took a look at the issue and could not replicate. I think it was just a coincidence of the values from your schedules. Please take a look at my recording: https://drive.google.com/file/d/1cFwHckr5yYSj2wdod1IcU8Qr7UkYcZYY/view?usp=sharing. Thanks!

**Comment by jasoncaldwell** [comment]
@ezequielc Sounds good, let's close. 👍

**Comment by ezequielc** [comment]
@jasoncaldwell Thanks!
