### ISSUE TITLE
Using Scott's Digital Signage Android Video Player, you cannot double click on a file from Storage to select it

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#229]
<b>How it works now:</b>
1. Add the Android Video Widget to your Presentation, open the Rise Storage File Selector in the Widget. 
2. Before, you were able to double click on the file to select it, but this no longer works. Now the double click just selects and unselects the video.

<b>How it should work:</b>
When you double click the file from the Storage selector, it should select it.

**Comment by alex-deaconu** [comment]
Reviewed issue. The Widget tries to access Storage via the Old URL (storage.risevision.com). Suggested that (if he's using the Storage Selector Component), he should update the the latest version to fix this.

Will follow up with him if he's not using the Component, or there are further issues.

**Comment by alex-deaconu** [comment]
Attempted to fix this from our side with a redirect. However the component has a domain check so it will not accept the `postMessage` result from apps.risevision.com. 

Ultimately he will have to update the component to the latest version.
