### ISSUE TITLE
Storage Selector requires you to click it twice when adding anything from Storage at rva.risevision.com

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#232]
<b>How it works now:</b>
1. Add a Video or Image Item at rva.risevision.com. Click the Storage Selector, and then select your media.
2. Add another Image or Video Item. Click the Storage Selector, and notice that it has the original media selected. You need to click it to unselect it, then click the Storage Selector again, and select the file you want.

This happens for anywhere in the old editor that requires you to go into the Storage Selector.

For further clarification: https://goo.gl/2ETx5U

@alex-deaconu This was the issue reported by Tony <a href="https://community.risevision.com/rise_vision_inc/topics/media-library-not-working-correctly">here</a>. As requested, I logged it so you can investigate and determine if you are goin to fix.

**Comment by alex-deaconu** [comment]
@robb-price this has been fixed. Please verify and notify the user. Thanks!

**Comment by robb-price** [comment]
Verified, and user has been notified.

**Comment by alex-deaconu** [comment]
Thanks @robb-price
