### ISSUE TITLE
Unpaid Invoices page displays only totals before discounts and payments

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2321]
### What is the expected behavior?
Unpaid Invoices page shows the amounts of all unpaid invoices so they can be previewed.

### What is the actual behavior?
Unpaid Invoices page displays only the total before discounts, which is misleading.  Clicking "Pay Now" on a given invoice shows the actual amount after discounts and credits.

### What steps can be taken to replicate the problem?
- Generate an invoice.
- Apply a credit to the invoice.
- View the Unpaid Invoices page.  The amount won't account for the credit.

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision we should now be showing the correct Amount Due for unpaid invoices, which would include Credits, etc. For paid invoices, since the Amount Due is $0, we would be showing the Total as before. Closing. Thanks.
