### ISSUE TITLE
Presentations list shows "1 Schedule" when a presentation has not been scheduled

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2332]
### What is the expected behavior?
On the presentations list, the "Schedules" column indicates how many schedules a presentation appears in.

### What is the actual behavior?
Under some conditions the presentation can appear to be scheduled when no schedules are chosen.

### What steps can be taken to replicate the problem?
I haven't been able to replicate this myself, but I have an example where a customer's presentation is doing this.

Here's a quick video overview: https://drive.google.com/file/d/125T7UvlEcoI1OPxPEWgoX8WDuVb-7GSd/view?usp=drivesdk

I can share the link to the presentation separately.

**Comment by alexey-rise** [comment]
@PatrickA-RiseVision we have fixed the issue for the examples you provided, however we were unable to replicate it or determine the ultimate cause, so the issue may re-occur in the future.
We added additional logging to help us better diagnose the issue if it does re-occur.
