### ISSUE TITLE
"Add Display License" Consolidated UI Feedback

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2366]
### Padding below "Cost will decrease" box

**Issue:** The padding below this box:

![Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/104503851-9c02d080-55af-11eb-804c-0450c3285feb.png)

should be `15px`.

---

### Button sizes

**Issue:** These buttons:

![Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/104504001-d40a1380-55af-11eb-8f57-f17abff9a109.png)

should be using [our "Large" button sizes](https://docs.google.com/document/d/1JaurbTMAWsHZIauyrENMVdM1shwdzb5BqtKkjSURVoI/edit#bookmark=id.9bkt4s31wbfk).

---

### Padding below coupon code input

**Issue:** The padding below this input:

![Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/104504637-c012e180-55b0-11eb-9bc6-1e0622dd2df8.png)

should be `15px`.

---

### Upper limit for number of additional display licenses

**Issue:** Should there be an upper limit (maximum) number for how many display licenses someone can add? When I enter a ridiculously high number (`55555555555555555555555555555555555555555555555`, for example), I get this:

![Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/104504936-31eb2b00-55b1-11eb-9856-2217d8051a03.png)

---

### Input size for additional display license amount

**Issue:** This input:

![Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/104505015-4e876300-55b1-11eb-9fda-eb3f37691af5.png)

Is bigger than [the mockup](https://overflow.io/s/I1SU0UQE?node=ccf09664). My preference would be for it to match the mockup.

---

### Opening up the "contact us" form in the help widget.

**Issue:** When you click this link:

![Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/104505372-c5bcf700-55b1-11eb-8e0c-80a48ca18a27.png)

Can we open the contact form like this:

![Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/104505427-dc634e00-55b1-11eb-9ffd-e9c390456674.png)

---

### Opening up the "common questions" article in the help widget.

**Issue:** When you click this link:

![Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/104505511-00269400-55b2-11eb-97fe-d078ca1c931c.png)

Can we open the article in the help widget directly, like this:

![Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/104505581-20565300-55b2-11eb-84d7-1f6e570b7620.png)

**Comment by ezequielc** [comment]
@jasoncaldwell I have two questions:

1. Re. "Input size for additional display license amount", it is larger than mockups because we reused the input/styling from plan selector. We can easily change to match the mockups, but just want to confirm your preference here.

2. Re. "Opening up the "common questions" article in the help widget.", we didn't find a reliable way to open the article in the widget. It is possible to open it, but it relies on a specific id from elev.io, which we are not sure will always remain the same. So to avoid future issues, our recommendation is to keep as is and open in a new tab. Let me know if good with you. Thanks!

**Comment by jasoncaldwell** [comment]
@ezequielc 

1: My preference would be to match the input size from the mockups.
2: Copy that, I'm fine with that (opening an external help article). Just wanted some clarity.

**Comment by ezequielc** [comment]
@jasoncaldwell Sounds good, I will update the input size. Thanks!

**Comment by ezequielc** [comment]
@jasoncaldwell fyi the issues above were solved. Thanks!
