### ISSUE TITLE
Password reset emails are sometimes not received by users

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2379]
### What is the expected behavior?
As a user, when I click "forgot password" and provide my email, I receive an email to reset my password.

### What is the actual behavior?
As a user, occasionally when I click "forgot password" and provide my email, I do not receive anything and have to reach out to support.

### What steps can be taken to replicate the problem?
The exact steps for replicating this are unknown.

In theory it should be:
1. Go to risevision.com
2. Click sign in
3. Click "Forgot your password?"
4. Enter your email address and click "Email me reset instructions"

I received the email when following the above steps, but users occasionally report that they cannot and need support to help them reset.

**Comment by PatrickA-RiseVision** [comment]
@jasoncaldwell as discussed

**Comment by alexey-rise** [comment]
As discussed in Trello card, there is nothing to fix given the example provided. If more examples can be found, we will reopen the issue and investigate further. Closing for now.
