### ISSUE TITLE
Credit Card payments made from the new Invoice page don't account for credits

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2385]
### What is the expected behavior?
When an invoice is adjusted for any reason (offline payments, balance carried forward, credits applied, etc.) the balance on the invoice is adjusted accordingly on the Invoice page in the app.  When a payment is made by credit card, the balance is what is charged.

### What is the actual behavior?
The balance on the invoice is adjusted correctly on the Invoice page in the app,  When a payment is made by credit card, the unadjusted total on the invoice is charged to the credit card.  The remainder is added to the account as unallocated excess payment.

### What steps can be taken to replicate the problem?
1. Generate an invoice.
2. Add a credit to the invoice.
3. Log in to the account at risevision.com
4. Go to account & billing
5. Find the invoice and click "Pay Now"
6. Pay it from here with a credit card

Instead of charging the adjusted amount after credits, the full amount is charged to the card.

**Comment by ezequielc** [comment]
@PatrickA-RiseVision this issue should now be fixed. Thanks.
