### ISSUE TITLE
"Pay Now" and "View Unpaid Invoices" links redirect logged-in users to Billing

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2386]
### What is the expected behavior?
Clicking "Pay Now" on an unpaid invoice or the "View Unpaid Invoices" link directs to a summary of unpaid charges that does not require a log in.

### What is the actual behavior?
A given link can be accessed by a user who is not logged in by clicking on it.  Logged-in users who click the link are redirected to billing.  Trying to navigate to this page in the app also redirects the user.

### What steps can be taken to replicate the problem?
1. Log in at risevision.com
2. Poke your face on the top-right
3. Click on Account & Billing
4. Click on "View Unpaid Invoices"
5. You're redirected

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision this issue should now be resolved. Closing. Thanks.
