### ISSUE TITLE
Placeholder Playlist does not go all the way to the bottom when you scroll

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#239]
<b>How it works now:</b>
In a Placeholder that has 25+ items, try to scroll to the bottom of the Placeholder playlist. Notice that can't get to the bottom items:
![2016-08-18_13-17-38](https://cloud.githubusercontent.com/assets/6862256/17783786/8e70f3aa-6547-11e6-9d7f-55eb08bfeb25.png)

Presentation to test with: https://apps.risevision.com/editor/workspace/f7bbfc9e-a343-450d-b07a-4225d270803c/?cid=556323b8-984c-4127-aa08-4d73d019bcb8. Look at the Posters Placeholder.

<b>How it should work:</b>
Regardless of the amount of items in a Placeholder's Playlist, you should be able to scroll to the bottom of it.

**Comment by RV-Adrian** [comment]
@ezequielc @alex-deaconu 

Height fix:
![bug](https://cloud.githubusercontent.com/assets/11826611/17786037/1b1830d0-6551-11e6-9160-0583ed3396e3.gif)

PR for fix at https://github.com/Rise-Vision/common-style/pull/268

**Comment by robb-price** [comment]
@RV-Adrian Looks like this is fixed, can this issue be closed?

**Comment by RV-Adrian** [comment]
@robb-price All wrapped! Can be closed now, thanks
