### ISSUE TITLE
[Templates] Problem with MLK Jr Template

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2416]
Problem: When I click on the MLK Jr Template

![Presentations___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/106510568-1cc13800-649d-11eb-975c-7783ce35a3b8.png)

it says:

![Presentations___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/106510603-28acfa00-649d-11eb-981a-2cb671ddb1ed.png)

**Comment by jasoncaldwell** [comment]
@mmeiers @osmankarame

**Comment by mmeiers** [comment]
@jasoncaldwell thank you for catching and logging this. It's fixed now.

**Comment by jasoncaldwell** [comment]
👍
