### ISSUE TITLE
If the cost to modify your subscription is under 50 cents, an error message is displayed and you can't proceed.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#2419]
### What is the expected behavior?
A message should be displayed recommending you contact Support, or more preferably, we allow Chargebee to make changes to a subscription under 50 cents (if possible) so the user can self serve.

### What is the actual behavior?
If you try to make a change to your subscription and it is under 50 cents to make the change, this error is displayed:
![processed](https://user-images.githubusercontent.com/6862256/106613284-04eac200-6538-11eb-8ec7-6ee75f082c25.jpeg)

### What steps can be taken to replicate the problem?
Add a display license to your subscription when there is under 1 hour left until it renews.

**Comment by ezequielc** [comment]
@robb-price @brianloosbrock I would like to confirm what we should do about this issue. I verified that this is a limitation of Stripe: https://support.chargebee.com/support/solutions/articles/228511-transaction-amount-limit-in-stripe.

I am considering leaving as is given the error message is very clear and this condition is not a common case.

But I am also ok with Robb's suggestion and show a message recommending to contact Support. If we go this path, my preference would be to display the detailed error message and append a generic "Please contact Support if you are having problems" which would be appended to every error message we show (address errors, card errors, etc). Thoughts? Thanks!

@alex-deaconu fyi

**Comment by robb-price** [comment]
@ezequielc That would work, but would it be possible to have it create a ticket automatically, and notify the user that something went wrong, and a ticket was automatically created for them?

@brianloosbrock FYI, this is what we discussed this morning in Standup.

**Comment by ezequielc** [comment]
@robb-price Automatically creating the ticket would be much more complex to implement. We don't have any other feature that does that so we would need to create that infrastructure, which I don't think it is justifiable for this issue. Thanks

**Comment by brianloosbrock** [comment]
@ezequielc We talked, quick recap;

- For any error the customer is getting when trying to make changes to a subscription or pay an invoice, what we call “billing” errors, we’ll append the following text to the error message. “If you need help please email us at support@risevision.com.”
- You’ll give us a query so we can put a process in place in support to review billing errors weekly to gain insight into what customers are experiencing and what we can do about them.

FYI @robb-price

**Comment by ezequielc** [comment]
@brianloosbrock @robb-price I added the query to our Queries shared drive: https://docs.google.com/document/d/1T-QlZbdpPy_hqGrvUTSleSUsJmyq9y0YVDA53iOANqk/edit.

I will let you know once I append the message in Apps. Thanks!

**Comment by ezequielc** [comment]
@robb-price @brianloosbrock fyi, appended message has been deployed. Thanks!
