### ISSUE TITLE
Images with % in the title say "Please wait while your image is downloaded" and never show in preview or on a Display

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#242]
<b>How it works now:</b>
1. Upload an image to Storage that has a % in the name.
2. Add that image to your Presentation, and notice that it sits on "Please wait while your image is downloaded" and never shows the image in the Editor, Preview, or on a Display.

Presentation to test with: https://apps.risevision.com/editor/workspace/ad673348-449d-440c-b352-75b0013d82a6/?cid=556323b8-984c-4127-aa08-4d73d019bcb8

**Comment by alex-deaconu** [comment]
Investigated the issue. Basically, a Javascript error is thrown when calling `decodeURIComponent()` with an already decoded URI (`100% Particpiation gallup.jpg` in this case). This issue occurs with these types of URIs in Apps (when uploading a file with `%` characters in it) and in Widgets, in the Rise Storage component.

In Apps, the error occurs here https://github.com/Rise-Vision/rise-vision-apps/blob/master/web/scripts/storage/services/svc-storage.js#L22 where we call `decodeURIComponent` with an un-encoded URI. @ezequielc @settinghead FYI, I will implement a fix for this, specifically.

In the component, the error occurs here https://github.com/Rise-Vision/web-component-rise-storage/blob/master/rise-storage.html#L1334 where `decodeURIComponent` is called twice for the same filename. @rodrigopavezi @stulees @donnapep FYI, wondering if you can open a similar issue for this in your project to fix.

Thanks!

**Comment by alex-deaconu** [comment]
Fixed issues with `%` in file/folder names in Apps.

Issue with Widgets is logged in a separate repo: https://github.com/Rise-Vision/web-component-rise-storage/issues/94

Closing. Thanks!
