### ISSUE TITLE
Unable to remove billing notification emails

### ISSUE THREAD

**Issue by olegrise** [Rise-Vision/rise-vision-apps#2428]
Similar to the https://github.com/Rise-Vision/rise-vision-apps/issues/780, I see this happening in the following situations:

-  I type invalid email and leave the field. The "Please provide a valid email" is shown and after that I can'd remove previously added email or make this field valid again.
- If I use address with autocomplete, "Please provide a valid email" validation error is triggered right away and then after that you cannot do anything.

Here is the video. 

https://user-images.githubusercontent.com/6841220/106773538-29fe3400-660f-11eb-9db8-864b7a8ba4f4.mov

**Comment by ezequielc** [comment]
@olegrise Issue has been solved. Thanks!
