### ISSUE TITLE
[Billing] Consolidated Feedback 

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2430]
**Consolidated feedback for:**

- Subscription Details page
- Add Payment Method page
- Remove Display Licenses page
- Change Plan to Yearly page

---

## Button copy on Add Payment Method Page

![Subscription___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/106795751-7a35c000-6628-11eb-8c0a-9d11b3ca706c.png)

Copy should be `Cancel`.

---

## Text color on toggles 

![Subscription___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/106795998-c7199680-6628-11eb-9a88-1afef58dcde9.png)

![Subscription___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/106797910-3d1efd00-662b-11eb-820e-33b52a9e8975.png)

The text for the part of the toggle that isn't selected should be black `#020620`. 

---

## Text size for "Remove" hyperlink 

![Subscription___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/106796702-b9b0dc00-6629-11eb-811c-052146ebf6f5.png)

This was my fault, but this text needs to be `14px`.

---

## American_express copy

![Subscription___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/106798390-e1a13f00-662b-11eb-8737-0e75aabfdfea.png)

Not sure if this is a bug or not, but should "Amercian_express" read as "American Express"?

**Comment by ezequielc** [comment]
@jasoncaldwell All issues above were resolved. Thanks!

**Comment by jasoncaldwell** [comment]
@ezequielc 👍
