### ISSUE TITLE
[Editor] Tooltip Text Cut Off

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2459]
When adding a text widget to legacy presentations, there's a tooltip for "PUD Failover" when you select "Scroll > By Page". The tooltip text is cut off for me (OSX + Chrome).

![Mouse_Highlight_Overlay_and_Edit_Presentation___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/107886551-7af30f80-6ece-11eb-9889-b0fecd1481fa.png)

**Comment by ezequielc** [comment]
@stulees @olegrise fyi, this is a Text widget settings defect. Thanks!
