### ISSUE TITLE
Display Screenshots don't work

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#2462]
### What is the expected behavior?
Pressing Update in the Display Screenshot section in Display Settings should update the screenshot of what is on the display.

### What is the actual behavior?
Regardless of the status of the display, it immediately fails to take the screenshot, instead stating "There was a problem requesting the screenshot."

### What steps can be taken to replicate the problem?
Go to any online display, and try to take a screenshot.

**Comment by tejohnso** [comment]
@robb-price I think this is resolved now as [discussed](https://rise-vision-inc.slack.com/archives/CD10S3YTT/p1613511094130300). Closing.
