### ISSUE TITLE
Ticker subscriptions do not have friendly names in the Account & Billing page

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2467]
### What is the expected behavior?
The Account & Billing page shows customers their subscription information so they can self-serve.

### What is the actual behavior?
LED Ticker subscriptions and even more notably C-Scape ticker subscriptions have really unclear names only in the Account & Billing page.  As the customer, I don't understand what this is or what I'm paying for.

These names are consumer-friendly in Chargebee.

![image](https://user-images.githubusercontent.com/40774237/108394028-a46fac00-71ea-11eb-8c62-5465159800a6.png)

### What steps can be taken to replicate the problem?
1. Add a subscription for LED Ticker or C-Scape iCandy ticker to a company
2. View the company's account & billing page
3. Click on the subscription to view details

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision this should now be corrected. Both the LED Ticker and C-Scape products should show correctly now, along with some other Ticker and Financial products which are actually archived in Chargebeee. Closing. Thanks.
