### ISSUE TITLE
Expire apps_events log data that is older than 24 months

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-vision-apps#2469]

**Comment by ezequielc** [comment]
@alanclayton I noticed that by removing data older than 24 months, we would be impacting some queries @sheadarlison uses for display activation rate, signups, etc.
I briefly talked with him and he would like to discuss before we move forward with this.
He suggested we should delete only PII fields, but that is more complicate. So let me know your thoughts. Thanks!

**Comment by alanclayton** [comment]
@ezequielc just talked to @sheadarlison on a revised plan. Could we do this instead: 

1. back up data older than 3 years so it is available if we find we need it for some reason
2. purge data older than 3 years and on a going forward basis.

**Comment by ezequielc** [comment]
@alanclayton We talked. I double checked and we store ~5MB/day in apps_events, as we only send customer journey relevant events (all other Apps events are sent only to Segment). Therefore, 1 year of data is equivalent to ~2GB, which costs $0.04/month. 
Based on that, I don't think it is worth pursuing backing it up and purging the data. It is better to keep it there, so it is available when needed. I will close the defect, but let me know in case you disagree. Thanks!

@sheadarlison @alex-deaconu fyi
