### ISSUE TITLE
Placeholder Properties window does not show entirely on smaller resolution browsers

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#247]
<b>How it works now:</b>
1. Open the Presentation Editor on a 1366 x 768 monitor, and go into a Placeholder. Notice that the Playlist can scroll to the bottom, but the Properties cannot.

For further clarification: https://goo.gl/9TCl3t

**Comment by RV-Adrian** [comment]
@robb-price 
Fixed and tested all lists on desktop (and mobile to be sure):
https://apps-stage-3.risevision.com/editor/workspace/0de758cc-6188-4fd1-9807-b125de842e72/

Reference:
![bug2](https://cloud.githubusercontent.com/assets/11826611/18070776/390f2cc6-6e1e-11e6-920b-61b1d37a08ee.gif)

**Comment by robb-price** [comment]
@RV-Adrian Verified at https://apps-stage-3.risevision.com/. Can we close this? Or do you want to close after it is deployed?

**Comment by RV-Adrian** [comment]
@robb-price Going to run a couple of issue fixes by the Apps team today, then get them closed.  Should be wrapped by end of day.

**Comment by robb-price** [comment]
@RV-Adrian Verified and closed!
