### ISSUE TITLE
[Templates] Clicking On Template Thumbnail Shows Error Message

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2470]
Clicking on the "International Women's Day" template results in an error message.

![Presentations___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/109561247-e7633680-7aaa-11eb-9e9d-96048d5c68f7.png)

**Comment by jasoncaldwell** [comment]
@osmankarame @mmeiers

**Comment by osmankarame** [comment]
Oh thank you Jason! Fixed
