### ISSUE TITLE
Clicking "Send me a Quote" on the Purchase page redirects to the Pricing page

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2472]
### What is the expected behavior?
"Send me a quote" button puts the user in touch with Sales who will then create and send a quote.

### What is the actual behavior?
On the Pricing page it works as expected, but on the Purchase page it does nothing but redirect the user to the Pricing page.  Information is not retained so the buyer must re-select the number of displays, whether or not they're a school, monthly or annual, and then click "Send me a quote" again to get the form.

### What steps can be taken to replicate the problem?
1. Sign up with a new company
2. Click on subscribe in the header
3. Click on send me a quote

**Comment by ezequielc** [comment]
@PatrickA-RiseVision @sheadarlison Button has been changed to "Contact Sales" as per conclusion above. Thanks!
