### ISSUE TITLE
[Legacy Editor] Sharing Legacy Presentations With Sub-Companies Uses "Last Revised" Version

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2473]
**Issue:** When sharing legacy presentations with sub-companies:

![Mouse_Highlight_Overlay_and_Edit_Presentation___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/110823385-0eb2c400-8260-11eb-9766-d6a5deeaef73.png)

It shares the "last revised" version of the presentation.

**Expected behavior:** When sharing legacy presentations with sub-companies, it shares the "last published" version of the presentation.

**Comment by ezequielc** [comment]
@jasoncaldwell This has been the behaviour for many years, since its original implementation. Therefore, if we want to change how it works, I think we should scope it as part of Editor changes, instead of a defect. Let me know if you agree. Thanks!

@alanclayton fyi

**Comment by jasoncaldwell** [comment]
@ezequielc Gotcha, thanks for the context. Is there a specific reason why we're doing it this way? Maybe some context would be helpful.

**Comment by ezequielc** [comment]
@jasoncaldwell Sorry, that precedes me joining Rise, so I don't have context as well :)

**Comment by jasoncaldwell** [comment]
@ezequielc Thanks!

**Comment by ezequielc** [comment]
@jasoncaldwell Just to confirm, are you good with closing this for now? Thanks!

**Comment by jasoncaldwell** [comment]
@ezequielc Yep, let's close this and address changes in future pitches. Thanks!
