### ISSUE TITLE
Can't license a display in a sub company when the parent has available licenses

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#2475]
### What is the expected behavior?
If there is an available license, you should be able to license a new display in a sub company.

### What is the actual behavior?
Regardless if you have a display license, you cannot license a new display you create in a sub company.

### What steps can be taken to replicate the problem?
Ensure you have a license in the parent, switch to the sub and create a new display. Notice that you cannot license it.

This video shows the process:  https://drive.google.com/file/d/1HzNpvecYzNbb_3fnkz9-BdRjXS8shQYd/view?usp=drivesdk

**Comment by ezequielc** [comment]
@robb-price In the video I see this happened on a Test company. Just to confirm, did you see the same behaviour on customers accounts too? Thanks

**Comment by robb-price** [comment]
@ezequielc Looks like the "Share Company Plan" was unchecked. I checked that, and confirmed with the user that this corrected the issue. Must have been human error, as the user can't see that option. Thanks!

**Comment by ezequielc** [comment]
@robb-price Good to hear it is solved. Thanks!
