### ISSUE TITLE
Cannot confirm if emails to new non Google users are being sent.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#2476]
### What is the expected behavior?
We need to be able to confirm that emails are being sent to users who add non google accounts to their organizations.

### What is the actual behavior?
Users state the did not receive the account addition email, and Support cannot confirm that the email was sent out.

**Comment by alexey-rise** [comment]
@robb-price would adding Support to BCC of those emails work as a confirmation?

**Comment by robb-price** [comment]
@alexey-rise Support is going to discuss the best way to deal with this issue, and I will get back to you on this after we have discussed it. Thanks!

**Comment by robb-price** [comment]
Closing this issue, as we will simply record a video every time a user has this request, to A) confirm it works, and b) send that video to the user to show them the confirmation.
