### ISSUE TITLE
If you are in a Presentation in your Parent Company and you switch to a Sub Company, the Editor stays on the Presentation in the Parent Company.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#248]
<b>How it works now:</b>
1. Open a Presentation in your Parent Company.2
2. Switch to a Sub Company. Notice that the Presentation remains on the Presentation from your Parent Company.

Also:
1. Make a change to the Presentation in the Parent Company and do not save.
2. Switch to the Sub Company, and click on Presentations. Notice that it does not ask you to save, and it removes you from the Sub Company and takes you back to the Parent Company.

For further clarification: https://goo.gl/k5Kw8h

<b>How it should work:</b>
If you switch to a Sub Company while you are in a Presentation in the Parent, it should tell you that Presentation is not available in the Sub Company and spit you out to the Presentations page.

**Comment by ezequielc** [comment]
@robb-price In relation to the first scenario, as both the User and the Presentation belong to the Parent Company, the User has permission to edit the Presentation, therefore it remains in the same Presentation. This behaviour is debatable, but I don't think it is an issue as it work as designed. If you agree, I will keep it as is.
The second scenario is clearly an issue and I am working on a fix. 
Thanks!
@alex-deaconu fyi

**Comment by alex-deaconu** [comment]
@robb-price just a heads up. @ezequielc fixed this issue as discussed in the "Second scenario" above. The fix is now deployed (the issue was closed automatically when the PR was merged). Please verify. Thanks!

**Comment by robb-price** [comment]
@alex-deaconu Verified!
