### ISSUE TITLE
[Template Editor] "Failed to add presentation" Error

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2486]
When clicking the "Add Template" button from the Playbook for the "April is Volunteer Month" template, I get a "Failed to add.." error:

![Presentations___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/112504696-6a05ab80-8d62-11eb-9010-ed5616d0c527.png)

**Comment by ezequielc** [comment]
@mmeiers fyi, I believe this is a template issue. Thanks

**Comment by osmankarame** [comment]
Thank you! Fixed
