### ISSUE TITLE
[Add A Display] Clicking "Cancel" Doesn't Undo Edits After Previous Save

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2493]
Please see this video:

https://www.loom.com/share/814da38880c14d6fb84f3ee661ae6c8f

**Comment by ezequielc** [comment]
@jasoncaldwell This has been resolved. Thanks!

**Comment by jasoncaldwell** [comment]
@ezequielc Thanks!
