### ISSUE TITLE
If you remove duration and then set presentation to Play Until Done in the schedule, it will skip that presentation.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#2498]
### What is the expected behavior?
If you set a presentation to Play Until Done in a schedule, it should follow that duration.

### What is the actual behavior?
If you remove the duration and then select Play Until Done, it will skip that presentation in the playlist and on the display.

### What steps can be taken to replicate the problem?
The steps in this video show the entire process: https://drive.google.com/file/d/1o6ZME9j1QAeYJ-W3eUlViqFn0wu8Xfde/view?usp=drivesdk

**Comment by alex-deaconu** [comment]
@robb-price moved to https://github.com/Rise-Vision/viewer/issues/509. Closing. Thanks.
