### ISSUE TITLE
[Display Licenses] Sub-Companies Can Accidentally Disconnect From Parents

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2503]
**Issue:** If a sub-company inherits display licenses from a parent, and there aren’t any display licenses available, and it attempts to access features throughout the app that require a display license or attempts to license a display directly from the display details page, the user can end up creating subscriptions by accident if they follow the in-app prompts:

![2021-03-15_14-15-56_MP4_-_Google_Drive](https://user-images.githubusercontent.com/1440943/113348613-cc335300-9304-11eb-9c1e-4dd423a3de18.png)

thereby disconnecting the display license inheritance from the parent.

Expected behavior: If a sub-company inherits display licenses from a parent, and there aren’t any display licenses available, and it attempts to access features throughout the app that require a display license or attempts to license a display directly from the display details page, the modal copy + CTA should be updated, [as depicted here](https://docs.google.com/document/d/1a3HbeaOQR9q0eK-NWUSPDG37bxF8-OYZ9JRTzaCka_Y/edit#bookmark=id.ylkp42ggu56i).

**Comment by ezequielc** [comment]
@jasoncaldwell The behaviour was changed as per discussion in the doc and the modal text was also updated. Thanks!
