### ISSUE TITLE
Adding or removing display licenses from a sub-company's subscription creates a subscription for the parent

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2517]
### What is the expected behavior?
On the account & billing page, I can click the subscription I want to modify, then add or remove display licenses by clicking the respective buttons.

### What is the actual behavior?
On the account & billing page, if I click on a subscription that is shipped to a sub-company, attempting to add or remove display licenses creates a new subscription in the parent instead.

### What steps can be taken to replicate the problem?
1. Create a subscription in a company that is shipped to a different company.  Currently there's no way to do this in-app, so it will have to be created manually in chargebee.
2. Go to the parent company
3. Click your username, then account & billing
4. click the subscription that's shipped to the other company
5. Add or remove display licenses

Here's a quick video: https://drive.google.com/file/d/1CvnLixzNU4-Gp49hcqVCurgk1zyaDi-D/view?usp=drivesdk

**Comment by ezequielc** [comment]
@PatrickA-RiseVision This has been resolved. The issue was actually an Apps navigation problem when parent didn't have a plan. Thanks
