### ISSUE TITLE
Webhooks for subscription cancellations due to non-payment are "not applicable" and not processed

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2518]
### What is the expected behavior?
When a subscription goes unpaid for 75 days from its due date, the subscription is cancelled automatically due to non-payment.  Invoices still owing are credited automatically and any display licenses are no longer available to the customer.

### What is the actual behavior?
When a subscription goes unpaid for 75 days from its due date, the subscription is cancelled automatically in chargebee and the webhook is "not applicable".  The invoice is credited and the subscription is cancelled, but display licenses remain active in the customer's account indefinitely.  The invoice appears as "Paid" in the app, though it's clear it's been written off if the PDF is downloaded.

### What steps can be taken to replicate the problem?
- Have a subscription cancel due to non-payment

We're not sure why we've only identified 2 cases of this so far, so I'm not sure what conditions cause the webhook to be "not applicable".

For more details see trello card: https://trello.com/c/rvm25xdN/7290-issue-2518-webhooks-for-subscription-cancellations-due-to-non-payment-are-not-applicable-and-not-processed-3

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision we have deployed a fix for this issue. To confirm:
- We are no longer setting a Subscription to Active when a `write_off` occurs. This should fix the main problem.
- We confirmed that the Suspended Subscription will be set to Cancelled as expected.
- We explored the option of adding a label in the Invoice list to indicate it has been written off, but upon discussions we decided not to release that. It will be thought through and addressed in a more thorough manner with a proper Pitch and Epic.

@brianloosbrock @ezequielc fyi. Closing. Thanks!
