### ISSUE TITLE
Cannot log in as the second account when using multiple Gmail or Google accounts

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#256]
<b>How it works now:</b>
1. Be logged into Gmail as 2 separate accounts.
2. Open https://apps.risevision.com, and try to select the second account to log in as.
3. Notice that it has logged you in as the first account.

For further clarification: https://goo.gl/6yvwiz

</b>How it should work:</b>
It should log you in as the account you selected.

**Comment by ezequielc** [comment]
@robb-price This is fixed, could you confirm? Thanks
