### ISSUE TITLE
Storage selector is missing some icons

### ISSUE THREAD

**Issue by olegrise** [Rise-Vision/rise-vision-apps#2566]
<img width="886" alt="Screen Shot 2021-04-28 at 2 34 16 PM" src="https://user-images.githubusercontent.com/6841220/116456556-674e1880-a830-11eb-9b3e-d8b65fe7757b.png">

**Comment by alex-deaconu** [comment]
@olegrise nice find! A fix has been deployed for this. Thanks!

**Comment by olegrise** [comment]
@alex-deaconu awesome! Thanks.
