### ISSUE TITLE
Editor Playlist icon position error

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-vision-apps#258]
Playlist Item Type icon position is too high on Safari browsers.

![image](https://cloud.githubusercontent.com/assets/11826611/18887017/68eff890-84c0-11e6-92eb-4c60c58deae0.png)

**Comment by ezequielc** [comment]
This issue is fixed: https://trello.com/c/D4KNK9u7/1702-issue-258-editor-playlist-icon-position-error-1
