### ISSUE TITLE
[Login] Copy Change

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2596]
**Issue:** If your Rise Vision account authenticates via Google, and you attempt to login to Rise Vision via an email + password combo (instead of Google), the error message copy is inaccurate.

![Sign_In___Rise_Vision_Apps](https://user-images.githubusercontent.com/1440943/118026630-02fe7f00-b32f-11eb-9dbd-d51e4ecbd751.png)

**Comment by alex-deaconu** [comment]
@jasoncaldwell nice find! The wording has been updated. Closing. Thanks!
