### ISSUE TITLE
When you overwrite an image in Storage, the thumbnail does not update, and the Preview/Editor take 1+ hours to update to the new Image

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#262]
<b>How it works now:</b>
1. Have an image from Storage running in a Presentation on a Display.
2. Upload an image to Storage that has the exact same file name as the image in your Presentation.
3. Notice that after 5 - 20 minutes, the image on the Display will update.
4. Notice that the image in Preview and the Editor takes at a minimum 1 hour to update.
5. Notice that the thumbnail in Storage never updates.

For further clarification: https://goo.gl/zeb3ff

<b>How it should work:</b>
Once you have overwritten the older file, the new one should show in Editor and Preview, and the thumbnail should update in Storage immediately after the upload.

**Comment by robb-price** [comment]
@alex-deaconu @ezequielc Any updates on this?

**Comment by ezequielc** [comment]
@robb-price This issue is going to be addressed in our next Sprint. Thanks

**Comment by ezequielc** [comment]
@robb-price This should be fixed. Could you confirm? Thanks
