### ISSUE TITLE
Ambiguous error when uploading files from a template with no subscription

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2628]
### What is the expected behavior?
Users who aren't subscribed are prompted to sign up when they try to upload files to storage.

### What is the actual behavior?
If they upload from within a template, an ambiguous error appears.

### What steps can be taken to replicate the problem?
From a company with no subscription, try creating a presentation from a template and uploading an image.
The actual behavior seems to be inconsistent, see this video:
https://drive.google.com/file/d/1pzYC-NVoxwpoO6isSpk2OUvRgOLb6M2V/view?usp=drivesdk

Sometimes it just works and uploads without issue, sometimes it throws the error.  Neither is the expected behavior in this scenario.

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision this issue has been corrected. We will now show the prompt to subscribe when clicking the Upload or Canva buttons in the Template Editor. Closing. Thanks!
