### ISSUE TITLE
Text is cut off in preview and on Display, despite having the space to show

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#263]
<b>How it works now:</b>
1. Preview <a href="https://apps.risevision.com/editor/workspace/1b0a9343-4275-4018-9ae9-cb73e1b96443/?cid=556323b8-984c-4127-aa08-4d73d019bcb8">this Presentation</a>, and notice that for some people the text in Placeholder <b>Feature_Desc</b> shows as expected for some users, but not others. For @alanclayton it showed fine, on my preview, it was cut off.

2. Play that presentation on a Display, and notice that the text is cut off, instead of going to the next line:
![2016-10-04_10-31-23](https://cloud.githubusercontent.com/assets/6862256/19078323/c08e92c0-8a1d-11e6-9b1e-64fd731539a7.png)

<b>How it should work:</b>
Since there is enough space to show the text, it should show the text entirely.

**Comment by alanclayton** [comment]
@robb-price should content look at this first? And to confirm, you get the same thing when running on a Display?

@ezequielc  @rodrigopavezi @donnapep @stulees FYI

**Comment by robb-price** [comment]
@alanclayton Yes, I get this when running on both a Windows and Linux Display.

@ezequielc @rodrigopavezi @donnapep @stulees FYI.

**Comment by robb-price** [comment]
@alanclayton @alex-deaconu @ezequielc Any update on this?

**Comment by alanclayton** [comment]
@robb-price see card here https://trello.com/c/A9PRkWca/2004-issue-263-text-is-cut-off-in-preview-and-on-display-despite-having-the-space-to-show-1

**Comment by donnapep** [comment]
@robb-price This was fixed in the Spreadsheet Widget.
