### ISSUE TITLE
Files are not overwriting in Storage when you upload one with the same name

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#264]
<b>How it works now:</b>
1. Take a jpg image file and upload it to Storage.
2. Take another jpg image file, rename it the same as the first image, and upload it, to replace the original.
3. Notice that it does not overwrite the original, instead it adds another image. Looking at the thumbnails, they appear as the same image.

For further clarification: https://goo.gl/f5CnuA

<b>How it should work:</b>
The file should be overwritten with the  newly uploaded version.

**Comment by robb-price** [comment]
@ezequielc @alex-deaconu Any update on this issue?

**Comment by ezequielc** [comment]
@robb-price This is fixed. Could you confirm? Thanks!

**Comment by robb-price** [comment]
@ezequielc Verified. Thanks!
