### ISSUE TITLE
"Aw Snap!" when viewing schedules and displays under some conditions

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2644]
### What is the expected behavior?
Navigation of the app is not interrupted.  Users can view their displays, and change or view their schedules from the schedule drop-down, then make changes to the schedule as needed from the schedule.

### What is the actual behavior?
Under some conditions that aren't really clear as of now an error appears when navigating schedules and displays indicating that Chrome as crashed.

![image](https://user-images.githubusercontent.com/40774237/121054035-562eea80-c792-11eb-9194-0cf0bc96d50c.png)

Console crashes without logging anything at the time of the crash but consistently shows this message immediately before the crash.  It's worth noting sometimes this message appears without a crash so it isn't clear if the two are related.

`Exception - WidgetController.setReady DOMException: Blocked a frame with origin "https://widgets.risevision.com" from accessing a cross-origin frame.
    at Function.f.sendReadyToPlayer (https://widgets.risevision.com/viewer/dist/viewer.js:77:150129)
    at Object.h.setReady (https://widgets.risevision.com/viewer/dist/viewer.js:77:149467)
    at window.reportReadyEvent (https://widgets.risevision.com/viewer/dist/viewer.js:77:132362)
    at window.itemReady (https://widgets.risevision.com/viewer/dist/viewer.js:77:258262) undefined`

I've been able to replicate it really consistently with 2 specific customer displays and schedules.  I haven't had any luck replicating this with my own company so I suspect it's something related to the schedule.

### What steps can be taken to replicate the problem?
Go to one of the two affected schedules.  Try to navigate around the app, like clicking "Displays" and then viewing the display's schedule.

Video: https://drive.google.com/file/d/1iT4u4ey2Bm3N6oU5N-J_7vVCV4fOuenR/view?usp=drivesdk

**Comment by ezequielc** [comment]
@PatrickA-RiseVision Is this something you have seen before or only started happening recently? I am just wondering if this should be considered for escalation. 

@santiagonoguez @alanclayton Given the error message comes from Viewer and the error happens on pages where we have embedded shared schedule, I am wondering if you should take this. Thanks!

**Comment by santiagonoguez** [comment]
@ezequielc at first sight, could be that some browser resource ( memory, open files ) could be filling.

https://superuser.com/questions/607563/how-to-determine-what-is-causing-chrome-to-show-the-aw-snap-dialogue

I don't think the CORS message above is related, and could be Viewer related or not. The schedule contains three legacy presentations that at first don't look that contain elements that could complicate things. So I'm not also sure who should own this. Thoughts @alanclayton ?

**Comment by alanclayton** [comment]
@santiagoarriaga I think it is best for you to coordinate directly with @ezequielc and @stulees to confirm ownership. Can you do that and let me know conclusion? Thanks

**Comment by santiagonoguez** [comment]
@alanclayton I talked with @ezequielc, and as Viewer is the most likely culprit, Delivery will take it. We don't think this should be escalated as it doesn't happen right away, and the error gets usually corrected by reloading the page, thanks !

**Comment by alanclayton** [comment]
@santiagoarriaga how many users are experiencing this?

**Comment by santiagonoguez** [comment]
The defect description mentions 2 customers, @PatrickA-RiseVision  have this been reported for more ?

**Comment by PatrickA-RiseVision** [comment]
@santiagoarriaga so far only 1 customer reported the issue.  The other I came across by happenstance while troubleshooting something unrelated; the customer hasn't brought it up.  I can only replicate it with these 2 schedules.  Kaden can also replicate it.

**Comment by robb-price** [comment]
@santiagoarriaga I spoke to Patrick and Kaden about this, and they are confident that we can close this bug.

**Comment by santiagonoguez** [comment]
@robb-price great, thanks !
