### ISSUE TITLE
Account and Billing page does not show the discounted subscription total for education and non profit companies

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#2658]
### What is the expected behavior?
The total that shows on the Account and Billing page, as well as when you click on the subscription from that page, should show the total including the discount, so users know the total of their subscription.

### What is the actual behavior?
Regardless if you have the 10% discount, the Account and Billing page shows the amount before the discount

### What steps can be taken to replicate the problem?
1. Set up a subscription with the 10% education / non profit discount.
2. Go to the Account and Billing page, and look at the subscription. It does not include the discount.

**Comment by alex-deaconu** [comment]
@robb-price a few fixes were applied for this. However, I want to start with an explanation for this issue. Responses from the Chargebee Subscription apis, list and individual, we always get a Plan Amount value. This is how much the plan is worth, excluding discounts, taxes, etc. Any final amounts that include taxes/discounts/etc have to be calculated via Estimate APIs.

So, we have updated the column name on the Billing page, as well as the heading on the Subscription page to say `Plan Amount`. In addition, on the Subscription page we have added an extra field `Next Payment` which contains the calculated amount due for their next invoice.

This should hopefully resolve any confusion for this. Closing. Thanks!
