### ISSUE TITLE
Existing URL playlist items requiring "Remove Validation" cannot be edited directly

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-vision-apps#2670]
**Expected behavior**
Users are able to edit all playlist items in a given schedule

**Actual behavior**
Existing URL items in a schedule playlist requiring "Remove Validation" do not allow for editing. The Apply button remains greyed out until you remove the URL, re-add it, and re-check the "Remove Validation" box.

**Steps to reproduce**
Watch [this video](https://drive.google.com/file/d/1xgUecgjHVDoj7Jbay6OxPAcVbksraGLi/view?usp=sharing)

**Comment by alex-deaconu** [comment]
@kaden-rise this issue should now be fixed. To confirm, if you open an item and make changes to any other field, you will not have to select "Remove Validation". However, if you do modify the URL it will re-validate it and you will have to check it off again. Closing. Thanks!
