### ISSUE TITLE
Incorrect widget loaded in apps-stage-0

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-vision-apps#2707]
When an image widget is added to a new blank presentation on apps-stage-0, the html view shows:

```
"objectData": "http://s3.amazonaws.com/widget-image-test/stage-1-dev/0.1.1/dist/widget.html",
```

This is not the correct path; widget-image-test should not be used.

**Comment by alex-deaconu** [comment]
@tejohnso this needs to be updated here: https://rva-test.appspot.com/#/GADGET_MANAGE/id=2707fc05-5051-4d7b-bcde-01fafd6eaa5e?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443. Thanks.

**Comment by tejohnso** [comment]
@stulees Can you make the required change there so that it points to the correct widget instance?

**Comment by stulees** [comment]
@tejohnso Done, thanks

**Comment by ezequielc** [comment]
Thanks, I will close this.
