### ISSUE TITLE
Images with specific naming conventions are not accessible in Storage in specific Company.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#271]
<b>How it works now:</b>
Notice that <a href="https://storage.googleapis.com/risemedialibrary-db379866-50f2-455f-af08-51dc023ef987/Chrome/1247-000_FINAL%20copy.jpg"><b>1247-000_FINAL Copy.jpg</b></a> does not work in a Presentation, or via the Storage URL, while <a href="https://storage.googleapis.com/risemedialibrary-db379866-50f2-455f-af08-51dc023ef987/Chrome/1247-000_FINAL.jpg"><b>1247-000_FINAL.jpg</b></a> works no problem.

Also, 4796-DJL. Shine.jpg won't work, but 4796-DJL_Shine.jpg will work.

I can't recreate this in Storage now, I can only create it using these files in their Company. I'm not sure if this is affecting anyone else.

https://community.risevision.com/rise_vision_inc/topics/images-loading-as-blank-white-screen

**Comment by ezequielc** [comment]
@robb-price I could not replicate this as well. They do have some other files that contains space in the name (like [cardiology tv graphic 2-4-16.jpg](https://storage.googleapis.com/risemedialibrary-db379866-50f2-455f-af08-51dc023ef987/Chrome/cardiology%20tv%20graphic%202-4-16.jpg)) and they work. The message we receive (Access Denied) is the same we get for a file that is trashed. It might have been an expected condition when restoring these files. I tried to do that, but I could not replicate the issue.
As it looks like they found a workaround and no one else is being affected, I would suggest to close the issue. Thoughts? Thanks

**Comment by robb-price** [comment]
@ezequielc Agreed. Let's close.
