### ISSUE TITLE
Displays will take up to 1 hour to reflect the settings of the Media Player using that Display ID

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#283]
<b>How it works now:</b>
1. Create a new Display at https://apps-stage-0.risevision.com, and get a Display ID.
2. Use that Display ID on a media player for the first time.
3. Notice that the Presentation assigned to that Display ID starts playing on the media player, however the UI still shows that it is not installed.
4. Similarly, if you have a Display in the UI that was using a different OS, Player Version, etc, it will not update when use that Display ID on a new media player.

For further clarification: https://goo.gl/6Dg40N

<b>How it should work:</b>
Once you start using that Display ID on a Display, you should see all the settings for that media player and Player version listed in the Display Settings.

**Comment by ezequielc** [comment]
@robb-price We increased the frequency of our job to check the display installation from every 45 minutes to 5 minutes. Also, we implemented some logic in the UI to avoid showing as not installed a display that is online. Cheers!

@fjvallarino fyi, make sure we always close the issue report after implementing the fix. Cheers!
