### ISSUE TITLE
Displays intermittently can't update or show display screenshot

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2839]
### What is the expected behavior?
Displays update automatically when changes to the schedule are saved, or changes to presentations in the schedule are published.
Update Display Screenshot button in Display Settings takes a current screenshot to display

### What is the actual behavior?
Sometimes, content won't update at all for periods of 10-15 minutes.  It seems to go away on its own eventually.
During that time, Display Screenshot doesn't seem to work.  Clicking "Update Display Screenshot" returns a grey screen with an error.

### What steps can be taken to replicate the problem?
Unknown, but I have example display IDs I can share.

**Comment by tejohnso** [comment]
Closing per fix above. @PatrickA-RiseVision feel free to reopen if necessary.
