### ISSUE TITLE
Drag and Drop doesn't work for some presentations.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#2843]
### What is the expected behavior?
When you drag and drop the items in a presentation playlist, they should go into that order.

### What is the actual behavior?
Dragging and dropping does not appear to follow where you want the items to be dragged to.

### What steps can be taken to replicate the problem?
This is a tough one to verbalize, so this video shows it occurring:
https://drive.google.com/file/d/12yO2uJIouG7NN32pMdOEtjje9Jy10c5L/view?usp=drivesdk

**Comment by sheadarlison** [comment]
@robb-price @ezequielc I had another customer report this today. Thanks!

**Comment by sheadarlison** [comment]
I also tested in Chrome/Firefox and it's happening in both

**Comment by alex-deaconu** [comment]
@robb-price @sheadarlison @ezequielc a fix has been released for this. Closing. Thanks.
