### ISSUE TITLE
All playlist items in the Playlist template are called literally "Playlist Item" when being edited

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2863]
### What is the expected behavior from the user’s point of view? 
I can tell what I'm editing because the name of the content is identified.

### What is the actual behavior from the user’s point of view? 
When I click on the duration of a playlist item in the playlist template, the item I'm editing is named "Playlist Item" which does not make it clear what I'm changing.

![image](https://user-images.githubusercontent.com/40774237/130276117-6b36f1df-8d19-482b-b03f-0e711c2f77ae.png)

### What steps can be taken to reproduce the actual behavior?
1. Create a presentation from a Playlist template
2. Add content to the playlist component.
3. Click on the duration to edit it.
4. The item is now called "Playlist Item".

**Comment by alex-deaconu** [comment]
@PatrickA-RiseVision a correction for this has been deployed. When opening the Settings, the name of the item as it appears in the playlist list will show. Closing. Thanks!
