### ISSUE TITLE
Persistent 'Hover' state on Common Header

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-vision-apps#293]
Reproduction Steps:
1. Navigate to any Apps subsection via Common header from apps.risevison.com

Expected Results :
Nav highlights current App location to User

Actual Results :
Hover state is persistent, but disappears when any spot on the screen is clicked (leaving the User with no info as to current App location).

Please see video capture in Zip file:
[bug2.m4v.zip](https://github.com/Rise-Vision/rise-vision-apps/files/649292/bug2.m4v.zip)

**Comment by alex-deaconu** [comment]
@RV-Adrian @ghislaineguerin double checked and the correct class is being applied to the menu item (`selected`) however the colour difference is so subtle that it's not noticeable:
`#020621` for unselected
`#444` for selected

This needs to be fixed in common-styles.

Thanks!

**Comment by ghislaineguerin** [comment]
@alex-deaconu I know this problem. I can fix it.

**Comment by ezequielc** [comment]
@RV-Adrian This issue is fixed. Please remember to close the issue before moving the card to Done. Cheers!
