### ISSUE TITLE
Can't download from storage

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#297]
**What is currently happening:**
When I try to download the interactive-display folder from this account https://apps.risevision.com/storage?cid=7d6d3f23-4914-4ac3-9163-9d905cf29c3c the download seems to time out.

**What is expected to work:**
I can download the folder as a zip

**What has been tried so far:**
Refreshing the page, opening a new Storage window, hard reloading and clearing cache, clicking download repeatedly

![storage-issue](https://cloud.githubusercontent.com/assets/9273546/21399102/27c3a182-c778-11e6-8e38-85595aea37f2.gif)

**Comment by ezequielc** [comment]
@sheadarlison We can't replicate the issue anymore. We worked on some improvements on Storage and maybe it was fixed by that. Let us know if you can still have the issue and we can reopen it. Thanks
