### ISSUE TITLE
User Status box is blank

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#301]
<b>How it works now:</b>
For any user, look at their account in the Company Users - Users Settings Window. Notice that the User Status is blank:
![2017-01-06_13-22-20](https://cloud.githubusercontent.com/assets/6862256/21728495/800e308e-d414-11e6-8e9b-f76df1a45044.png)

<b>How it should work</b>
This should show the current status of the user.

**Comment by ezequielc** [comment]
@robb-price A fix was released. Could you confirm it is working? Thanks

**Comment by robb-price** [comment]
@ezequielc Fix is confirmed. Verified and closed.
