### ISSUE TITLE
'Sign Up' panel is misaligned

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-vision-apps#303]
The Problem:
Image size throws text out of alignment.

![image](https://cloud.githubusercontent.com/assets/11826611/21850717/ee7db9d6-d7d9-11e6-94ce-e92433cf35b0.png)

Solution: Provide proper image so text is aligned.

**Comment by ezequielc** [comment]
@RV-Adrian This is closed now, right? Thanks

**Comment by RV-Adrian** [comment]
@ezequielc Right! Closing now
