### ISSUE TITLE
Content appears duplicated on placeholder name change

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-vision-apps#308]
When changing the name of a placeholder which already has content in it, e.g. text or image, the content will be duplicated below the placeholder and can obscure other content.

### Steps to reproduce:

1. Add a new placeholder;
2. Add a text widget and add some content;
3. Change the name of the placeholder and save the change;
4. The content is then duplicated below the original placeholder;
5. For text content, if you go to change the text it will show as changed in the duplicate text but not in the original until the presentation is saved.

<img width="463" alt="screen shot 2017-01-19 at 9 52 29 am" src="https://cloud.githubusercontent.com/assets/8008948/22111961/4cc54396-de2f-11e6-8dce-0b50c3d3f2b7.png">

The duplicated content will clear on save/save & preview however a name change should be possible without the duplication showing up.

**Comment by checcoux** [comment]
![schermata del 2017-02-02 09-25-31](https://cloud.githubusercontent.com/assets/15678527/22541943/bde42984-e929-11e6-87a0-88d53b5f056e.png)
Not only with text but also with images

**Comment by fjvallarino** [comment]
@pcsandford this has just been deployed. Please validate and, if it looks correct, close the issue! Thanks!

**Comment by pcsandford** [comment]
@fjvallarino tested and validated with text and image. Looks good, thanks!
