### ISSUE TITLE
Schedules App: When a Display is selected in a Schedule, no checkmark appears.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#310]
**How to recreate**
1. Select a Schedule from schedules.risevision.com
2. Click the Displays Selected to edit Display distribution
3. Click a Display to select it

**What happens**
When a Display is clicked, it is only highlighted in a slightly darker grey, there is no checkbox next to the Display. Also, when Displays are already selected, the same issue occurs.

**What should happen**
The checkbox next to the Display should fill.

![schedulesdefect](https://cloud.githubusercontent.com/assets/8458926/22123291/bc37453c-de50-11e6-97c3-4c2f07c88836.png)

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Issue 310: No checkmark appears when checking Displays in Distribution](https://trello.com/c/xDH6outy/3037-1-issue-310-no-checkmark-appears-when-checking-displays-in-distribution)

**Comment by RV-Adrian** [comment]
@robb-price @btfrise 
This is now fix and deployed, please confirm on http://apps.risevision.com
Thanks!

**Comment by btfrise** [comment]
@RV-Adrian Looks good!
