### ISSUE TITLE
signup or login with google account

### ISSUE THREAD

**Issue by kevintd** [Rise-Vision/rise-vision-apps#315]
HI, 

Firstly, thank you for your contribution. I clone this source and try to run it. But i catch an issue about login or signup with google account, it always gets the error: respond 400. Error invalid_request redirect_uri not supported for response_type=token:

Can anyone help me?

**Comment by ezequielc** [comment]
Hi @kevintd ,
just to confirm so I don't duplicate work, are you the same person from this post in our community?
https://community.risevision.com/rise_vision_inc/topics/new-developer-needs-a-little-help

If not, could you provide a console log output so I can have more details? 

Thank you!

**Comment by kevintd** [comment]
Thank @ezequielc for your response,
Yep, it's so difference, my issue here is how to use OAuth2.0 to pass the Login/signup screen (i ran this project on localhost)

![image](https://cloud.githubusercontent.com/assets/4203786/22280321/3d6e9b66-e313-11e6-9cc7-6ed2f9a6eb18.png)
Your sincerely,

**Comment by ezequielc** [comment]
@kevintd If you run as http://localhost:8000/ instead of your IP, does it work?

You might need to set your own CLIENT_ID in each environment:
https://github.com/Rise-Vision/rise-vision-apps/tree/master/web/scripts/config

.value("CLIENT_ID", "614513768474.apps.googleusercontent.com");

And also register the App, same as described in the [community post](https://community.risevision.com/rise_vision_inc/topics/new-developer-needs-a-little-help)

Cheers!

**Comment by kevintd** [comment]
my project works on ubuntu server with address 192.168.0.43
and i already registered Key, then edit config.js like that
angular.module('risevision.apps.config', [])
    .value("CLIENT_ID", "769921019097-ue34bgh5fqga0iddhkc8cjjplj6is811.apps.googleusercontent.com")
    .value('APPS_URL', 'http://192.168.0.43:8000')

but it still have same issue, can you help me?

Thank u so much,

**Comment by ezequielc** [comment]
@kevintd I assume you can't check localhost then.
I can't confirm from your logs but I guess you are hitting our test server, so I would also add to config.js:
`.value("CORE_URL", "https://rvaserver2.appspot.com/_ah/api")`

Make sure your requests are not going to https://rvacore-test.appspot.com/.

Thanks!

**Comment by ezequielc** [comment]
@kevintd I am closing the issue as I didn't hear from you. Feel free to open it again if necessary. Thanks!
