### ISSUE TITLE
Storage Issues

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#322]
**What is not working/What is currently happening:**
When your account is suspended you can't switch between list and tile view

**What is expected to work/What is the client expecting:**
You can switch between list and tile view

**What has been tried so far:**
Nothing

See buttons are greyed out below:

![screen shot 2017-02-02 at 9 51 52 am](https://cloud.githubusercontent.com/assets/9273546/22554780/61fd8006-e92f-11e6-92a9-6514d362a9f8.png)

**Comment by alex-deaconu** [comment]
@sheadarlison a fix for this issue has been deployed. Please verify and close. Thanks!
