### ISSUE TITLE
Can't copy DisplayID from Display Settings page

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-vision-apps#323]
Copying display ID's from the Display Settings page is a common function in Support to avoid having to manually type IDs.

Something changed recently where the table data that includes display id can no longer be copied.

**Comment by RV-Adrian** [comment]
@alanclayton Issue is fixed and deployed, please confirm if ok? Thanks!

**Comment by alanclayton** [comment]
@RV-Adrian Looks good. Thanks
