### ISSUE TITLE
Schedule Name field is misaligned

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-vision-apps#332]
The Problem: Schedule Name field is misaligned under Display Details
The Solution: Update to utility name class call

![image](https://cloud.githubusercontent.com/assets/11826611/22940137/ed22a6c4-f2ae-11e6-8b54-fbf539d6c071.png)

**Comment by RV-Adrian** [comment]
@alex-deaconu @ezequielc @fjvallarino 
Fix is deployed, please validate. Thanks!

**Comment by ezequielc** [comment]
@RV-Adrian Confirmed it is fixed. Thanks!
