### ISSUE TITLE
Placeholder List items have incorrect padding

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-vision-apps#333]
The Problem: Placeholder List items have incorrect padding
The solution: Update the .editor-playlist-item class in Common Style

![image](https://cloud.githubusercontent.com/assets/11826611/22940233/3478ca58-f2af-11e6-972d-a7a662c3297a.png)

**Comment by RV-Adrian** [comment]
@alex-deaconu @ezequielc @fjvallarino 
Fix is deployed, please validate. Thanks!

**Comment by ezequielc** [comment]
@RV-Adrian Validated. Thanks for fixing it.
