### ISSUE TITLE
User List is missing panel class

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-vision-apps#336]
The Problem: User List from the Common-Header dropdown is missing a .panel and .panel-default class call
The Solution: Add these classes the the .scrollable-list DOM element

![image](https://cloud.githubusercontent.com/assets/11826611/23002201/6e51cc9e-f3b7-11e6-8d84-430da8098d5d.png)

**Comment by alex-deaconu** [comment]
@RV-Adrian this issue should now be resolved. Please verify and close. Thanks!

**Comment by RV-Adrian** [comment]
@alex-deaconu Verified, thanks 👍
