### ISSUE TITLE
Presentation changes are not staying saved.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#346]
<b>How it works now:</b>
1. Add or remove a Widget from a Presentation.
2. Save that Presentation, and go back to that Placeholder. Notice that the item you removed or added has not been saved successfully.

For further clarification: https://goo.gl/bbnRqo

<b>How it should work:</b>
Any changes you make to a Presentation that you save need to remain in the Presentation.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Issue 346: Presentation Changes are not staying saved.](https://trello.com/c/I0RYKs43/3417-1-issue-346-presentation-changes-are-not-staying-saved)

**Comment by RV-Adrian** [comment]
@robb-price Looks resolved, can you close? Thanks!

**Comment by ezequielc** [comment]
@robb-price This was escalated and fixed. I am closing it. Thanks!
