### ISSUE TITLE
App Empty States are misaligned/not functional

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-vision-apps#350]
The Problem:
Alignment issues, and one appears as a link that leads nowhere:
![image](https://cloud.githubusercontent.com/assets/11826611/23613277/cae55798-024c-11e7-8736-45a2c124b053.png)

The Solution:
Update rise-vision-apps (and possibly Common Style) to sync, and remove HREF tags.

**Comment by ezequielc** [comment]
@RV-Adrian I think we are good to close this one. Thanks!

**Comment by RV-Adrian** [comment]
@ezequielc Thanks
