### ISSUE TITLE
Update the error message that appears when a user tries to add a duplicate user.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#353]
<b>How it works now:</b>
If you try to add a user, and that user already exists, the error message simply says, "Error: User already exists."

<b>How it should work:</b>
When a duplicate user is added, it should say this:
![2017-03-06_22-16-56](https://cloud.githubusercontent.com/assets/6862256/23640287/a78cc2d6-02ba-11e7-919f-ae7a8a378f45.png)

@ezequielc FYI. Thanks!

**Comment by alex-deaconu** [comment]
@robb-price we've implemented this in the Common Header and deployed to Apps and RVA. Can you verify and close if acceptable? Thanks!

**Comment by ezequielc** [comment]
@robb-price I am closing this as it was deployed. Thanks!
