### ISSUE TITLE
Editor app does not acknowledge saved image widget change

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-vision-apps#373]
1. Configure an image widget within a placeholder
2. Edit the image and save changes

Expected:  The placeholder shows the updated file name for the new image
Observed:  The placeholder shows the original file name as though the image has not been changed.  

**[VIDEO](https://drive.google.com/file/d/0B_fkyfbDITdiRTZXSnFDMjBzbFk/view?usp=sharing)**

**Comment by ezequielc** [comment]
@tejohnso  Thanks. I saw some layout issues in your video as well. What browser are you using? Cheer!

**Comment by tejohnso** [comment]
@ezequielc I'm using 64bit Chromium 57.0.2987.110 on Linux

**Comment by ezequielc** [comment]
@tejohnso Thanks!

**Comment by ezequielc** [comment]
@tejohnso A fix has been deployed. Let us know if you still have the issue. Thanks!
