### ISSUE TITLE
Create Folder does not focus on the Name field

### ISSUE THREAD

**Issue by fjvallarino** [Rise-Vision/rise-vision-apps#385]
When opening the Create Folder popup, focus should be on the Name text field. This happens correctly the first time the window is opened, but not on subsequent calls.

Rename popup does not have this issue.

**Comment by alex-deaconu** [comment]
@fjvallarino this issue has now been corrected. Please verify and close. Thanks!

**Comment by fjvallarino** [comment]
@alex-deaconu looks good!
