### ISSUE TITLE
Add to schedule button doesn't do anything

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-vision-apps#386]
1.  Create a new display with no schedule

2.  Click Add To Schedule

[VIDEO](https://drive.google.com/file/d/0B_fkyfbDITdiWmlmbWFnbWR6VGs/view?usp=sharing)

**Comment by alex-deaconu** [comment]
@tejohnso this issue has now been fixed. Please verify and close. Thanks!
