### ISSUE TITLE
Can't Create a Folder

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#391]
###What is happening 
I am in a sub company and was able to create a folder in their storage, after creating the first folder I attempt to create a second folder and get the below error.

https://apps.risevision.com/storage?cid=86668660-4ab1-4e1b-8982-dc334b38b3bf

<img width="1280" alt="screen shot 2017-04-11 at 11 42 45 am" src="https://cloud.githubusercontent.com/assets/9273546/24917734/18cc23a8-1eac-11e7-8ef1-79386cfbfa4d.png">

###What should happen
I am able to create multiple folders in a sub company.

###What has been tried so far
Nothing yet. 

Let me know if you have questions.

**Comment by ezequielc** [comment]
@sheadarlison We could not replicate the issue. I watched fullstory session and repeated the same steps but the error did not appear. Are you capable of replicating the issue? If not, I think we can close the issue. Thanks!

**Comment by sheadarlison** [comment]
@ezequielc I haven't been able to reliably replicate the issue but, this is not the first time I've seen this happen. I think there is a bug, but I'm fine closing the issue until we can reliably replicate. 

Thanks
