### ISSUE TITLE
Sort in Storage is broken

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#403]
Problem: 
You can only sort by name in Storage and the arrow stays on all the column header instead of disappearing when you try to sort a different column.

How it should work: 
You can sort by any column 

Video: 
https://www.screencast.com/t/h7AzEs0Zw8Ss

**Comment by alex-deaconu** [comment]
@sheadarlison great find! Issue should be fixed now, please verify and close if acceptable. Thanks!

**Comment by sheadarlison** [comment]
Looks good, thanks @alex-deaconu
