### ISSUE TITLE
Display status icon color bug

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-vision-apps#42]
Status icons turn blue in Displays list on hover. (no meaning to it)

Something like the following could be included in Common Style to fix:
#displaysListTable .table-2>tbody>tr:hover.clickable-row td, .table-2>tbody>tr:hover>td a {
color: #555;
}

**Comment by ByronDarlison** [comment]
@RV-Adrian I believe this is now fixed. Can you review and confirm? Thanks

**Comment by RV-Adrian** [comment]
@ByronDarlison This is still an active issue. Not an especially tough fix, let's tackle it this Sprint.

**Comment by ByronDarlison** [comment]
Okay. Opening card from that checklist now @RV-Adrian

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ioWjLbEj&#x2F;1127-https-github-com-rise-vision-rise-vision-apps-issues-42"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> https:&#x2F;&#x2F;github.com&#x2F;Rise-Vision&#x2F;rise-vision-apps&#x2F;issues&#x2F;42</a>

**Comment by alex-deaconu** [comment]
This has been fixed. Closing. Thanks.
