### ISSUE TITLE
A placeholder can be "distributed" to a display that is not scheduled

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-vision-apps#425]
Not sure if this is a bug but I thought I'd mention it.  

![distribution](https://cloud.githubusercontent.com/assets/1511535/26003749/930b811e-3701-11e7-9118-b7ff2efb1696.png)

The presentation editor will allow a placeholder to be distributed to any display in the company, even if that display is not scheduled for the presentation.   I'm not sure what it means to distribute a placeholder like that.  I'm guessing the display isn't going to show it.  Where would it show it, if the presentation isn't even scheduled on that display?  It seems the dialog should either only show displays that have the presentation scheduled, or show them all, but then display a warning if an unscheduled display is selected so that the user knows that placeholder isn't going to be shown on the display unless the presentation is scheduled for that display.

**Comment by ezequielc** [comment]
@tejohnso Thanks for bringing this up. We talked about it and we don't have a clear definition on how we should solve it. It relates to showing schedules in the Display list. But as it is not an actual issue, we will keep it in our backlog and pursue it at a later point. If you agree with that, I think we can close the issue. Thanks

**Comment by tejohnso** [comment]
:+1:
