### ISSUE TITLE
Failed to add display [object Object]

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-vision-apps#448]
I ran across 
![this error](https://user-images.githubusercontent.com/1511535/28541866-86f14e7a-7088-11e7-87ba-191552567371.png) while trying to add a display.

**Comment by fjvallarino** [comment]
@tejohnso this has just been deployed. Could you validate it? Thanks!

**Comment by tejohnso** [comment]
@fjvallarino I don't get the error anymore :+1:
