### ISSUE TITLE
If you change a Placeholder from an RGB color to transparent, it switches back to the color after you press Save.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#45]
<b>How it works how:</b>
1. Set the Placeholder color on a Placeholder, notice the Placeholder color changes. Save the Presentation. Notice the color is saved.
2. Set the Placeholder color to transparent by deleting the entire RGB Code, notice the Placeholder goes transparent. Save the Presentation, notice the previous color of the Placeholder returns.

For further clarification: https://goo.gl/kJSrSM

<b>How it should work:</b>
Once you set the Placeholder to transparent, it should stay that way after saving the Presentation.

**Comment by robb-price** [comment]
@ByronDarlison @ezequielc FYI.

**Comment by alex-deaconu** [comment]
Note: This issue also occurs with Presentation Backgrounds.

@robb-price FYI this is now fixed. Please verify.

Thanks!

**Comment by robb-price** [comment]
@alex-deaconu Verified and Closed.
