### ISSUE TITLE
Cannot add a placeholder

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-vision-apps#468]
When I click add presentation and choose the blank template, the left column with the placeholder action is not visible and the tooltip is only partially visible.  See [recording](https://drive.google.com/file/d/0B_fkyfbDITdiN29YUm1xUlVfSUE/view?usp=sharing).

**Comment by ezequielc** [comment]
@tejohnso We could not replicate the issue. I am wondering if it could be a styling cache issue. Do you see the error in incognito mode? Thanks

**Comment by tejohnso** [comment]
I can't replicate the issue anymore either.
