### ISSUE TITLE
Onboarding flow remains when user signs out

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-vision-apps#474]
![image](https://user-images.githubusercontent.com/11826611/30024384-8b970b3e-9141-11e7-96a5-4075b92cf1b8.png)

1. Sign In
2. Observe onboarding steps
3. Sign Out
4. Steps remain on Sign Up/In page

**Comment by fjvallarino** [comment]
@RV-Adrian this has just been deployed. Could you check and close the issue if it works as expected? Thanks!

**Comment by ezequielc** [comment]
@RV-Adrian I am closing this issue. You can reopen it if you still find the issue. Thanks
