### ISSUE TITLE
When there many items in the Placeholder, you cannot see the very last item.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#482]
<b>How it works now:</b>
Using <a href="https://apps.risevision.com/editor/workspace/9f8c0dfa-b208-42a4-b4fd-bcf49a0302ae/?cid=556323b8-984c-4127-aa08-4d73d019bcb8">this Presentation</a>, you can see there are 41 items in the main Placeholder. Notice that you cannot see the last item in the Placeholder's Playlist.

For further clarification: https://goo.gl/WiXt1P

<b>How it should work</b>
regardless of how many items are in the Placeholder's Playlist, you should be able to see them all.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Issue 482: Can't see last item in a Placeholder when there are lots of items.](https://trello.com/c/M6FWxyug/5912-1-issue-482-cant-see-last-item-in-a-placeholder-when-there-are-lots-of-items)

**Comment by RV-Adrian** [comment]
@robb-price 
Fix is now deployed to apps.risevision.com
Can you confirm on your side? Thanks!

**Comment by robb-price** [comment]
@RV-Adrian Confirmed!
