### ISSUE TITLE
Padding appears on HTML Widget upon Preview if the width/height settings are in the Presentation's full resolution

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-vision-apps#49]
**How it works now:**
1. Create an embedded HTML Widget item in a 1920x1080 Placeholder in a Presentation that is 1920x1080. 
2. Change the background color of the Placeholder to any non white color. Use <a href=http://rva.risevision.com/#/PRESENTATION_MANAGE/id=29863655-9fc0-4824-b1ef-977cec204eb7?cid=960b72df-9af7-476b-8a47-b67ded4c779d">this Presentation</a> as an example. Notice the padding between the viewer border and the embedded item in the HTML Widget.  

FYI, this does not occur with the Web Page Widget. See <a href="http://rva.risevision.com/#/PRESENTATION_MANAGE/id=86842a59-56fa-4a1e-a4b7-5e06bcff28a4?cid=960b72df-9af7-476b-8a47-b67ded4c779d
">this Presentation</a> example using the Web Page Widget. 

This happens in both Classic and New Editor.

**How it should work:**
As a user, when I embed a HTML Widget in a 1920x1080 Placeholder in a 1920x1080 Presentation, I expect that the Widget will occupy the entire presentation space.

Sent via Community https://community.risevision.com/rise_vision_inc/topics/8px-margin-in-html-widget

Let me know if there is anything further for this.

**Comment by ByronDarlison** [comment]
@hcs0 @alanclayton is this a apps defect or a problem with the html widget? This sounds like it belongs to the widget? @alex-deaconu @ezequielc any thoughts? Thanks

**Comment by hcs0** [comment]
@ByronDarlison This is a defect in the HTML widget and it still exists within RVA and the new Editor.  Will close this and add in that repo.
