### ISSUE TITLE
When you are signed into one Editor, when you open the other one, you need to sign in again.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#499]
<b>How it works now:</b>
If you are working in the classic editor and need to look at Displays or need something from Storage, and you select that from the Common Header, you need to sign in again.

This video shows what I mean: https://goo.gl/6CFWoc

<b>How it should work</b>
When you sign into one Editor, it should sign into both, or better yet, explain why you need to log into the other one if you open it up in a separate window. 

FYI 4 users have brought this up today, so we know that users are being affected by it.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Issue 499 - When you sign into one Editor and open something in the other editor, you need to sign in again](https://trello.com/c/3TkruL1A/6218-1-issue-499-when-you-sign-into-one-editor-and-open-something-in-the-other-editor-you-need-to-sign-in-again)

**Comment by robb-price** [comment]
Users are also reporting when they need to go edit a Presentation in the classic editor, they just get a white screen. They are getting this because they need to log into the classic editor. This explains the process; https://goo.gl/DfF9BC

**Comment by alex-deaconu** [comment]
@robb-price this issue should be fixed with the latest RVA deployment. Please re-open if you still encounter it. Thanks!
