### ISSUE TITLE
First Name and Last Name fields aren't populated 

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-vision-apps#502]
After entering 'First Name' and 'Last Name' data in the fields of the registration popup, they are not followed to 'User Settings'.  

See video for reference: https://drive.google.com/a/risevision.com/file/d/13ehSmaUh6GkzPr274RGumIu3HkYXhHPn/view?usp=sharing

**Comment by alex-deaconu** [comment]
Fixed by https://github.com/Rise-Vision/hubspot-connector/pull/37. @RV-Adrian I was no longer able to replicate. Please re-open if you are. Thanks!

**Comment by RV-Adrian** [comment]
@alex-deaconu Will do, thanks!
