### ISSUE TITLE
If you leave https://apps.risevision.com logged in for 24 hours, it will ask you to complete your registration again

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#520]
<b>How it works now:</b>
1. Log into https://apps.risevision.com, and leave the page open for 24 hours.
2. When you try to edit some content after 24 hours, it will take you to the registration screen again, giving you the impression you have not completed registration.
3. If you try to finish registration,  it tells you that you are an invalid user.

Closing the page and logging in again will work as expected (you can log in without registering again)

<b>How it should work</b>
It shoudl just ask you to log in again, not complete registration.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Issue 520: 24 Hour Page Open Bug](https://trello.com/c/8wri6A1K/6684-2-issue-520-24-hour-page-open-bug)

**Comment by alex-deaconu** [comment]
@robb-price this issue should now be corrected in Apps. To confirm, we are now showing the Sign In page rather than the registration pop-up, as suggested. Thanks.
