### ISSUE TITLE
Clicking on "Classic Editor" in the Common Header dropdown results in an error.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#526]
<b>How it works now</b>
1. At https://apps.risevision.com, click on the tiles, then select "Classic Editor"
2. Notice that you get this error message:
![2017-12-11_14-18-31](https://user-images.githubusercontent.com/6862256/33849287-334d5ca0-de7e-11e7-8f23-178ffe300fc6.png)

<b>How it should work:</b>
It should open the classic editor.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Issue 526: Opening Classic Editor from the Common Header dropdown has an error](https://trello.com/c/cG30bH2F/6688-2-issue-526-opening-classic-editor-from-the-common-header-dropdown-has-an-error)

**Comment by ezequielc** [comment]
@robb-price Issue should be fixed. Let me know if you still have problems. Thanks
