### ISSUE TITLE
Presentation Background Settings Clears Unintentionally

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/rise-vision-apps#536]
How to Replicate
1. Open up any presentation settings and add a hex color to the background and click Apply (this will apply a background color to presentation as intended)
2. Re-Open the settings (you will notice the background color is no longer there), click Apply
3. The color is now completely gone from the presentation background.

In this example I set the color to black and went back into the settings and you notice it is blank.
https://www.screencast.com/t/0xcT5FpuS

**Comment by mmeiers** [comment]
FYI @sheadarlison

**Comment by fjvallarino** [comment]
@mmeiers @sheadarlison @pcsandford this is fixed and deployed to production. Please re-open the issue if you find any problem.
