### ISSUE TITLE
Firefox Quantum - Can't submit support request or move schedule playlist items

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-vision-apps#538]
**Reproduction Steps:**

1. Support Request

Select "Get Support" from the "Need Help?" menu at the top of the Apps or Store page. With a non-priority support account, you'll then select "Contact Support" from the next window.

2. Playlist items

In the schedules menu try to change the order of the playlist items
![image](https://user-images.githubusercontent.com/33877348/34306946-0b1970a6-e703-11e7-85fb-a1659d0311e7.png)

**Expected Results:**

1. Support Request

A little window should pop-up in the bottom right that lets you ask a question, but it doesn't

2. Moving playlist items

You should be able to drag the playlist item to change the order, but nothing happens

**Comment by alex-deaconu** [comment]
The issue with moving Playlist Items should now be resolved. Leaving this Issue open however for the Zendesk widget not opening correctly. Thanks.

**Comment by ezequielc** [comment]
@kaden-rise @alex-deaconu  I opened a separate issue for the Support Widget fix (https://github.com/Rise-Vision/rise-vision-apps/issues/629). I am closing this as Playlist Item issue is fixed. Thanks
