### ISSUE TITLE
Blank Presentation doens't work when creating from onboarding bar

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rise-vision-apps#547]
To reproduce:

1. Start a new Company
1. Start a new Presentation
1. In the Onboarding Bar click Create
1. Select Blank Presentation

Nothing happens.

It should start a new Blank Presentation

https://www.screencast.com/t/j0iCo4MS

**Comment by fjvallarino** [comment]
@ezequielc closing this issue, as the fix has been deployed to production.
