### ISSUE TITLE
Transparent background option disappears in Placeholder

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rise-vision-apps#55]
**How to recreate**
Add a Google Spreadsheet Placeholder in the new Editor.  Configure the background color from transparent to something else then try to configure it back to transparent.  

**How it is working now**
The transparent option is not available.  See http://recordit.co/BaCgY6cyTC

**How it should work**
The transparent option should be available after choosing color.

**Comment by lapinnoir** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/conversation/1771813391

**Comment by lapinnoir** [comment]
FYI @alex-deaconu @ezequielc

**Comment by alex-deaconu** [comment]
@lapinnoir as that is occurring in a Widget, this issue should go to Content. @ezequielc FYI. Thanks.

**Comment by lapinnoir** [comment]
@alex-deaconu Thanks for letting me know
