### ISSUE TITLE
You can't add Storage content to your Presentation in the classic Editor

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#551]
<b>How it works now</b>
1. Open the classic Editor, add the Image or Video Widget, and select Configure, and then Single Image (or Video).
2. The page that comes up does not allow you to add anything from Storage.

As a workaround, this does not occur in the new Editor.

For further clarification: https://goo.gl/h8xvZq

<b>How it should work</b>
You shoudl be able to add content from Storage regardless of the Editor.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 551: Cannot add content from Storage in the Classic Editor](https://trello.com/c/UPb5CtzK/7065-issue-551-cannot-add-content-from-storage-in-the-classic-editor)

**Comment by tylermwight** [comment]
We have also found this issue in the new editor but it only shows up when editing image widgets (not first adding them):

1. Open the new editor, add an image widget, adding the image the first time will work.
2. Edit the image widget and click "Single Image" in the top left. Clicking on that will show this menu:

![image](https://user-images.githubusercontent.com/27289926/35156316-bec291dc-fced-11e7-9bc4-ada13cff7fd6.png)

**Comment by alex-deaconu** [comment]
@robb-price this should now be corrected. Thanks.

**Comment by robb-price** [comment]
@alex-deaconu Confirmed as corrected.
