### ISSUE TITLE
Storage Selector does not always appear for 'Added Users' in a Company

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-vision-apps#558]
1. Go to 'Company Users'
2. Select 'Add User'
3. Complete form with a test email address
4. Access validation email sent to above email address
5. Validate added user from this email's link
6. Log in to apps.risevision.com with this email, and complete registration
7. Add or access a Presentation with an Image Widget (any Template with Image)
8. Access 'Image Widget' Settings
9. Select 'Single Image' or 'Folder of Images'
10. Note blank iframe modal where Selector should appear 

Reference: Storage Selector error
![image](https://user-images.githubusercontent.com/11826611/35755466-5f492f7e-0835-11e8-8aca-5081469c7edb.png)

**Comment by fjvallarino** [comment]
@RV-Adrian this has been deployed to production. I'll close the issue. You can re-open if needed.

**Comment by RV-Adrian** [comment]
@fjvallarino Thanks! The error was on and off but it seems to work right now. I'll try to keep an eye on it.
