### ISSUE TITLE
Internal Error on first Template usage

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-vision-apps#568]
New User attempted to start with Full Screen Image template and receives a 'Failed to Get Presentation - Internal Error' popup

Please see:
https://fsty.io/v/NjZ3HCN

You should be able to access Console from the above link to get the system error output.

![image](https://user-images.githubusercontent.com/11826611/36615700-2d234608-18af-11e8-9ed5-7d7fbe0f7e36.png)

**Comment by ezequielc** [comment]
@RV-Adrian Can you replicate the issue?  I just checked and it works fine here. 
Also, I just verified the session date and it coincides with the downtime on Google Cloud that we had a few days ago. I am almost certain that was the cause. If you can't replicate, i would say we close this. Thanks!

**Comment by RV-Adrian** [comment]
@ezequielc No I could not replicate. Thought the console message might reveal more, but the Cloud issue makes sense. Closing now!
