### ISSUE TITLE
Last Connection showing as a time that is in the future

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-vision-apps#584]
As you can see here, https://www.screencast.com/t/1LlveRglp, Last Connection is showing a time that is in the future.  The timestamp should be approximately `13-Mar-2018 10:10 AM`, which is when the display was turned on.

**Comment by alanclayton** [comment]
When the Display is turned off, the Last Connection shows as yesterday. https://www.screencast.com/t/tl3bwZoV.

**Comment by alex-deaconu** [comment]
@alanclayton I'm pretty sure the Last Connection time is retrieved from the Messaging Service, unless I'm missing something the date returned is probably incorrect. Thanks.

**Comment by alanclayton** [comment]
@alex-deaconu when the card for this issue gets created on your board can you just move it over to ours and we'll take it. Thanks

**Comment by fjvallarino** [comment]
@alanclayton last week @tejohnso deployed a fix for this. I'm closing the issue, please re-open if needed. Thanks!
