### ISSUE TITLE
Monitoring Timeline not respecting changes

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-vision-apps#585]
I'm unable to change the Monitoring Timeline start/end time to be anything other than 3:00am - 12:30pm. 

1. Uncheck `Always`
2. Edit Timeline
3. Uncheck `All Day`
4. Change `Start Time` to be 8:00 AM then Apply
5. `Start Time` should be shown as 8:00 AM, but instead appearing as 3:00 AM  https://www.screencast.com/t/EaOmf57v

**Comment by fjvallarino** [comment]
@alanclayton I'm closing this issue as discussed, since it can't be reproduced currently.
