### ISSUE TITLE
RPP Trial is being considered as a Subscription on Store link

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rise-vision-apps#595]
If a user has a RPP trial (expired in this case), the link to Buy More licenses in Store assumes the trial is a subscription and use it to link to the subscription page:
https://www.screencast.com/t/SQ8GSB48

Instead of that, it should not assume RPP trial is a subscription and it should forward users to Store product page.

Thanks

**Comment by fjvallarino** [comment]
This was fixed with: https://github.com/Rise-Vision/rise-vision-apps/pull/596
