### ISSUE TITLE
Incorrect player version showing on display settings

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-vision-apps#620]
The player version for a Display on settings page is incorrect. Will provide display id on trello card.  See here, ![image](https://user-images.githubusercontent.com/6854911/39326429-89324d8c-495a-11e8-883c-58830e4f23eb.png)

**Comment by alexey-rise** [comment]
Fixed in https://github.com/Rise-Vision/core/pull/379
Please note that this fix only affects field changes moving forward (existing values are not affected).
