### ISSUE TITLE
You cannot remove a deleted Display from a Subscription

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#627]
### What is the expected behavior?
If a Display is deleted from a Company, and it is currently assigned to a Subscription, it should be automatically removed from that subscription.

### What is the actual behavior?
When you go to the Subscription, it shows that it is still assigned to this "phantom" Display, and will not allow you to select a different one.

 ### What steps can be taken to replicate the problem?
This video shows the issue in action:  https://goo.gl/w7cPsh

The workaround is to cancel the subscription and create a new one.

**Comment by olegrise** [comment]
@robb-price is this issue affecting a user and needs to be fixed ASAP or not really? Thanks.

**Comment by robb-price** [comment]
@olegrise We can create the fixed Subscription on the backend, so no one is blocked. However the user cannot fix this on their own.

**Comment by olegrise** [comment]
Thanks @robb-price. We are planning to fix this issue in the next day or two.
@ezequielc @alex-deaconu

**Comment by olegrise** [comment]
@robb-price the issue is fixed. The fix is going to work only for displays deleted after the fix. I didn't run any jobs to fix any existing subscriptions referencing deleted displays.
