### ISSUE TITLE
Preview showing certificate error when accessed over HTTPS.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#628]
**How to recreate**
Open any preview with https://

**What happens**
We see a certificate error.

**What should happen**
We should see preview.

**Comment by btfrise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Preview certificate issue](https://trello.com/c/cPejIEEi/7907-1-preview-certificate-issue)

**Comment by alex-deaconu** [comment]
@btfrise this issue should now be resolved. We have updated the certificate for preview.risevision.com. Thanks!
