### ISSUE TITLE
Error message when saving Presentation does not explain what happened.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#632]
**How to recreate**
This is an intermittent issue.

1. Create a new Presentation
2. Click Save

**What happens**
We get the error message **Failed to add Presentation** backend error.

**What should happen**
Error message should explain what happened and what the user should do if anything.
![errormessage](https://user-images.githubusercontent.com/8458926/39549634-30334532-4e24-11e8-9bf6-7622ac4d7295.png)

**Comment by fjvallarino** [comment]
@btfrise an improvement for this has been deployed (better user facing error messages). I'll close the issue for now, but feel free to re open if needed. Thanks!
