### ISSUE TITLE
Sign up for newsletter input field has no name attribute

### ISSUE THREAD

**Issue by ghislaineguerin** [Rise-Vision/rise-vision-apps#642]
<input type="checkbox" class="sign-up-newsletter-checkbox ng-valid ng-not-empty ng-dirty ng-valid-parse ng-touched" ng-model="profile.mailSyncEnabled">

This is causing tracking errors.

**Comment by ezequielc** [comment]
@ghislaineguerin Since the PR is merged, I am closing the issue. Thanks!
