### ISSUE TITLE
Users need to revoke Rise Vision App access before they can log in.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#646]
### What is the expected behavior?
If users have logged in before, they should be able to log in every day without issues.

### What is the actual behavior?
Some users (3 so far) have reported that they were going into a loop of logging in. When they entered their Gmail/Google credentials, it would go into a loop of taking them to https://apps.risevision.com/unauthorized/%257B%2522p%2522%253A%2522%2522%252C%2522u%2522%253A%2522%2522%252C%2522s%2522%253A%2522%2522%257D each time. 

Only by removing the Rise Vision app at https://myaccount.google.com were they able to log back in.

 ### What steps can be taken to replicate the problem
So far we have not been able to replicate, and only 3 users have reported the issue.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) [Ticket Blocked] Issue 646 - Users need to revoke Rise Vision App access before they can log in](https://trello.com/c/6s9VyPbx/8015-3-ticket-blocked-issue-646-users-need-to-revoke-rise-vision-app-access-before-they-can-log-in)

**Comment by alex-deaconu** [comment]
@robb-price have you guys encountered any other tickets related to this? We are considering closing this, as we do not have enough data and information for this type of issue and cannot replicate. We have however released various improvements in logging and catching errors with Authentication and API access. Thanks.

**Comment by alex-deaconu** [comment]
Closing as per the above.
