### ISSUE TITLE
Help Button is preventing some users from pressing Save / Publish

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#648]
<b>How it works now:</b>
Some users are reporting that they are prevented from clicking on Save / Publish from the Help button:
![screen shot 2018-05-17 at 1 22 20 pm](https://user-images.githubusercontent.com/6862256/40311489-eba6a882-5cdd-11e8-870d-ca07d05a6a00.png)

<b>How it should work:</b>
The Help button should not prevent the user from interacting with anything.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) [Users blocked] Issue 648: Help Button prevents pressing Save/Publish](https://trello.com/c/AfRHUg2M/8014-3-users-blocked-issue-648-help-button-prevents-pressing-save-publish)

**Comment by alex-deaconu** [comment]
Resolved by moving the Help button back to the Common Header. The ZD button in its original state will only show on login pages. Thanks.
