### ISSUE TITLE
'Ghost' preview on dragging Playlist item has unintentional offset

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-vision-apps#649]
How it works now:
When you drag a Playlist item on the dotted anchor UI, the preview 'ghost' is offset from where the user's cursor is at that point.

![bug](https://user-images.githubusercontent.com/11826611/40318036-49c69342-5cf1-11e8-8b3f-17427226e632.gif)

How it should work:
The preview should be aligned just below the user's cursor position.

**Comment by fjvallarino** [comment]
@RV-Adrian closing issue. Please re-open if needed!
