### ISSUE TITLE
Storage UI sits on loading and doesn't show error when blocked by firewall

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rise-vision-apps#652]
A user reported they couldn't load Storage: https://risevision.zendesk.com/agent/tickets/23555
We identified that storage server url was blocked by firewall.

But Storage UI remained on loading, without letting the user know about the request failure.

<img width="1440" alt="screen shot 2018-05-25 at 5 32 26 pm" src="https://user-images.githubusercontent.com/7738553/40565226-10059f3c-6042-11e8-8e03-8670ed303570.png">

**How it should work:**
A message should be shown to the user informed that the request failed and they should check their connection or firewall.

**Comment by alex-deaconu** [comment]
@ezequielc this issue should be resolved with the latest release. We are now checking the endpoint URL directly and reporting an error if it's unreachable. Thanks.
