### ISSUE TITLE
When using Image as full-screen placeholder background, Presentation white screens.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#659]
**How to recreate**
1. Create a new Presentation with a full screen Placeholder.
2. Add a background image to that placeholder, no other content.
3. Publish the Presentation and assign it to a Schedule/Display.

**What happens**
The image background appears for around 20 seconds, then goes white.

**What should happen**
Display should continue playing background image.

**Notes**
While testing, I saw some odd things happen.

On the client's Windows machine, when the background image would turn white, I would be immediately disconnected from the remote session. After about 5 minutes, the connection would start up. The Display showed offline shortly after the white screen appeared.

On my Linux machine, when the background image turned white, the Display went offline in displays.risevision.com, my remote session shut off. I closed Rise Player and noticed that while I was still connected to wifi, I couldn't browse anywhere. I rebooted the machine, Rise Player started, I saw the image for 20 seconds, then white. The Display was then still online and I could remote in.

After the first instance of the above on each machine I am not able to replicate, but while doing local testing it's something that you will want to look out for.

**Comment by btfrise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) [Ticket Blocked] Issue 659 When using Image as full-screen placeholder background, Presentation white screens.](https://trello.com/c/K88dCo6i/8111-1-ticket-blocked-issue-659-when-using-image-as-full-screen-placeholder-background-presentation-white-screens)

**Comment by ezequielc** [comment]
@btfrise This seems to me like a Viewer/Delivery issue. @alex-deaconu @tejohnso Do you agree? Thanks

**Comment by btfrise** [comment]
[Moved](https://github.com/Rise-Vision/viewer/issues/309)
