### ISSUE TITLE
Thumbnail does not update when storage file is overwritten.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#661]
**How to replicate**

1. Upload an image file to Rise Storage.
2. Copy link to that image file and open in new tab.
3. Upload a different image with same filename to same Rise Storage account.
4. Refresh tab viewing image file, image is updated.
5. Look at thumbnail, it is not updated.

**Workaround**
Clearing cache will show new thumbnail.

**Comment by btfrise** [comment]
Per @rudibravo [this](https://github.com/Rise-Vision/rise-storage/issues/44) is now with Apps.

**Comment by btfrise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Rise Storage defect #44 - Thumbnail does not update when file is overwritten](https://trello.com/c/vYvQJmMo/8052-1-rise-storage-defect-44-thumbnail-does-not-update-when-file-is-overwritten)

**Comment by btfrise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Rise Storage defect #44 - Thumbnail does not update when file is overwritten](https://trello.com/c/vYvQJmMo/8052-1-rise-storage-defect-44-thumbnail-does-not-update-when-file-is-overwritten)

**Comment by alex-deaconu** [comment]
@btfrise this is now fixed. @rudibravo thanks for the initial investigation!
