### ISSUE TITLE
'Downgrade' appears while on Free plan tier

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-vision-apps#665]
**How to recreate:**
Go to a Company with a lapsed trial that has been placed on 'Free'
ie. https://store.risevision.com/shopping-cart?cid=f10e748f-d11f-4c5e-802c-9bab59e56b3d

**What happens**
'Downgrade' appears while on Free plan tier

**What should happen**
'Downgrade' should not be visible, only 'Subscribe'

![image](https://user-images.githubusercontent.com/11826611/41172088-b8fbd744-6b20-11e8-9fc7-746580282848.png)

**Comment by RV-Adrian** [comment]
@alex-deaconu FYI this looks fixed with the Pricing deployment yesterday 👍

**Comment by alex-deaconu** [comment]
@RV-Adrian the logic around the buttons in the Plan Modal has been refactored so this issue should be prevented. Closing. Thanks.

**Comment by RV-Adrian** [comment]
@alex-deaconu 👍
