### ISSUE TITLE
Trial subscriptions show strange status.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#668]
**How to recreate**
1. Create a Presentation in a Company, add a trial of a 3rd party Widget to that Presentation.

**What happens**
The Widget shows _editor-app.subscription.status.premium - 7 Days Trial_.

**What should happen**
The Widget trial status should show _7 Days Trial
![trialstatus](https://user-images.githubusercontent.com/8458926/41362406-e34689ac-6ef6-11e8-9d36-0abf8f1ab616.png)
_

**Comment by alex-deaconu** [comment]
@btfrise this issue is now fixed. It should say "Not Subscribed" in this case. Thanks.
<img width="819" alt="screen shot 2018-06-13 at 3 35 18 pm" src="https://user-images.githubusercontent.com/6218188/41373833-7770d5e2-6f1f-11e8-8268-6ccacb32d17d.png">
