### ISSUE TITLE
If only one item in Schedule, the duration of that item is blank, and PUD is not selected, Display shows that nothing is assigned to Schedule.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#669]
**How to recreate**
1. Add a Presentation to a Schedule that is assigned to a Display.
2. Remove any entry in the Duration field.
3. Make sure PUD is unchecked.

**What happens**
Display shows that nothing is scheduled.

**What should happen**
An error message should appear when trying to save a playlist item with no duration and PUD is not checked.

**Comment by alex-deaconu** [comment]
@btfrise this issue should now be corrected. We've added validation for the Duration field in the Placeholder Item and Schedule Playlist Item settings. It should not allow blank duration or less than 1. Thanks.
