### ISSUE TITLE
User gets booted back to master company after clicking "Save" on Display page.

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rise-vision-apps#68]
From @ashleighalmeida in https://github.com/Rise-Vision/displays-app/issues/97:

What is happening:

The user switches to their sub company
User navigates into their display's page and clicks save. 
Once they click the "Displays" link to go back to their master list, they are brought back to the parent company.

What should be happening:
When user clicks "Save" on the display page, they are brought back to their master list inside of being bounced back to the parent company.

Recreation Demo:
https://drive.google.com/a/risevision.com/file/d/0B5_6TQ6T_mw1UFlSNEMtZEJ2OWc/view?usp=sharing

Thanks!

https://app.intercom.io/a/apps/d85f4ah4/inbox/apa@risevision.com/conversations/1845881254

**Comment by brianloosbrock** [comment]
+1 - I just noticed this as well.

**Comment by ezequielc** [comment]
@brianloosbrock @rjcahoy This issue has been fixed.
It was switching to master company even when visiting Display Details, not only after saving.
Could you please verify it works? Thanks

**Comment by brianloosbrock** [comment]
@ezequielc Verified. Looks good.

**Comment by ezequielc** [comment]
Thanks @brianloosbrock
