### ISSUE TITLE
All Displays are showing offline.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#681]
Currently all Displays are showing as offline in every company. [Here](https://apps.risevision.com/displays/list?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55) is a link to our uptime company, which has Displays that are online and displaying content, that are being reflected as offline.

**Comment by btfrise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) All Displays are showing offline.](https://trello.com/c/H4keRQTh/8203-1-all-displays-are-showing-offline)

**Comment by btfrise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) All Displays are showing offline.](https://trello.com/c/H4keRQTh/8203-1-all-displays-are-showing-offline)

**Comment by alex-deaconu** [comment]
@btfrise despite the recovery from this issue, wondering if you could leave this open so we can add a more user friendly error message rather than just showing all the Displays as offline. Thanks!

**Comment by fjvallarino** [comment]
@btfrise this has been deployed to production. I'm closing the issue; please re open it if needed. Thanks!
