### ISSUE TITLE
Microsoft Edge - Can't access Placeholder properties in Editor

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#685]
### What is the expected behavior?
Clicking the placeholder should allow you to access options relating to the placeholder, such as adding playlist items and modifying properties

### What is the actual behavior?
Clicking the placeholder causes the UI to fidget and does not continue to the placeholder options or properties.

### What steps can be taken to replicate the problem?
- Access apps.risevision.com in Microsoft Edge
- Create a new presentation
- Use a blank template
- Create a placeholder
- Select the placeholder

**Comment by fjvallarino** [comment]
@PatrickA-RiseVision a fix has been deployed to production. I'm closing the issue. Please re-open if needed!
