### ISSUE TITLE
'Delete' key moves Editor back in browser history (behind modal)

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/rise-vision-apps#69]
Also happens when there is no modal. Chrome/OSX

https://cloud.githubusercontent.com/assets/11826611/11129867/c850e618-894f-11e5-96ee-c06a9145b78f.gif

**Comment by ezequielc** [comment]
@alex-deaconu Issue should be fixed. Could you validate and close? Thanks!

**Comment by alex-deaconu** [comment]
@ezequielc works perfectly. Thanks for fixing!
