### ISSUE TITLE
Browser Tab Behavior

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/rise-vision-apps#691]
### What is the expected behavior?
Browser tabs should show helpful information to identify what they are for with a quick glance. I've attached a very rough mock-up.

![image](https://user-images.githubusercontent.com/41346848/42845472-4a32b5b8-89d3-11e8-8d65-1d6666b66521.png)

### What is the actual behavior?
Regardless of whether editor, a specific presentation, display, etc. is selected, all tabs look the same.
![image](https://user-images.githubusercontent.com/41346848/42845558-90b40b68-89d3-11e8-95f8-436183f41497.png)

### What steps can be taken to replicate the problem?
Problem is very easy to replicate, just open several tabs through apps. 

This isn't really a dire issue, but it is something that can improve user experience, especially if they have a large amount of displays or content to update or check.

**Comment by ezequielc** [comment]
@colby-maughan Thanks for the input. As you pointed out, this is not really an issue so we will consider it a new feature. We will queue a card in Apps backlog, but I will go ahead and close this. Thanks!
