### ISSUE TITLE
Displays created w/Claim ID after 4/30 have no display.json file.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#692]
**What happens**
Displays created by Claim ID after 4/30 cannot display content from Rise Storage.

**What should happen**
All Displays should be able to show content from Rise Storage.

**Information**

Replicated [here](https://connect.risevision.com/Host#Support/All%20Sessions//72cee5d9-ea38-4399-b3cb-c902beaeb9bc)

**Comment by tejohnso** [comment]
@btfrise This should be resolved now. Please confirm&close.

**Comment by btfrise** [comment]
Looks good.
