### ISSUE TITLE
Dowload Player button from email is a broken link 

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rise-vision-apps#696]
Both Download Rise Player button and 'http://www.risevision.com/riseplayer' link are sending users to https://help.risevision.com/hc/en-us/sections/360000094863-Activate-a-Display which returns a 404 error page.

instead, they should point users to http://www.risevision.com/riseplayer.

**Comment by fjvallarino** [comment]
@ezequielc this has been deployed. I'm closing the issue. Please re open if needed!
