### ISSUE TITLE
Sizing placeholders with % - effect on widgets

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/rise-vision-apps#70]
Not sure if technically a bug or enhancement, but marked as bug as result was not as expected

Shea and I were looking to build a slideshow template that would be responsive. I set up a placeholder and changed the width to 70%, and allowed for a margin of 15% each side, expecting this to shrink according to screen size. However, setting a % rather than px size for the placeholder appears to reduce the size taken up by the widget. I have tried to change the body to % but this doesn't appear to affect it. Please see this test template https://apps.risevision.com/editor/workspace/80f3bfa4-90a4-42c5-89d0-14d95246b06d/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

The right hand side placeholder is sized to half the screen at 960px and the left hand side is 50% and the difference in the widget size is noticeable. The text widget was also effected as the alignment options within the widget would not center/left/right align correctly when inside a placeholder with % width.

Steps to Recreate

Set up a placeholder to half of the width of the screen using px and add the image folder widget and text widget. Set some text to centre align.
Set up a second placeholder to half of the width of the screen using % and add the image folder widget and text widget. Set some text to centre align.
Preview the presentation to see the two different sizes of image folder widget on screen. The text in the text widget within the % width placeholder should also be off-centre.

Thanks!

**Comment by ByronDarlison** [comment]
As per discussions on this card https://trello.com/c/NlZnBDsn closing
