### ISSUE TITLE
If your file has a "#" in it, it will not show in your Presentation when you use a folder.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#704]
### What is the expected behavior?
Regardless of the name of the file, it should show in your Presentation.

### What is the actual behavior?
If your file has a #, it will not show in the Presentation if you are playing this for a folder. If you link to the file directly, it shows.

### What steps can be taken to replicate the problem?
1. Add the Image Widget to a folder that has a file with a # in the title.
2. Notice in the Presentation, that file will not show in the image rotation.
3. Notice again if you add the image using a direct link to the file, it will show.

**Comment by ezequielc** [comment]
@sheadarlison @pcsandford This seems like an Image Widget issue. Do you want to take the initial look at it? Thanks

**Comment by sheadarlison** [comment]
@stulees Do you know if this is Image or RLS related?

**Comment by sheadarlison** [comment]
Okay thanks @stulees 

@robb-price could you please move this to the Image Widget repo - we'll investigate this week.

Thanks

**Comment by sheadarlison** [comment]
Closing this and opened here: https://github.com/Rise-Vision/widget-image/issues/169
