### ISSUE TITLE
Placeholder has two spaces between div and id

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/rise-vision-apps#706]
Reproduction Steps
Added a blank presentation then one placeholder. Then I went into the html. 

Expected Results
https://www.screencast.com/t/kEv4cGCJcGvX
I expected to see a placeholder named <div id="ph0"> instead I got <div  id="ph0">.
This was problematic for me because I added a class after the id and it did not pick it up until I deleted the extra space.

**Comment by ezequielc** [comment]
@mmeiers Do you have an example? A presentation with a class that only works if we remove the extra space? I am not able to replicate it. Thanks

**Comment by fjvallarino** [comment]
@mmeiers this is fixed in production. Please, reopen the issue if needed!
