### ISSUE TITLE
Win 10 Display Details page shows a message for Chrome OS displays

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rise-vision-apps#707]
The screenshot area on Display Details page shows a message related to Chrome OS Beta even though the Display is a Windows 10 computer.

https://apps.risevision.com/displays/details/7G55UB7ZA4VH?cid=748185b7-00d5-4cd9-9acb-1919dde44426

![Screenshot](https://s3.amazonaws.com/uploads.hipchat.com/106443/1323337/jWv4150M7Bz3BX0/Screen%20Shot%202018-08-09%20at%201.59.49%20PM.png).

Instead, it should show the regular message or the screenshot if available.

**Comment by rudibravo** [comment]
@ezequielc Fix is deployed. Can you please validate and close? Thanks

**Comment by ezequielc** [comment]
@rudibravo Looks good. Thanks for fixing it!
