### ISSUE TITLE
Displays list in apps is not sortable by columns aside from Name

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#717]
### What is the expected behavior?
The displays list is sorted when you click on the table headers.

### What is the actual behavior?
Only the Name header responds to mouse clicks.  The other columns are not sortable.

### What steps can be taken to replicate the problem?
1. Navigate to https://apps.risevision.com/displays/list?cid=49e395ef-825a-4fee-9c58-b44c4337e192
2. Try to sort by Player Type

**Comment by ezequielc** [comment]
@PatrickA-RiseVision This is not really a bug, since we never had this ability. 
We analyzed this in the past and due to how our data is structured it is not an easy feature to add. 
I will keep this card in our backlog, but I will close the issue. Let me know if you think otherwise. Thanks!
