### ISSUE TITLE
Storage: if a file exists in trash, it will display instead of a file with the same path and filename in storage 

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#720]
### What is the expected behavior?
Files uploaded to Storage should display correctly in Storage and in Presentations.

### What is the actual behavior?
If a file already exists in trash, and a file with the same name is uploaded to the same path in Storage, the file preview and the image in presentations are replaced with the file from Trash.

### What steps can be taken to replicate the problem?
1. Upload a file to storage.
2. Run that file on a presentation using the Image Widget (single image).
3. Move the file to trash.
4. Name a different file the same thing on your machine.
5. Upload the file you renamed in 4 to storage.

The preview in Storage should be of the file you trashed.  Your display should also not update.  Try downloading the file.  The correct file seems to get downloaded in spite of the preview.

Extra credit:
1. Rename the file in storage -- just add a 2 or something at the end of the file name.
2. Click on "Presentations" (or anywhere else in the app).
3. Click on "Storage" (Refreshing didn't seem to work here when I was playing with it).  -- The preview in Storage should now be correct for the renamed file.
4. Change the file's name back to what it was originally.
5. Click on "Presentations" (or anywhere else in the app).
6. Click on "Storage" (Refreshing didn't seem to work here when I was playing with it). -- The preview in Storage should be for the wrong file again.

Extra credit 2:
1. If you've manipulated the file name, change it back to the file name of the file in Trash.
2. Delete the file from Trash.
3. Check the file in Storage.  Repeat the steps above as needed.  For some reason, it's still broken, even after you take the file away in Trash.

**Comment by ezequielc** [comment]
@rudibravo @tejohnso This seems like a issue for Delivery, do you agree? Thanks

**Comment by rudibravo** [comment]
@ezequielc @tejohnso agreed.

**Comment by PatrickA-RiseVision** [comment]
https://github.com/Rise-Vision/rise-launcher-electron/issues/757 replaced this
