### ISSUE TITLE
Displays: Unsupported Players are licensed by default if licenses are available

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#721]
### What is the expected behavior?
Unsupported Players cannot be licensed, and the Licensed Display toggle is greyed out/disabled

### What is the actual behavior?
Unsupported Players are licensed by default if licenses are available.  Licensed features (like Embedded Presentations) are available as long as Licensed Display toggle is not turned off manually.

### What steps can be taken to replicate the problem?
1. Add a new Display to your company while unused Licenses are available in your account.
2. On an unsupported player, set up the display by Display ID.
3. Try scheduling a presentation that contains various Licensed features onto that display (Twitter doesn't seem to work, but Embedded Presentation does)

You can also replicate this using a Claim ID, but "Licensed Display" is not toggled on by default.  Instead:
1. On an unsupported player, set up the display by Claim ID.
2. Before the Player version updates on the app, find the Display in the app in Displays
3. Turn Licensed Display on.
4. Try scheduling a presentation that contains various Licensed features onto that display (Twitter doesn't seem to work, but Embedded Presentation does)

**Comment by fjvallarino** [comment]
@PatrickA-RiseVision a fix for this has been deployed to production. The previous version would only assign a license to a display if its Player was supported or was not installed (I added the validation for the new Chrome Player). If you later installed an Unsupported player, the license would remain assigned. Now, if you install an Unsupported player, the license will be removed from the Display and become available for manual assignment (this takes a few minutes after the player notifies its version). 

I'm closing the issue. Please re open if needed!
