### ISSUE TITLE
Upload Folder doesn't work if the images already exist outside of that folder

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#725]
### What is the expected behavior?
When you upload a folder, regardless if those files exist in Storage already, it uploads all files to that folder.

### What is the actual behavior?
If those files exist outside of the folder you are uploading, they will not be uploaded to the folder.

### What steps can be taken to replicate the problem?
1. Upload Image1.png, Image2.png to your main Storage folder.
2. Select Upload Folder, and upload the folder that contains Image1.png and Image2.png.
3. Notice that they are not created in the Folder.
For further clarification: https://goo.gl/5DrFGq

The workaround is to upload, and then move them over to the folder that was created, or rename them before uploading them, but it is a pain.

--

**Comment by btfrise** [comment]
Confirmed fixed. Closing.
