### ISSUE TITLE
When you upload new images with the same names, the older images show up in Storage UI

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#733]
### What is the expected behavior?
If you replace the images in a folder that are playing in a Presentation, both the Display and Storage UI will show those new images.

### What is the actual behavior?
The Display downloads and begins showing the new images, but the Storage UI continues to show the older ones. This shows regardless if you clear cache, are in an Incognito window, or even after 15 minutes.

### What steps can be taken to replicate the problem?
1. Upload 4 images, called 1, 2, 3, 4 to a Folder, and play that folder in a Presentation with the Image Widget
2. Delete the 4 images form the folder, confirm they are moved to Trash.
3. Upload 4 new images, all called 1, 2, 3, and 4. Notice that when you upload the thumbnail is for the older image.
4. Notice the Display downloads and shows the new images.

For greater clarification: https://goo.gl/bpuhd4

--

**Comment by tejohnso** [comment]
This will be part of a [future epic](https://trello.com/c/fI6jppVd) and the design is considered [here](https://trello.com/c/5ysg8bhL)
