### ISSUE TITLE
Users are not warned when uploading file types we do not support. 

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#734]
### What is the expected behavior?
When a user uploads a file type that is not supported in our players they should be warned as such and provided with instructions on what files are supported. 

- https://help.risevision.com/hc/en-us/articles/201788630-Video-Widget-supported-formats
- https://help.risevision.com/hc/en-us/articles/115001957183-Supported-file-types-for-the-Image-Widget

### What is the actual behavior?
Users are not warned when they upload unsupported file types. 

### Files types that should trigger a warning
Videos

- .mov  
- .wmv
- .m4v
- .flv
- .avi
- .ogg

Images

- .tiff

FYI @alanclayton

**Comment by andrecardoso** [comment]
Fix deployed to production.
