### ISSUE TITLE
Store still shows "Store Account" instead of "Account and Billing".

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#735]
### What is the expected behavior?
Apps.risevision.com and store.risevision.com should have the same options in the Common Header.

### What is the actual behavior?
Currently apps.risevision.com says Account & Billing, while store.risevision.com shows Store Account.

store.risevision.com: https://goo.gl/rhBZPE
apps.risevision.com: https://goo.gl/cYhmWT

**Comment by fjvallarino** [comment]
@robb-price this has been deployed to production. As a summary, besides updating the link you mentioned, the following changes were made:

- Chargebee users are redirected to the Plans Modal in Apps, except for Invoice History, Unpaid Invoices and Invoice Details.
- Chargebee users are redirected to /billing in Apps when trying to access Account and Billing
- These redirections do not apply to old Rise's Store users

 Please re open the issue if needed!

@alex-deaconu @ezequielc FYI
