### ISSUE TITLE
User list does not show all users in a Company when there are more than 50 users

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#736]
### What is the expected behavior?
Looking at the list of users in a Company, you should see all users.

### What is the actual behavior?
For Companies that have more than 50 users, you can't see any users past 50.

**Comment by alex-deaconu** [comment]
@robb-price do you have a Company Id where we can replicate this? Thanks!

**Comment by robb-price** [comment]
@alex-deaconu You can replicate it with Company 83d6c7ad-7028-4233-8861-295857451398. Thanks!

**Comment by alex-deaconu** [comment]
@robb-price awesome, thanks!

**Comment by alex-deaconu** [comment]
@robb-price the functionality to load more results on scroll was not actually implemented on the Users list. Who would have thought a Company would have more than 50 users?

Either way, this has been corrected and should load more users on scroll as expected now.

Closing. Thanks!

**Comment by robb-price** [comment]
@alex-deaconu Thanks!
