### ISSUE TITLE
Trial Basic Plan sets to bill in Chargebee despite another plan being purchased

### ISSUE THREAD

**Issue by jrkuchta** [Rise-Vision/rise-vision-apps#740]
### What is the expected behavior?
After a plan purchase by a customer, the trial would end and only the purchased subscription would remain active
### What is the actual behavior?
The trial remains active and sets to bill because there is now a payment method associated.

### What steps can be taken to replicate the problem?
Start a new account trial and then purchase a different plan.

**Comment by olegrise** [comment]
The store-server code was fixed and change was deployed to production. Thanks.

**Comment by jrkuchta** [comment]
Thanks, Oleg!



JR Kuchta
jrk@risevision.com
*Rise Vision*
Communicate Visually
www.risevision.com
