### ISSUE TITLE
Store: You can't obtain a quote for a product you are already subscribed to

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#750]
### What is the expected behavior?
You can obtain a quote for any product on Rise Vision by adding it to your cart, navigating to your cart and clicking on "Create Quote".

### What is the actual behavior?
You cannot add a product to you are already subscribed to to your cart, so you cannot obtain a quote for that product.

### What steps can be taken to replicate the problem?
1. In a test company, subscribe to a plan.
2. In the same test company, go to store.risevision.com.
3. Select the same plan you subscribed to in step 1.
4. You are unable to add it to your cart, which prevents you from obtaining a quote.
---
5. For contrast, select a different plan from step 1 and add it to your cart.
6. Click on "Go to cart"
7. Click on "Create quote", it will function as intended.

**Comment by ezequielc** [comment]
@PatrickA-RiseVision I am not sure this is an issue.
You can't subscribe again to a plan that you are already subscribed to, that is why you can't add it to the cart.

Even if you create the quote, you wouldn't be able to subscribe to the plan again, as you are already a subscriber. 
Could you clarify what is the scenario you would like to cover?

Thanks!

**Comment by ezequielc** [comment]
@PatrickA-RiseVision As Growth is going to handle quotes, I will close the issue. Thanks!
