### ISSUE TITLE
Very old Player showing as  supported

### ISSUE THREAD

**Issue by tylermwight** [Rise-Vision/rise-vision-apps#753]
Issue: A very old verison of Rise Player is showing as 'supported' when it should not. This lets you change display licensing on old displays we do not want to support

An example can be seen here:
https://apps.risevision.com/displays/details/75WXQ2D75A8Y?cid=7bb84387-b769-4d9e-95c5-f7f3809dde70&cHJpb3JpdHktc3VwcG9ydA=1

In case they change that display I've also attached a screenshot here:

![image](https://user-images.githubusercontent.com/27289926/46213491-ec2dca00-c2f5-11e8-9931-331db674b246.png)

**Comment by fjvallarino** [comment]
@tylermwight this has been fixed and deployed to production. Please re open the issue if needed!
