### ISSUE TITLE
Plan Bar not showing that a customer is subscribed to a plan

### ISSUE THREAD

**Issue by jrkuchta** [Rise-Vision/rise-vision-apps#754]
### What is the expected behavior?

The plan bar in app displays that a customer is on a plan and which plan they are on.

### What is the actual behavior?

The plan bar did not show that the customer was on a plan, even though they had purchased a plan 2 days prior.

### What steps can be taken to replicate the problem?

Unknown if this happens with all subscription purchases.

**Comment by olegrise** [comment]
@jrkuchta we just deployed the fix for this issue. Thanks.
