### ISSUE TITLE
Incorrect Licensed Displays count

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rise-vision-apps#757]
A company on the Advanced Plan has 8 displays but Displays list shows:
11 Licensed Displays | 3 Unused Licenses

It should show 8 Licensed Displays instead of 11. 

Sample:
https://apps.risevision.com/displays/list?cid=89d5e521-c80e-487d-be3c-dabe938493ff

Also, we a recommendation is to say Available instead of Unused.
So, the expected would be:

8 Licensed Displays | 3 Available Licenses

**Comment by alex-deaconu** [comment]
Unfortunately due to deployment issues the fix for this issue was not deployed until now. It is now resolved; with updated wording. Thanks.
