### ISSUE TITLE
Subscriptions cancelled mid-cycle are not visible while still active

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#759]
### What is the expected behavior?
Users who cancel subscriptions mid-cycle continue to have service until the cycle ends.  Support can see and help manage their subscriptions, as well as assist with free and licensed features.

### What is the actual behavior?
Users who cancel their subscriptions mid-cycle have that subscription removed from their account.  It continues to work as intended (they have service), but does not appear on their account page.  Support cannot identify the subscription, and is of the impression that the user is not subscribed.

### What steps can be taken to replicate the problem?
1. Create a subscription for a year of Starter plan.
2. Cancel it.  You still have the display license until your cycle ends.
3. Notice that the top banner says "Get more out of rise vision!" as though you're not subscribed.
4. Your subscription doesn't appear in your subscriptions.
5. It's not possible for the user to find out how long is left.

Note also that if you do this for a sub-company subscription billed to a parent company, the logs won't identify it either on the sub-company.

**Comment by ezequielc** [comment]
A fix has been released.
Plan bar now shows the date until the plan is valid: "Your Basic Plan subscription expires on 15-Jun-2019"
