### ISSUE TITLE
Chargebee Invoice 17

### ISSUE THREAD

**Issue by Connie038** [Rise-Vision/rise-vision-apps#764]
On Se 17, US customer picked a CAD plan [Advanced Plan (Yearly/CAD)] for CAD968
Customer id: 1c0689f6-50cc-412f-93a4-b5df384f9458
Customer name: Washington County Community College
Subscription Id: 1mk51UMR3vtUzCsau
Payment was received for USD968

What should be the process to correct this regarding subscription, invoice, and payment?

**Comment by ezequielc** [comment]
@Connie038  @jrkuchta I believe this is the invoice we talked few days ago. @jrkuchta Is this something you can take? Thanks

**Comment by Connie038** [comment]
@ezequielc @jrkuchta Yes. That is the invoice I mentioned in SoS. I would need to void invoice 17, and I need someone remove the subscription and replace it with a new one for a correct plan and new invoice in USD. Please let me know who would work on this, customer success or accounting? Thanks.

**Comment by jrkuchta** [comment]
@ezequielc @Connie038 This was corrected.  This defect can be closed.

**Comment by ezequielc** [comment]
@jrkuchta Thanks!
