### ISSUE TITLE
Sales Tax are posted to wrong GL account in Xero - Urgent to fix

### ISSUE THREAD

**Issue by Connie038** [Rise-Vision/rise-vision-apps#770]
US sales tax on Chargebee invoices were posted to Canadian Sales tax account (2210). They should be posted to account 2215 instead. 

Some examples: 
invoice 63
in Chargebee
![image](https://user-images.githubusercontent.com/38078274/47584537-c7466a00-d928-11e8-9594-107e29f96d21.png)
in Xero
![image](https://user-images.githubusercontent.com/38078274/47584632-142a4080-d929-11e8-8c13-db1588c190ac.png)

also check invoice 7, 9, 27, 25, 29, 32, 33 ...

**Comment by olegrise** [comment]
@Connie038 how did you make this screenshot in Xero? Could you share a link this page?

**Comment by Connie038** [comment]
@olegrise The link might not work because it is from a query to the Journal Report. 
Here is the link. You will need to scroll down to find the journal for customer "Revolutionary Clinics". 
https://go.xero.com/Reports/Report2.aspx?reportId=fae8c037-0348-4320-9adb-1e72a3ca9755&report=&statement=37cd22da-ae89-42a2-a4f9-5c6af3f64ce5&attPage=&fromDate=9%20Oct%202018&toDate=9%20Oct%202018&orderBy=JournalID&showTracking=null&postedManualJournalsOnly=null
If you find the link doesn't work, you can run the report yourself by Xero (RVI) -> Reports -> All Reports -> Journal Report -> Set the date range as invoice date, then scroll down to look for the customer. You should find the journal with Accounts Receivable, Sales Tax and Revenue accounts. 

Please call me if you have any question. Thanks a lot!

**Comment by olegrise** [comment]
@Connie038 sounds good. Thanks.

**Comment by Connie038** [comment]
@olegrise Here is what xero responded yesterday
![image](https://user-images.githubusercontent.com/38078274/47785261-95dded80-dcde-11e8-8ab5-5f5cef61ef2e.png)

**Comment by Connie038** [comment]
![image](https://user-images.githubusercontent.com/38078274/48012064-278a9800-e0ef-11e8-9ce8-f786c03cc5ac.png)

So, this is something due to limitation from the Xero version we currently used. Accounting will review and reclass internally on monthly basis.
