### ISSUE TITLE
Security codes beginning with 0 not being accepted during payment

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/rise-vision-apps#771]
### What is the expected behavior?

Customer should be able to input credit card number, expiration date, and security code to make a purchase on the Rise Vision store.

### What is the actual behavior?

Security codes with a 0 at the beginning don't seem to be working. 

### What steps can be taken to replicate the problem?

Attempt to purchase a subscription using a card with a security code that begins with a 0.

**Comment by alex-deaconu** [comment]
@colby-maughan this issue should now be fixed. Users should be able to enter CVC codes starting with 0s correctly. Thanks.
