### ISSUE TITLE
Classic Editor Not Recognizing Plans in Chargebee

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/rise-vision-apps#773]
### What is the expected behavior?

Adding a Widget through classic editor should work as it did in previous store implementation. 

### What is the actual behavior?

When you attempt to add a Widget through the classic editor, you are prompted to purchase a plan. I've only been able to reproduce this on an account that was recently migrated to Chargebee so far. 

### What steps can be taken to replicate the problem?

1. Make sure the company you are checking is linked to Chargebee
2. Open a presentation via the classic editor.
3. Open a placeholder's properties and click "Add" then "Content". 
4. You will be brought to the pricing page and the presentation will now be open in an iframe behind the pricing page.

**Comment by alex-deaconu** [comment]
@colby-maughan this issue should now be corrected. Thanks.
