### ISSUE TITLE
3-5 years plan is shown as 'Yearly' in Account & Billing page

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rise-vision-apps#776]
We added new plans for 3 and 5 years terms and they are properly handled by the system.
But Account & Billing page shows the plan name as 'Yearly' instead of stating 3 or 5 years.

What is showing: 'Basic Plan ( Yearly / USD)'
What it should be: 'Basic Plan ( 3 Year / USD)'

Example:
![Billing Image](https://trello-attachments.s3.amazonaws.com/5911c99d0e011200d8261ace/5be46dbcb809ce651409400d/f5b95ec1815f4c103efe1680ba82510b/image.png)

**Comment by alex-deaconu** [comment]
This is now fixed and deployed.
