### ISSUE TITLE
Unable to remove billing notification emails if a duplicate has been entered

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-vision-apps#780]
**Expected behavior:**

End users should be able to enter and remove email addresses from the billing notification list at any time.

**Actual behavior:**

If a duplicate email address has been added to the billing notification list, there is no longer an option to remove email addresses from the list.

**Steps to replicate**

1. Add the same email address to the billing notification list multiple times.

**Comment by fjvallarino** [comment]
@alex-deaconu this has been deployed to production. Please re open the issue if needed!

**Comment by alex-deaconu** [comment]
@kaden-rise FYI. Thanks.
