### ISSUE TITLE
On mobile resolution, Display IDs are getting cut off in the activation email

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rise-vision-apps#784]
Display IDs are getting cut off in the activation email in GMail on Android

![Mobile Resolution](https://s3.amazonaws.com/uploads.hipchat.com/106443/1323337/CUIvYpTqi9XzEaO/Screenshot_20181121-111701.png)

**Comment by fjvallarino** [comment]
@ezequielc this has been deployed. Please re open if needed!
