### ISSUE TITLE
You can only start a Starter or Basic Plan as a Trial, not a full blown subscription

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#794]
**Expected Behavior:**
As a Parent Company, I can quickly start a subscription for a Sub Company without having to start a trial first.

**Actual Behavior:**
If I want to start a Starter or Basic Plan, the only option is a trial:
![2019-01-03_15-45-12](https://user-images.githubusercontent.com/6862256/50660665-9f9a0080-0f6e-11e9-80aa-8813a053078c.png)

**Comment by alex-deaconu** [comment]
@robb-price this issue has now been fixed. We are now allowing a User to Subscribe as well as Start a Trial:

<img width="1093" alt="screen shot 2019-01-11 at 2 26 49 pm" src="https://user-images.githubusercontent.com/6218188/51128972-28c6f800-17f7-11e9-835e-71193b87ce04.png">

Closing. Thanks!
