### ISSUE TITLE
When you have a scheduled item for not the current month, the first time you open the calendar, it is the wrong month.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#796]
Expected Behavior:
When you have content scheduled to play with a start and end date in a certain month, when you open the start / end date calendar, it should open the calendar in the month the start or end date is in.

Actual Behavior:
When you open the start / end date Calendar, it will be in the current month. When you close and open again, it will be in the correct month.

For further clarification: https://goo.gl/V4xHdo

**Comment by alex-deaconu** [comment]
@robb-price this Issue has has now been corrected. When loading the Date Picker Calendar, the correct Date and Month should be selected. Thanks.
