### ISSUE TITLE
Display Monitoring Not Working Under Specific Companies

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/rise-vision-apps#804]
### What is the expected behavior?
When display monitoring is enabled, turning the display off should result in an e-mail alert shortly afterwards.

### What is the actual behavior?
Turning the display off does not result in an e-mail alert for any displays under the company. 

### What steps can be taken to replicate the problem?
Turn off a display associated with the problem company - a monitoring alert will never be generated.

**Comment by colby-maughan** [comment]
I logged this in apps due to discussion in HipChat yesterday - please let me know if this needs to be moved.

**Comment by ezequielc** [comment]
@colby-maughan Thanks.
@tejohnso Given the authorization API was returning 'authorized', I assume it  should be an issue on Display/Delivery side. Do you agree? Thanks

**Comment by tejohnso** [comment]
@ezequielc we'll take a look. I've moved the card.

**Comment by ezequielc** [comment]
@tejohnso Thanks, let us know if you need any help.

**Comment by alex-deaconu** [comment]
This issue is now resolved. Validated the fix with the user and added fixes to prevent this from happening again. Thanks.
