### ISSUE TITLE
Changing the order of widgets in a placeholder playlist results in unexpected behavior

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-vision-apps#807]
**Expected Behavior**
When changing the order of a widget in a placeholder playlist the widget is placed exactly where you try to move it.

**Actual Behavior** 
Moving a widget to a different location in the placeholder playlist doesn't work correctly. The widget is not placed where you try to move it. It tends to keep moving down in the playlist.

**Steps to reproduce**
1. Add multiple widgets to a single placeholder playlist
2. Try changing the order of the widgets in the playlist a few times.

**Comment by kaden-rise** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Defect 807 - Changing the order of widgets in a placeholder playlist results in unexpected behavior](https://trello.com/c/x33BEMNS/9323-defect-807-changing-the-order-of-widgets-in-a-placeholder-playlist-results-in-unexpected-behavior)

**Comment by alex-deaconu** [comment]
This issue should now be resolved. Closing. Thanks!
