### ISSUE TITLE
User Account Remains After Company Deletion

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/rise-vision-apps#811]
### What is the expected behavior?

Deleting a company deletes all data associated with the company, including users.

### What is the actual behavior?

Users appear to remain after a company is deleted, preventing the owners of the e-mail address from signing up under a different company. 

### What steps can be taken to replicate the problem?

Create a new user under a new company, then delete the company. Attempt to sign up using the same e-mail address.

**Comment by alex-deaconu** [comment]
@colby-maughan a fix for this issue has been deployed. I have confirmed that when a Company is deleted, the User's Authentication record is removed as well. This way, when they try to sign up again they are not given the error that we were seeing before. Thanks.
