### ISSUE TITLE
User is not authenticated error

### ISSUE THREAD

**Issue by nipuniitg** [Rise-Vision/rise-vision-apps#82]
Hi Rise-Vision developers,

I have followed the instructions given here ( https://help.risevision.com/developer/getting-started/registration/clientId ) to obtain the client_id and also registered the app on the https://developer.risevision.com/apps/list website. 
I have replaced the obtained client_id in the files rise-vision-app-launcher/web/bower_components/common-header/dist/js/common-header.js and rise-vision-app-launcher/web/bower_components/common-header/src/js/svc-config.js
And then deployed the code on an amazon ec2 instance. 
Ran the commands npm install , bower install, gulp build and gulp 
The site is up but I find one error.

As soon as I click "Sign up with Google" and login using the google account, I get a pop-up asking to fill more details like the image below
<img width="583" alt="screen shot 2016-02-11 at 11 43 01 pm" src="https://cloud.githubusercontent.com/assets/2149443/13026766/da7da53a-d259-11e5-98f8-f18513ba3f3e.png">

But as soon as I enter the details and click on "Create Account", I get this error message and gets redirected to the home page again.
![screen shot 2016-02-11 at 11 45 44 pm](https://cloud.githubusercontent.com/assets/2149443/13026769/ff40b574-d259-11e5-8339-85166bbf4002.png)

Am I missing something?
Any help is appreciated. Thanks

**Comment by ezequielc** [comment]
Hi @nipuniitg,

could you verify if your CLIENT_ID is correct in `dist/js/website.min.js` after deployment?
I guess your modifications are overridden after you run `bower install`.

Cheers!

**Comment by nipuniitg** [comment]
Hi @ezequielc ,
The CLIENT_ID is correct in dist/js/website.min.js after deployment.
Do we need to change the client_id for the LOGGER as well ?

**Comment by ezequielc** [comment]
@nipuniitg No, that shouldn't be necessary. 

One step that might be missing is to set NODE_ENV=prod .
By default, the app will connect to our development servers. 
Please set NODE_ENV=prod and run gulp build again.

If it still doesn't work, please send me your client_id and company id and I will check our logs.
You can send it support@risevision.com  re:Ezequiel.

Cheers!

**Comment by nipuniitg** [comment]
@ezequielc Sorry for the delay.

Here is the client id 1025993406491-hvtotav5gc01fijbmoas8dpvulrl2tnu.apps.googleusercontent.com and it is Blynq Company.
I have hosted the code on an amazon instance.
Thanks for your help.

**Comment by ezequielc** [comment]
@nipuniitg Thanks for the details.
I verified the logs and you really are using our development servers.
Please set NODE_ENV=prod and run gulp build again.

To verify it worked, make sure the API calls are pointing to https://rvaserver2.appspot.com/.

Let me know if it works! Cheers!

**Comment by nipuniitg** [comment]
Thanks a lot @ezequielc :) 
It's working now except that i'm seeing the names to be as below
<img width="742" alt="screen shot 2016-02-21 at 1 28 00 pm" src="https://cloud.githubusercontent.com/assets/2149443/13201610/7404407e-d89f-11e5-9fac-1311f0fe9958.png">

I have replaced my client_id in the files rise-vision-app-launcher/web/bower_components/common-header/dist/js/common-header.js and rise-vision-app-launcher/web/bower_components/common-header/src/js/svc-config.js

**Comment by ezequielc** [comment]
@nipuniitg Good to hear that it worked.

Now the problem is the translation file. Your `locales/translation_en.json` is not accessible. 

If you deployed by copying the `/dist` folder after the build, please make sure the permissions are correct for that file.

If you are serving the files by just running `gulp`, you need to change LOCALES_PREFIX in https://github.com/Rise-Vision/rise-vision-apps/blob/master/web/scripts/config/prod.js to 
use the source version:

```
.constant('LOCALES_PREFIX',
      'bower_components/rv-common-i18n/dist/locales/translation_')
```

Hope it helps.  Cheers!

**Comment by nipuniitg** [comment]
Thanks @ezequielc  it helped :D
