### ISSUE TITLE
Cannot update billing address on credit cards in Apps

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#838]
### What is the expected behavior?
Users can update their payment method details in-app by following the process documented in [this help center article](https://help.risevision.com/hc/en-us/articles/115000917226-How-do-I-update-or-change-my-credit-card-on-file-).

### What is the actual behavior?
Users cannot update the billing address information by following the process documented in [this help center article](https://help.risevision.com/hc/en-us/articles/115000917226-How-do-I-update-or-change-my-credit-card-on-file-).  When updating the card details, the billing address of the original card remains.

### What steps can be taken to replicate the problem?
1. In your Account page in the app, click on "Edit payment methods"
2. Add a new payment method.
3. Click on "Edit payment methods" again.
4. Click on the card you added in step 2
5. Click on "Edit payment method" to modify the card details.
6. You can update the card number, CVS, and expiration date, but there is no way to update the billing information.

**Comment by ezequielc** [comment]
@PatrickA-RiseVision Chargebee has a configuration to enable/disable those fields. I have enabled them now, so customers can update their credit card address. Thanks
