### ISSUE TITLE
Pages with lots of assets take a long time to load

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#839]
### What is the expected behavior?
All pages at https://apps.risevision.com should load quickly, regardless of how many items show on the page.

### What is the actual behavior?
Pages with several assets are taking too long to load.

### What steps can be taken to replicate the problem?
Log into a Company with several assets, usually Presentations or Displays. This also slows down the Home page as well.

For further clarification: https://goo.gl/NPkNzy

**Comment by ezequielc** [comment]
@robb-price I would like to treat this as an improvement rather than an issue. We have multiple areas that would benefit from faster load time and I will present it as an epic option soon. Let me know if you disagree. Thanks!
