### ISSUE TITLE
Pasting a spreadsheet into the text widget causes presentation to go blank and inaccessible in editor.risevision.com

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#84]
**How to recreate**
1. Using editor.risevision.com create a new presentation
2. Within that presentation, add 3 placeholders.
3. In two of those placeholders, add content of any type (I've used images for simplicity).
4. In the third placeholder, add the Text widget.
5. In a Google sheet that contains content, select a range of cells and copy.
6. Paste this into the Text Widget
7. Save presentation

**What happens**
The presentation goes completely blank, and the presentation is inaccessible from the Presentations screen, clicking the Presentation does not open anything.

**What should happen**
The presentation should save, all content should remain without being deleted, and the presentation should be fully accessible and editable. 

**Sample presentation**
http://bit.ly/1R8FqY5

**Video overview**
http://www.screencast.com/t/SdCy4n0n4fX5

**Notes**
- I am unable to replicate this in the RVA editor, I was able to paste into a Text Widget and save the presentation with no trouble.
- It appears this is caused by pasting a range of cells from a Spreadsheet, pasting from a Doc, website, or text editor does not replicate this issue.

**Comment by btfrise** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;NGCB3qZ0&#x2F;1484-2-problem-pasting-from-a-spreadsheet-into-the-text-widget-then-saving-presentation-causes-the-presentation-content-to-be-removed"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> (2) Problem - Pasting from a spreadsheet into the text widget, then saving presentation causes the presentation content to be removed.</a>

**Comment by ezequielc** [comment]
@btfrise A fix has been deployed. Could you please validate. Thanks!
