### ISSUE TITLE
Display Settings: Hitting the Enter key with your cursor in the Display Name field opens "Choose Your Plan"

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#842]
### What is the expected behavior?
Hitting the Enter key in the Display Name field in Display Settings commits your change to the Display Name.

### What is the actual behavior?
Hitting the Enter key in the Display Name field opens the "Choose Your Plan" popup.

### What steps can be taken to replicate the problem?
1. Log in to risevision.com.
2. Click on "Displays".
3. Select a Display by clicking on it.
4. Click into the Display Name field.
5. Hit Enter.

**Comment by ezequielc** [comment]
@PatrickA-RiseVision This is fixed. Let me know in case you still see the issue. Thanks!
