### ISSUE TITLE
When a user adds RSS, Text Scroller, or any Cenique gadget from the new Editor, the Editor refreshes.

### ISSUE THREAD

**Issue by hcs0** [Rise-Vision/rise-vision-apps#85]
When a user adds RSS, Text Scroller, or any Cenique gadget from the new Editor, the Editor refreshes.

**How to recreate**
In a new presentation in the new Editor, add a Placeholder containing a Cenique gadget / RSS gadget.  

**What happens**
When you add the Cenique gadget / RSS gadget the Editor refreshes. See http://recordit.co/Jqw58bR7BV for the Cenique gadget.  The same effect happens when a user adds the RSS gadget.

**What should happen**
When a user attempts to add a Cenique gadget / RSS gadget, the Editor should inform the user that the it is not compatible in the new Editor instead of refreshing back to the Start page.

Sample presentation:
New editor link: https://apps.risevision.com/editor/workspace/a3434544-abc9-4502-9fcf-3aa32365f567/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4
Classic editor link: https://rva.risevision.com/#/PRESENTATION_MANAGE/id=a3434544-abc9-4502-9fcf-3aa32365f567?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

**Notes**
When I open a presentation with a Cenique gadget created in RVA within the new Editor, I get the Deprecated Items message.
When I continue to open the Cenique gadget settings within the new Editor, I get a message in the widget stating that it’s not compatible.

**Comment by hcs0** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/conversation/1937559527

**Comment by hcs0** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/conversation/1945985993

**Comment by ezequielc** [comment]
@hcs0 @brianloosbrock @alanclayton I just deployed a fix for the issue. Whenever you add a Gadget, you should see Playlist Item settings and a warning message that Gadgets are not supported in the new Editor. 
Could you please confirm it is working? 
Thanks!

**Comment by hcs0** [comment]
@ezequielc @brianloosbrock @alanclayton I've tested RSS, Text Scroller,and all Cenique gadgets and can confirm the fix. :+1:
