### ISSUE TITLE
Tax being charged when labeled Tax Exempt in Chargebee

### ISSUE THREAD

**Issue by jrkuchta** [Rise-Vision/rise-vision-apps#851]
### What is the expected behavior?
In Chargebee, if "Exempt from Tax" = "Yes" and "Avalara Customer Usage Type" = "Tribe/Status Indian/Indian Band", a customer should not be charged sales tax.

### What is the actual behavior?
Two customers who are set up as tax exempt with the above attributes were taxed on their invoices.
https://risevision.chargebee.com/customers/542031/details
https://risevision.chargebee.com/customers/800891/details

Unsure if this has any bearing, but both customers billing addresses are in TN.

### What steps can be taken to replicate the problem?
I have not attempted to replicate the problem.

**Comment by olegrise** [comment]
Fixed the issue by adding corresponding tax exemption rule to Avalara.
