### ISSUE TITLE
Clicking Save on a new Template added from the library creates a duplicate

### ISSUE THREAD

**Issue by pcsandford** [Rise-Vision/rise-vision-apps#862]
###  What is the expected behaviour?
After adding a Template the user can click Save if they have made changes or not and then add to their schedule and only that Template is added.

### What is the actual behaviour?
After adding a new Template click Save and it looks like nothing happens, even if a change has been made the Publish button is not active. Click Save a few more times and then look at the Presentations view and you will see duplicate Templates, all listed as published, for the amount of times you clicked Save.

If you go back to the Template from the Presentation list and click Save the Publish button will become active as normal. Clicking Save no longer creates a duplicate.

### What steps can be taken to replicate the problem?
- Add a Template from the Library.
- Click on Save a few times.
- Go to the Presentations view.

**Comment by PatrickA-RiseVision** [comment]
This also happens if you make a copy of a presentation, and then click "Save".

**Comment by olegrise** [comment]
@pcsandford @PatrickA-RiseVision the fix is deployed to production. Thanks.
