### ISSUE TITLE
Company Industry is not being passed to Zendesk from Apps

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#868]
### What is the expected behavior?
Updating Industry in the Company Settings in the App updates the Industry in the matching CID company in Zendesk.

### What is the actual behavior?
Industry in the Company Settings in the App and Industry in the matching CID company in Zendesk do not appear to be linked.  Making a change does nothing.

### What steps can be taken to replicate the problem?
Add an industry to a company.  Specific example will follow in the Trello card.

**Comment by ezequielc** [comment]
@tejohnso I believe this is should go to Delivery. Do you agree? Thanks

**Comment by tejohnso** [comment]
@ezequielc We have a ZD proxy project that handles new tickets to ensure they have the industry. But there's nothing that is supposed to update industry based on changes from apps. I think this is a feature request that should be handled as part of the work to capture industry data from the user.

**Comment by ezequielc** [comment]
Based on @tejohnso's  comment, this will be handled as a new feature. Thanks
