### ISSUE TITLE
Text Widget not being rendered in Editor

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rise-vision-apps#87]
@alanclayton : 

Add the Text Widget to an empty Placeholder, add some text then save. Notice the Text is not being rendered in Editor. As long as the Text Widget is the first item in the Playlist, the text should be rendered.

**Comment by ezequielc** [comment]
@alanclayton Do you know if Gadget ID was changed for Text Widget? Thanks

**Comment by alanclayton** [comment]
@ezequielc Sure did. It is now 32d460d1-a727-4765-a8e9-587f7915ab05

Here is Time & Date if you want to do that one to 8b984369-f83c-4eca-add6-e431d338eaff

**Comment by ezequielc** [comment]
Thanks @alanclayton We will need to update it in our code. Thanks

**Comment by ezequielc** [comment]
@alanclayton I updated Text Widget ID in our code. Could you please confirm it is working? Thanks!

**Comment by ByronDarlison** [comment]
@alanclayton @ezequielc is this defect now closed? Thanks

**Comment by alanclayton** [comment]
@ByronDarlison @ezequielc Yes. Text Widget now rendered in Editor. Thanks.

@ezequielc Are you going to render Time & Date as well?

**Comment by ezequielc** [comment]
@alanclayton Time & Date would require more testing and I think it should be handled in a separate task.
@ByronDarlison Should we queue a card for Time & Date Widget rendering? Thanks

**Comment by ByronDarlison** [comment]
@ezequielc I think we missed this somewhere along the way. What's the points estimate for it? Thanks!

**Comment by ezequielc** [comment]
@ByronDarlison 1 point. Cheers

**Comment by ByronDarlison** [comment]
Yes, please queue a card. Thanks!
