### ISSUE TITLE
Cancelled but still active subscription shouldn't show message in Storage

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rise-vision-apps#875]
When a subscription is cancelled but has not expired yet, Storage is showing a message telling that the subscription is cancelled.
The message is confusing as Storage functionality is still available.

Instead, we should just not show the message. There is already a clearer message in CH.

<img width="1417" alt="Screen Shot 2019-03-25 at 6 13 32 PM" src="https://user-images.githubusercontent.com/7738553/54954726-13bec180-4f2a-11e9-9236-547c555c4e92.png">

**Comment by alex-deaconu** [comment]
A fix for this issue has been released. If the Company still has an Active Cancelled Subscription, we will no longer show the message. Otherwise, if Cancelled and Inactive, we will continue to show the message and CTA to Subscribe. Thanks!
