### ISSUE TITLE
Presentations: Placeholder timeline set to "Always", but HTML has a timeline and seems to be stuck on.

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#893]
### What is the expected behavior?
The Placeholder Timeline can be controlled in the editor in the Placeholder properties.

### What is the actual behavior?
We have a few examples of the Placeholder Timeline not being controlled correctly from Editor.  The timeline remains in the HTML and seems to behave unpredictably on a Display.

### What steps can be taken to replicate the problem?
I have existing presentations that are affected for observation/testing.  I will link them in Trello.

**Comment by alex-deaconu** [comment]
Discussed and some of the behaviour is consistent with the Timeline flag.

Could not replicate Display behaviour in other Presentation instances.

Closing. Thanks.
