### ISSUE TITLE
Highlighting text in a field and releasing the mouse button outside of window causes window to close without the option to save changes

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-vision-apps#902]
**Expected Behavior:**
Highlighting text in a field and releasing your mouse button outside of the window should not close it.

**Actual Behavior:**
Highlighting text in a field and releasing the mouse button outside of the window causes the window to close.

**Steps to reproduce:**
Watch this video: https://drive.google.com/file/d/1_HGY9anivAfUM0jM6MfZk-EpblFq_EG9/view?usp=sharing

**Comment by alex-deaconu** [comment]
@kaden-rise it was decided that this is expected behaviour and we will not be fixing. Closing issue. Thanks.

**Comment by colby-maughan** [comment]
@sheadarlison @ezequielc @kaden-rise Re-opening per discussion in conversion room.

**Comment by alex-deaconu** [comment]
@kaden-rise @colby-maughan this issue should now be fixed. We are now detecting if the click was initiated within the modal and no longer closing it if they release the click outside. Thanks.
