### ISSUE TITLE
Setting Displays to Free auto assigns the license to a different Display

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#910]
### What is the expected behavior?
When you change a Display from Licensed to Free and press Save, you should be able to have 1 Display License available to assign wherever you need to.

### What is the actual behavior?
In the case of Companies that had assigned more Displays than they were licensed to, now that we have fixed that issue, when they change a Display from Licensed to Free and press Save, that License is going to a different Display in the Parent or Sub Company.

### What steps can be taken to replicate the problem?
The Company where this can be created will be added to the Trello Card.

**Comment by alex-deaconu** [comment]
We provided a list of the Displays that were assigned Licenses. Also did an investigation on whether there was an issue with the assignment, but did not determine that to be the case.

An improvement to the logic is being considered but not within the scope of this issue.

Closing. Thanks!
