### ISSUE TITLE
Template Editor: Template name shifts out of view when it is long 

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#928]
Screenshot of issue happening: https://www.screencast.com/t/5cwN1Yk2wgFQ

Template where it occurs: https://apps.risevision.com/templates/edit/cb997e91-0e21-4081-87f7-b93a6ce90fa4?cid=7fa5ee92-7deb-450b-a8d5-e5ed648c575f

How it should work: template name should appear correctly aligned, [screenshot](https://app.zeplin.io/project/5c58a8a2b74a443081a59e09/screen/5ca038ecc2d2d2052d7590f3)

**Comment by santiagonoguez** [comment]
And in Safari it looks even worse !

**Comment by santiagonoguez** [comment]
Also iPhone X Chrome looks very bad

**Comment by santiagonoguez** [comment]
Also Samsung Chrome sometimes looks very bad

**Comment by alex-deaconu** [comment]
@sheadarlison @santiagonoguez I've addressed some of the issues listed in this PR with 3 fixes in Apps and the Stretchy library. I was not able to replicate any more issues, but if we do discover any we can reopen or log a more specific issues. Closing. Thanks!

**Comment by santiagonoguez** [comment]
@alex-deaconu thanks ! :D
