### ISSUE TITLE
Template Editor: Back button doesn't trigger modal

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#929]
Video:  https://www.screencast.com/t/uKs0mncEhvD

How it should work: When I click back the first time I am presented with the warning modal.

**Comment by alex-deaconu** [comment]
@sheadarlison this issue should now be resolved. The additional page in the browser history should no longer be generated, so the warning should come up right away when the back button is clicked. Closing. Thanks!

**Comment by sheadarlison** [comment]
👍 Thanks @alex-deaconu
