### ISSUE TITLE
Template Editor: Template could not be deleted without being saved first.

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#932]
Video attached to card: https://trello.com/c/7167eN4X/6799-template-editor-issues

**Steps**

1. Add Presentation
2. Delete presentation without saving
3. Notification - “Failed to delete presentation. The presentation could not be found. Please validate it still exists.”

**Comment by alex-deaconu** [comment]
@sheadarlison this issue is now resolved. To confirm, the issue occurs because the HTML Template doesn't actually exist since it hasn't been saved. The error is expected behaviour.

To fix this, we are disabling the Delete button until save.

Thanks!

**Comment by sheadarlison** [comment]
👍  Thanks @alex-deaconu
