### ISSUE TITLE
Template Editor: Can’t publish after first save 

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#933]
Video on card: https://trello.com/c/7167eN4X/6799-template-editor-issues

**Comment by ezequielc** [comment]
@sheadarlison As discussed in the execution strategy doc, this is the expected behaviour as first Save will automatically publish the Template. I am closing the issue. Thanks!

**Comment by sheadarlison** [comment]
Sounds good @ezequielc
