### ISSUE TITLE
Template Editor Issue: Preview on iOS is not following the margins that other platforms ( Android, desktop ) do follow. 

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#935]
Screenshot: https://trello-attachments.s3.amazonaws.com/55b10a8302680b3aea04ed90/5cc7549485f6234127188053/3fc9d3690a2dbb749f38c4a7cd54058b/iphone.png

**Comment by ezequielc** [comment]
@santiagonoguez fixed this issue: https://github.com/Rise-Vision/rise-vision-apps/pull/941. Thanks!
