### ISSUE TITLE
Widget settings show in classic editor but not new editor.

### ISSUE THREAD

**Issue by brianloosbrock** [Rise-Vision/rise-vision-apps#94]
I'm working on a new widget with a vendor and I can open the configuration settings in classic editor but not in new editor. Video overview here https://goo.gl/NavP8G.

I'll send the test account information separately. 

@ezequielc

**Comment by ezequielc** [comment]
@brianloosbrock I tried to open the Settings in RVA and new Editor and it didn't work in any of them. 

![screenshot from 2016-02-24 16 26 52](https://cloud.githubusercontent.com/assets/7738553/13297946/950a7196-db13-11e5-857a-8293a07e435a.png)

The Settings URL leads to a page not found: https://www.unifiedbrandmedia.com/data/widgets/financials/previousclose/settings.html

I guess you had Settings cached in RVA. Could you double check the URL?

Thanks!

**Comment by brianloosbrock** [comment]
@ezequielc They changed the URL and looks like they removed the one I originally had problems with. The new one now opens in both classic and new editor. This issue can be closed. Thanks

**Comment by ezequielc** [comment]
Thanks @brianloosbrock !
