### ISSUE TITLE
Clicking of Classic Editor link goes to an error page

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#946]
### What is the expected behavior?
When you click the Classic Editor link at http://apps.risevision.com, you should be taken to http://rva.risevision.com.

### What is the actual behavior?
When you click on the Classic Editor link, you are taken to an error page:
![2019-05-03_07-18-55](https://user-images.githubusercontent.com/6862256/57134330-d98bdf80-6d73-11e9-9897-1d9af2990283.gif)

### What steps can be taken to replicate the problem?
Click on the Classic Editor link.

**Comment by alex-deaconu** [comment]
@robb-price this issue should now be resolved. The Classic Editor link should work correctly. Thanks!
