### ISSUE TITLE
User not asked to confirm Industry when navigating to sub-company

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-vision-apps#951]
Problem
As a User, when I navigate to a sub-company I am not prompted to specify the industry of the sub-company. As a result, templates notifications are not shown.

I should be asked to confirm the industry for the company I belong to, or a sub-company when I navigate to it. Note: a user that belongs to the Rise Vision Company should not be asked to confirm industry of a sub-company.

**Comment by olegrise** [comment]
@alanclayton this issue is now fixed. Thanks.

**Comment by alanclayton** [comment]
@olegrise 👍
