### ISSUE TITLE
Trial days length in banners is different

### ISSUE THREAD

**Issue by RowanDarlison** [Rise-Vision/rise-vision-apps#955]
### What is the expected behavior?
The dates in the banners match.

### What is the actual behavior?
The dates in the banners are different.

### What steps can be taken to replicate the problem?
https://apps.risevision.com/storage?cid=be918edf-f7d1-4f72-a6b6-b6fb3b2acc37

**Comment by alex-deaconu** [comment]
@RowanDarlison a fix for this issue has been deployed. To confirm, we are now showing the rounded up value for the trial days. So when starting a Trial, we will show 14 days (as opposed to 13). Closing. Thanks!
