### ISSUE TITLE
Summer Countdown template can't be selected outside the Rise Vision company

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#956]
### What is the expected behavior?
When adding a new presentation, you can select the Summer Countdown template and add a copy of it to your presentations.

### What is the actual behavior?
When adding a new presentation, selecting the Summer Countdown template prompts you to subscribe.
![image](https://user-images.githubusercontent.com/40774237/57414167-651acb80-71cd-11e9-9de7-694c782f5b7e.png)

### What steps can be taken to replicate the problem?
- Log into any test company as a user that doesn't belong to the Rise Vision company
- Add a presentation
- Choose the Summer Countdown template
- Click "Start with this template" OR click "Add" from the template list

**Comment by sheadarlison** [comment]
Fixed, template wasn't shared correctly.
