### ISSUE TITLE
Template Editor: Preview is cutting off some content on the right side

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#959]
OS: Windows 10 
Browser: Chrome latest version 
Screen resolution: 2560x1440
Scale: 150% 

Issue: https://www.screencast.com/t/N6QfImkR8UN

**Comment by ezequielc** [comment]
@sheadarlison A fix has been released. Thanks!

**Comment by sheadarlison** [comment]
👍 thanks @ezequielc
