### ISSUE TITLE
Dragging the Top Presentation in a Schedule and then using the up/down arrows in the UI causes Presentations to occasionally move up too far and appear in incorrect locations

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/rise-vision-apps#960]
### What is the expected behavior?

Dragging the top presentation and using the up/down arrows to adjust works more or less the same.

### What is the actual behavior?

Dragging the first item in the playlist does not seem to correctly update the playlist - the up arrow is grayed out, and pressing the up arrow on an item beneath it causes it to jump to another location in the playlist sometimes. Down arrow above the moved item seems to work without issue. Sometimes you are able to cycle back and forth between a presentation that is currently off-screen and should not be getting moved, as it's swapping places with a presentation much farther up the list. Issue appears to get worse the more schedules are adjusted via dragging. 

### What steps can be taken to replicate the problem?

1. Create a schedule with several presentations. More presentations seem to make this issue more prevalent. 
2. Drag the first presentation down a few spots. This seems easiest to replicate when you scroll wheel down to find a spot farther from the beginning of the schedule.
3. Press the Up Arrow beneath the previously dragged presentation.
4. The presentation will now be somewhere it is not supposed to be. Sometimes it only skips over one presentation, sometimes multiple.

**Comment by alex-deaconu** [comment]
@colby-maughan we have deployed a fix that should resolve this issue. Please let us know if you encounter it anymore. Thanks!
