### ISSUE TITLE
Template Editor: Symbol name when searched is different from symbol name in most popular list

### ISSUE THREAD

**Issue by RowanDarlison** [Rise-Vision/rise-vision-apps#966]
Symbol name when searched is different from symbol name in most popular list - ex. GCC1 (GOLD). And when you add the symbol the same problem applies, if it’s added from most popular it uses the short name if it’s added from search it uses the long name. When you search GCC1 the complex name shows up. Video showing the problem happening with Currencies as well: https://www.screencast.com/t/medKtM37ufx

**Comment by alex-deaconu** [comment]
@RowanDarlison this issue should now be resolved. The names should match across the two lists. Thanks!

**Comment by RowanDarlison** [comment]
Looks good!
