### ISSUE TITLE
Drag and Drop in Placeholders rearranges your content after you move it around

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#979]
### What is the expected behavior?
When you arrange the content in a Placeholder via drag and drop, it should remain in that order.

### What is the actual behavior?
The content is not staying in the order you set it in.

### What steps can be taken to replicate the problem?
The steps in this video show how to recreate: 
https://drive.google.com/a/risevision.com/file/d/1P01RjYOR-zZRz_WsWddpM3-0dSozecjv/view?usp=drivesdk

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Issue 979 - Drag and Drop in Placeholders is not working](https://trello.com/c/N9ZAMa7T/10120-3-issue-979-drag-and-drop-in-placeholders-is-not-working)

**Comment by alex-deaconu** [comment]
@robb-price we have deployed a fix that should resolve this issue. Please let us know if you encounter it anymore. Thanks!
