### ISSUE TITLE
Template Editor shows blank attributes list

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rise-vision-apps#992]
Template Editor doesn't show the attributes list when I leave the Editor having a selected Attribute and add a new HTML Presentation.

Video: https://drive.google.com/file/d/11Infm4FePXNfWyW0y8zBVzalq8wvgWQ-/view?usp=sharing 

### Reproduction Steps

1. Add a new HTML Presentation
1. Click on one of the attributes
1. Leave the Editor without saving
1. Create a new HTML Presentation

### Expected Results
It should show the attributes list.

### Actual Results
It doesn't show the attributes

**Comment by olegrise** [comment]
@ezequielc nice! I saw this happening but couldn't find a way to reproduce it.
